spark.sql("""
CREATE OR REPLACE TEMP VIEW vw_darts_site_mapping_seed AS
SELECT
    col1 AS SiteCode,
    col2 AS ClinicName,
    col3 AS DataBaseName,
    col4 AS ETLName,
    col5 AS MethodName,
    col6 AS IsActive
FROM VALUES
    ('AHK', 'Ahoskie', 'SAMMS-Ahoskie', 'Darts', 'DartsSrv', 1),
    ('B12B', 'ColoradoSprings', 'SAMMS-ColoradoSpringsV5', 'Darts', 'DartsSrv', 1),
    ('B24', 'Paintsville', 'SAMMS-PaintsvilleV5', 'Darts', 'DartsSrv', 1),
    ('B25', 'Pikeville', 'SAMMS-PikevilleV5', 'Darts', 'DartsSrv', 0),
    ('B26', 'Hazard', 'SAMMS-HazardV5', 'Darts', 'DartsSrv', 0),
    ('B27', 'Savannah', 'SAMMS-SavannahV6', 'Darts', 'DartsSrv', 0),
    ('B28', 'WestPlaines', 'SAMMS-WestPlainesV5', 'Darts', 'DartsSrv', 0),
    ('B29', 'PoplarBluff', 'SAMMS-PoplarBluffV5', 'Darts', 'DartsSrv', 0),
    ('B30', 'KCN', 'SAMMS-KCNv5', 'Darts', 'DartsSrv', 0),
    ('B31', 'Dyersburg', 'SAMMS-DyersburgV5', 'Darts', 'DartsSrv', 0),
    ('B33', 'Paducah', 'SAMMS-Paducah', 'Darts', 'DartsSrv', 0),
    ('B34', 'Corbin', 'SAMMS-CorbinV5', 'Darts', 'DartsSrv', 0),
    ('B35', 'Lexington', 'SAMMS-LexingtonV5', 'Darts', 'DartsSrv', 0),
    ('B35A', 'Berea', 'SAMMS-BereaV5', 'Darts', 'DartsSrv', 0),
    ('B36', 'Asheville', 'SAMMS-AshevilleV5', 'Darts', 'DartsSrv', 0),
    ('B37', 'Clyde', 'SAMMS-ClydeV5', 'Darts', 'DartsSrv', 0),
    ('B38', 'Spartanburg', 'SAMMS-SpartanburgV5', 'Darts', 'DartsSrv', 0),
    ('B39', 'Aiken', 'SAMMS-AikenV5', 'Darts', 'DartsSrv', 0),
    ('B41', 'Chesapeake', 'SAMMS-ChesapeakeV5', 'Darts', 'DartsSrv', 0),
    ('B42', 'VirginiaBeach', 'SAMMS-VirginiaBeachV5', 'Darts', 'DartsSrv', 0),
    ('B42A', 'NewportNews', 'SAMMS-NewportNewsV5', 'Darts', 'DartsSrv', 0),
    ('B42B', 'Franklin', 'SAMMS-FranklinV5', 'Darts', 'DartsSrv', 0),
    ('B42C', 'GlenAllen', 'SAMMS-GlenAllenV5', 'Darts', 'DartsSrv', 0),
    ('B42D', 'ChesapeakeSouth', 'SAMMS-ChesapeakeSouthV5', 'Darts', 'DartsSrv', 0),
    ('B44', 'Albany', 'SAMMS-AlbanyV5', 'Darts', 'DartsSrv', 0),
    ('B45', 'Tifton', 'SAMMS-TiftonV5', 'Darts', 'DartsSrv', 0),
    ('B46', 'WashingtonDC', 'SAMMS-WashingtonDCv5', 'Darts', 'DartsSrv', 0),
    ('B47', 'Mobile', 'SAMMS-MobileV5', 'Darts', 'DartsSrv', 0),
    ('B48', 'Tuscaloosa', 'SAMMS-TuscaloosaV5', 'Darts', 'DartsSrv', 0),
    ('B51', 'NorthLittleRock', 'SAMMS-NorthLittleRockV6', 'Darts', 'DartsSrv', 0),
    ('B52', 'JacksonGA', 'SAMMS-JacksonGAV5', 'Darts', 'DartsSrv', 0),
    ('B54', 'Gadsden', 'SAMMS-GadsdenV5', 'Darts', 'DartsSrv', 0),
    ('B55', 'Shoals', 'SAMMS-ShoalsV5', 'Darts', 'DartsSrv', 0),
    ('B57', 'Pawtucket', 'SAMMS-Pawtucket', 'Darts', 'DartsSrv', 0),
    ('B57A', 'Johnston', 'SAMMS-Johnston', 'Darts', 'DartsSrv', 0),
    ('B57B', 'Middletown', 'SAMMS-Middletown', 'Darts', 'DartsSrv', 0),
    ('B57C', 'Providence', 'SAMMS-Providence', 'Darts', 'DartsSrv', 0),
    ('B57D', 'Westerly', 'SAMMS-Westerly', 'Darts', 'DartsSrv', 0),
    ('B66A', 'Bremen', 'SAMMS-Bremen', 'Darts', 'DartsSrv', 0),
    ('B72', 'Mobile-OBOT', 'SAMMS-Mobile-OBOT', 'Darts', 'DartsSrv', 0),
    ('B73', 'Montgomery', 'SAMMS-Montgomery', 'Darts', 'DartsSrv', 0),
    ('B75', 'Lawrence', 'SAMMS-LawrenceV6', 'Darts', 'DartsSrv', 0),
    ('B76', 'Huntsville-OBOT', 'SAMMS-Huntsville-OBOT', 'Darts', 'DartsSrv', 0),
    ('BAT', 'Batesville', 'SAMMS-Batesville', 'Darts', 'DartsSrv', 0),
    ('BG', 'BowlingGreen', 'SAMMS-BowlingGreen', 'Darts', 'DartsSrv', 0),
    ('BOI', 'Boise', 'SAMMS-Boise', 'Darts', 'DartsSrv', 0),
    ('CBCO', 'CoeurdAlene', 'SAMMS-CoeurdAleneV6', 'Darts', 'DartsSrv', 0),
    ('CON', 'Conway', 'SAMMS-Conway', 'Darts', 'DartsSrv', 0),
    ('D07', 'Knoxville', 'SAMMS-KnoxvilleV6', 'Darts', 'DartsSrv', 0),
    ('D08', 'Madison', 'SAMMS-MadisonV6', 'Darts', 'DartsSrv', 0),
    ('D09', 'Murfreesboro', 'SAMMS-MurfreesboroV6', 'Darts', 'DartsSrv', 0),
    ('DA', 'Davenport', 'SAMMS-Davenport', 'Darts', 'DartsSrv', 0),
    ('DM', 'DesMoines', 'SAMMS-DesMoines', 'Darts', 'DartsSrv', 0),
    ('DRD-CO', 'Columbia', 'SAMMS-ColumbiaV5', 'Darts', 'DartsSrv', 0),
    ('DRD-KC', 'KC', 'SAMMS-KCv5', 'Darts', 'DartsSrv', 0),
    ('DRD-KVB', 'KVB', 'SAMMS-KVBv5', 'Darts', 'DartsSrv', 0),
    ('DRD-KVC', 'KVC', 'SAMMS-KVCv5', 'Darts', 'DartsSrv', 0),
    ('DRD-NOLA', 'NOLA', 'SAMMS-NOLAv5', 'Darts', 'DartsSrv', 0),
    ('DRD-SF', 'SF', 'SAMMS-SFv5', 'Darts', 'DartsSrv', 0),
    ('ELC', 'ElizabethCity', 'SAMMS-ElizabethCity', 'Darts', 'DartsSrv', 0),
    ('ET', 'Elizabethtown', 'SAMMS-Elizabethtown', 'Darts', 'DartsSrv', 0),
    ('FAY', 'Fayetteville', 'SAMMS-Fayetteville', 'Darts', 'DartsSrv', 0),
    ('FR', 'Frankfort', 'SAMMS-Frankfort', 'Darts', 'DartsSrv', 0),
    ('FS', 'FortSmith', 'SAMMS-FortSmith', 'Darts', 'DartsSrv', 0),
    ('FW', 'FortWayne', 'SAMMS-FortWayne', 'Darts', 'DartsSrv', 0),
    ('GAL', 'Gaylord', 'SAMMS-Gaylord', 'Darts', 'DartsSrv', 0),
    ('HGT', 'Hagerstown', 'SAMMS-Hagerstown', 'Darts', 'DartsSrv', 0),
    ('HNT', 'Huntsville', 'SAMMS-Huntsville', 'Darts', 'DartsSrv', 0),
    ('HS', 'HotSprings', 'SAMMS-HotSprings', 'Darts', 'DartsSrv', 0),
    ('JON', 'Jonesboro', 'SAMMS-Jonesboro', 'Darts', 'DartsSrv', 0),
    ('LAN', 'Lansing', 'SAMMS-Lansing', 'Darts', 'DartsSrv', 0),
    ('LO', 'Louisville', 'SAMMS-Louisville', 'Darts', 'DartsSrv', 0),
    ('LV1', 'Cheyenne', 'SAMMS-Cheyenne', 'Darts', 'DartsSrv', 0),
    ('LV2', 'DesertInn', 'SAMMS-DesertInn', 'Darts', 'DartsSrv', 0),
    ('LV3', 'McDaniel', 'SAMMS-McDaniel', 'Darts', 'DartsSrv', 0),
    ('MNRE', 'Monroe', 'SAMMS-Monroe', 'Darts', 'DartsSrv', 0),
    ('MP', 'MtPleasant', 'SAMMS-MtPleasant', 'Darts', 'DartsSrv', 0),
    ('MRD', 'Meridian', 'SAMMS-Meridian', 'Darts', 'DartsSrv', 0),
    ('NC', 'NorthCharleston', 'SAMMS-NorthCharleston', 'Darts', 'DartsSrv', 0),
    ('NLR', 'NLROBOT', 'SAMMS-NLROBOT', 'Darts', 'DartsSrv', 0),
    ('PH', 'Phoenix', 'SAMMS-Phoenix', 'Darts', 'DartsSrv', 0),
    ('RE', 'Reno', 'SAMMS-Reno', 'Darts', 'DartsSrv', 0),
    ('RMD', 'Richmond', 'SAMMS-Richmond', 'Darts', 'DartsSrv', 0),
    ('SFN', 'SFN', 'SAMMS-SFNv5', 'Darts', 'DartsSrv', 0),
    ('SHP', 'Shreveport', 'SAMMS-Shreveport', 'Darts', 'DartsSrv', 0),
    ('STN', 'Staunton', 'SAMMS-Staunton', 'Darts', 'DartsSrv', 0),
    ('STVN', 'Stevenson', 'SAMMS-Stevenson', 'Darts', 'DartsSrv', 0),
    ('TE', 'Tempe', 'SAMMS-Tempe', 'Darts', 'DartsSrv', 0),
    ('TEX', 'Texarkana', 'SAMMS-Texarkana', 'Darts', 'DartsSrv', 0),
    ('TTCA', 'Bessemer', 'SAMMS-BessemerV5', 'Darts', 'DartsSrv', 0),
    ('TTCB', 'Cullman', 'SAMMS-CullmanV5', 'Darts', 'DartsSrv', 0),
    ('TTCC', 'GrandBay', 'SAMMS-GrandBay', 'Darts', 'DartsSrv', 0),
    ('TU', 'Tucson', 'SAMMS-Tucson', 'Darts', 'DartsSrv', 0),
    ('V1', 'VCPHCS-I-Memphis', 'SAMMS-VCPHCS-I-MemphisV5', 'Darts', 'DartsSrv', 0),
    ('V10', 'Boulder', 'SAMMS-BoulderV5', 'Darts', 'DartsSrv', 0),
    ('V10A', 'FortCollins', 'SAMMS-FortCollinsV5', 'Darts', 'DartsSrv', 0),
    ('V11', 'VCPHCS-XI-NorthDenver', 'SAMMS-VCPHCS-XI-NorthDenverV5', 'Darts', 'DartsSrv', 0),
    ('V12', 'VCPHCS-XII-DowntownDenver', 'SAMMS-VCPHCS-XII-DowntownDenverV5', 'Darts', 'DartsSrv', 0),
    ('V12A', 'Centennial', 'SAMMS-CentennialV5', 'Darts', 'DartsSrv', 0),
    ('V14', 'VCPHCS-XIV-Bridgeway', 'SAMMS-VCPHCS-XIV-BridgewayV5', 'Darts', 'DartsSrv', 0),
    ('V15', 'Joplin', 'SAMMS-JoplinV5', 'Darts', 'DartsSrv', 0),
    ('V17', 'ColumbiaTN', 'SAMMS-ColumbiaTNv5', 'Darts', 'DartsSrv', 0),
    ('V19', 'Jackson', 'SAMMS-JacksonV5', 'Darts', 'DartsSrv', 0),
    ('V20', 'Paris', 'SAMMS-ParisV5', 'Darts', 'DartsSrv', 0),
    ('V21', 'Raleigh', 'SAMMS-RaleighV5', 'Darts', 'DartsSrv', 0),
    ('V5', 'NONTC', 'SAMMS-NONTCv5', 'Darts', 'DartsSrv', 0),
    ('V5B', 'Houma', 'SAMMS-HoumaV6', 'Darts', 'DartsSrv', 0),
    ('V6', 'LC', 'SAMMS-LCv5', 'Darts', 'DartsSrv', 0),
    ('V8', 'VCPHCS-VIII-Memphis', 'SAMMS-VCPHCS-VIII-MemphisV5', 'Darts', 'DartsSrv', 0),
    ('V9', 'Nashville', 'SAMMS-NashvilleV5', 'Darts', 'DartsSrv', 0),
    ('VBRA', 'Brainerd', 'SAMMS-BrainerdV6', 'Darts', 'DartsSrv', 0),
    ('VBRP', 'BrooklynPark', 'SAMMS-BrooklynParkV6', 'Darts', 'DartsSrv', 0),
    ('VMIN', 'Minneapolis', 'SAMMS-MinneapolisV6', 'Darts', 'DartsSrv', 0),
    ('VWBY', 'Woodbury', 'SAMMS-WoodburyV6', 'Darts', 'DartsSrv', 0),
    ('WIL', 'Wilson', 'SAMMS-Wilson', 'Darts', 'DartsSrv', 0)
""")

spark.sql("""
MERGE INTO bhg_bronze.dbo.site_mapping AS tgt
USING vw_darts_site_mapping_seed AS src
ON  tgt.SiteCode = src.SiteCode
AND tgt.ETLName = src.ETLName
AND tgt.MethodName = src.MethodName
WHEN MATCHED THEN UPDATE SET
    tgt.ClinicName = src.ClinicName,
    tgt.DataBaseName = src.DataBaseName,
    tgt.IsActive = src.IsActive
WHEN NOT MATCHED THEN INSERT (
    SiteCode,
    ClinicName,
    DataBaseName,
    ETLName,
    MethodName,
    IsActive
)
VALUES (
    src.SiteCode,
    src.ClinicName,
    src.DataBaseName,
    src.ETLName,
    src.MethodName,
    src.IsActive
)
""")

print("Darts site_mapping MERGE completed")