select distinct SiteCode, FormName, convert(varchar(100),FormId) FormId, ClientId, CreatedOn, UpdatedOn, Isdeleted 
, CompletedBySignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'CompletedBySignatureSignatureDate' order by [DateTime] desc) 
, CounselorSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and 
 (DateField = 'CounselorSignatureSignatureDate' or DateField = 'CounselorSignatureDate') order by [DateTime] desc) 
, DoctorSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'DoctorSignatureSignatureDate' order by [DateTime] desc) 
, MedicalProviderSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'MedicalProviderSignatureSignatureDate' order by [DateTime] desc) 
, PatientSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'PatientSignatureDate' order by [DateTime] desc) 
, ProviderSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'ProviderSignatureSignatureDate' order by [DateTime] desc) 
, RequestorSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'RequestorSignatureDate' order by [DateTime] desc) 
, StaffSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'StaffSignatureDate' order by [DateTime] desc) 
, SupervisorSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'SupervisorSignatureSignatureDate' order by [DateTime] desc) 
 from (SELECT a.SiteCode, FormName = 'Periodic Reassessment', FormId = '', 
         a.ClientId, a.CreatedOn, a.ModifiedOn,PatientSignatureDate, CounselorSignatureDate, ProviderSignatureDate, SupervisorSignatureDate
FROM [pats].[Tbl_NewPeriodicReassessment] a
left join [pats].[Tbl_NewPeriodicReassessmentCounselorReview] b
on a.id = b.newperiodicreassessmentID
)

/*
select SiteCode, FormName, FormID, PreadmissionId, ClientId, QuestionID 
     , QuestionOrderID = Row_Number() over(Partition by v.FormName, v.FormId, v.ClientId, v.QuestionId order by v.QuestionId)
     , QuestionText, OptionID, AnswerValue, Createdby, CreatedOn, UpdatedBy, UpdatedOn, IsDeleted, preDel from (
     Select SiteCode = '" + st.SiteCode.ToString() + "', 'Admission Assessment' as [FormName] 
          , '7-' + convert(varchar, ClientId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID] 
          , PreAdmissionId, ClientId, 0 as QuestionID, 1 as QuestionOrderID, null as QuestionText, null as [OptionID], null as AnswerValue 
          , a.Createdby, convert(date, a.CreatedOn) as [CreatedOn], a.ModifiedBy as [UpdatedBy], convert(date, a.ModifiedOn) as [UpdatedOn], a.Isdeleted --, d.IsDeleted isd
          , b.IsDeleted preDel
       from [dbo].[AdmissionAssessment] a --left join SF_DataForms d on (a.ClientId = d.PatientId) where d.FormName = 'Admission Assessment'
       left join SF_PatientPreAdmission b on (a.PreAdmissionId = b.ID and a.ClientId = b.PatientID)
       ) v


select * from SF_PatientPreAdmission where ID = 108
select * from SF_DataForms where FormName = 'Admission Assessment'

select * /*distinct SiteCode = '" + st.SiteCode.ToString() + "', 'MN - DAANES Notification Form' as [FormName]
     , '22-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID] 
     , ClientId = isnull(a.ClientId, 0), convert(date, a.CreatedOn) as [CreatedOn], convert(date, a.ModifiedOn) as [UpdatedOn], a.Isdeleted
     , CompletedBySignatureSignatureDate = null 
     , CounselorSignatureSignatureDate = null 
 --case when convert(date, CounselorsignatureDate) is null then '1900-01-01' else convert(date, CounselorsignatureDate) end 
     , DoctorSignatureSignatureDate = null 
     , MedicalProviderSignatureSignatureDate = null
     , PatientSignatureDate = null
     , ProviderSignatureSignatureDate = null
     , RequestorSignatureDate = null
     , [StaffSignatureDate] = case when convert(date, StaffSignatureDate) is null then '1900-01-01' else convert(date, StaffSignatureDate) end
     , SupervisorSignatureSignatureDate = null */
  from [dbo].tblMAARC a 


select SiteCode, FormName, FormID, PreadmissionId, ClientId, QuestionID 
     , QuestionOrderID = Row_Number() over(Partition by q.FormName, q.FormId, q.ClientId, q.QuestionId order by q.QuestionId) 
     , QuestionText, OptionID, AnswerValue, Createdby, CreatedOn, UpdatedBy, UpdatedOn, IsDeleted from (
   Select SiteCode = '" + st.SiteCode.ToString() + "', 'Consent to Treatment with an Approved Narcotic'  as [FormName] 
        , '4-' + convert(varchar, c.ClientId) + '-' + convert(varchar, c.PreAdmissionId) + '-' + convert(varchar, c.id) as [FormID] 
        , c.PreAdmissionId, c.ClientId, 0 as QuestionID, 1 as QuestionOrderID, null as QuestionText, null as [OptionID], null as AnswerValue 
        , c.Createdby, convert(date, c.CreatedOn) as [CreatedOn], c.ModifiedBy as [UpdatedBy], convert(date, ModifiedOn) as [UpdatedOn]
        , IsDeleted = case when isnull(c.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(df.IsDeleted,0) = 0 then 0 else 1 end
     from [dbo].NCPIE c
     inner join SF_PatientPreAdmission pa on (c.PreAdmissionId = pa.ID)
     left join SF_DataForms df on (c.DataFormId = df.Id)
   ) q

select * from StateFactForm where DataFormId < 0
select abs(DataFormId), DataFormId from SF_PatientPreAdmission where DataFormId < 0
    select * from SF_DataForms where FormName = 'Consent to Treatment with an Approved Narcotic' --id in (7595, 7596)
*/

select distinct SiteCode, FormName, convert(varchar(100),FormId) FormId, ClientId, CreatedOn, UpdatedOn, Isdeleted 
, CompletedBySignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'CompletedBySignatureSignatureDate' order by [DateTime] desc) 
, CounselorSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and 
 (DateField = 'CounselorSignatureSignatureDate' or DateField = 'CounselorSignatureDate') order by [DateTime] desc) 
, DoctorSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'DoctorSignatureSignatureDate' order by [DateTime] desc) 
, MedicalProviderSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'MedicalProviderSignatureSignatureDate' order by [DateTime] desc) 
, PatientSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'PatientSignatureDate' order by [DateTime] desc) 
, ProviderSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'ProviderSignatureSignatureDate' order by [DateTime] desc) 
, RequestorSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'RequestorSignatureDate' order by [DateTime] desc) 
, StaffSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'StaffSignatureDate' order by [DateTime] desc) 
, SupervisorSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'SupervisorSignatureSignatureDate' order by [DateTime] desc) 
 from (select SiteCode = 'B27', ft.FormName, f.id as FormId, f.ClientId, f.CreatedOn, f.UpdatedOn, IsDeleted = case when isnull(f.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end  from dbo.Form f left join FormTemplate ft on (f.FormTemplateId = ft.Id) inner join [dbo].[SF_PatientPreAdmission] pa on (f.PreAdmissionId = pa.ID)  left join dbo.SF_DataForms d on (pa.DataFormId = d.Id)/*')*/ union select SiteCode = 'B27', ft.FormName, f.id as FormId, f.ClientId, f.CreatedOn, f.UpdatedOn, IsDeleted = case when isnull(f.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end from dbo.Form f left join FormTemplate ft on(f.FormTemplateId = ft.Id) inner join [dbo].[SF_PatientPreAdmission] pa on (f.PreAdmissionId = pa.ID)  left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) where /*(f.CreatedOn >= '1/1/2024' or isnull(f.UpdatedOn, f.CreatedOn) >= '1/1/2024') or*/ f.Isdeleted = 1) x 
union select distinct SiteCode = 'B27', 'RI - BHOLD' as [FormName], '24-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.MedicalStaffSignatureDate) is null then '1900-01-01' else convert(date, a.MedicalStaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from RIBHOLD a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'RI - Health Home Care Plan Review Form' as [FormName], '25-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from RIHealthHomeCareReview a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'RI - Health Home Consent to Receive' as [FormName], '26-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from RIHealthHomeConsentToReceive a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'RI - Health Home Eligibility and Follow up Checklist' as [FormName], '27-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from RIHealthHomeEligibilityFollUpChecklist a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'RI - Health Home History' as [FormName], '28-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from RIHealthHomeHistory a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'RI - Health Home Note' as [FormName], '29-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from RIHealthHomeNote a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'RI - Health Home Triage Assessment' as [FormName], '30-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from RIHealthHomeTriageAssessment a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'RI - Health Home Patient Centered Plan of Care' as [FormName], '31-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from RIHealthHomePatientCenteredPlan a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'RI - Overdose Prevention Education' as [FormName], '32-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from RIOverdosePreventionEducation a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'RI - PHQ-9 Form' as [FormName], '33-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from RIPHQ9 a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'GA - Patient Rights and Responsibilities' as [FormName], '34-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from PatientRightsandResponsibilities a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'GA - Order for Services' as [FormName], '35-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = case when convert(date, a.ProviderSignatureDate) is null then '1900-01-01' else convert(date, a.ProviderSignatureDate) end, RequestorSignatureDate = null, [StaffSignatureDate] = null, SupervisorSignatureSignatureDate = null  from OrderforServices a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'GA - Consent to Treatment with an Approved Narcotic' as [FormName], '36-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = case when convert(date, a.ProviderSignatureDate) is null then '1900-01-01' else convert(date, a.ProviderSignatureDate) end, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from GAConsenttoTreatmentwithanApprovedNarcotic a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'GA - Consent Central Registry Georgia' as [FormName], '37-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from GAConsentCentralRegistryGeorgia a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'GA - Transition and Discharge Plan' as [FormName], '38-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = case when convert(date, a.ProviderSignatureDate) is null then '1900-01-01' else convert(date, a.ProviderSignatureDate) end, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = case when convert(date, a.SupervisorSignatureDate) is null then '1900-01-01' else convert(date, a.SupervisorSignatureDate) end  from TransitionandDischargePlan a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'NC - Consent to Central Registry' as [FormName], '39-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from NCConsenttoCentralRegistry a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'NC - Initial Transition and Discharge Plan' as [FormName], '40-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from NCInitialTransitionDischargePlan a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'NC - Crisis Prevention and Intervention Plan' as [FormName], '41-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from CrisisPrevention a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'NC - Consent and Auth Disclosure of Sub Disorder' as [FormName], '42-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from NCConsentAuthDisclosureSubDisorder a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'NC - Person Centered Profile' as [FormName], '43-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = case when convert(date, a.ProviderSignatureDate) is null then '1900-01-01' else convert(date, a.ProviderSignatureDate) end, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = case when convert(date, a.SupervisorSignatureDate) is null then '1900-01-01' else convert(date, a.SupervisorSignatureDate) end  from NCPersonCenteredProfile a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'NC - PIE' as [FormName], '44-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from NCPIE a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', '90 Day Review' as [FormName], '45-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = case when convert(date, a.MedicalProviderSignatureDate) is null then '1900-01-01' else convert(date, a.MedicalProviderSignatureDate) end, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from NinetyDayReview a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'AR-State Fact form' as [FormName], '46-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.Createdon), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = case when convert(date, a.CompletedBySignatureDate) is null then '1900-01-01' else convert(date, a.CompletedBySignatureDate) end , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = null, SupervisorSignatureSignatureDate = null  from StateFactForm a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'MN - Consent to Treatment Via Telehealth' as [FormName], '23-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from ConsenttoTreatmentViaTelehealth a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'MN - DAANES Notification Form' as [FormName], '22-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from tblDAANESNotification a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'MN - Authorization for Release of Information to the MAARC' as [FormName], '21-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedDate), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from tblMAARC a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'Initial Services Plan and Vulnerable Adult Determination' as [FormName], '20-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from InitialServicesPlanandVAD a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'State Fact Form' as [FormName], '19-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = case when convert(date, a.CompletedBySignatureDate) is null then '1900-01-01' else convert(date, a.CompletedBySignatureDate) end , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.CompletedBySignatureDate) is null then '1900-01-01' else convert(date, a.CompletedBySignatureDate) end, SupervisorSignatureSignatureDate = null  from StateFactForm a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'MN - Mental Health Informed Consent' as [FormName], '18-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from MentalHealthInformedConsent a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'Insurance Benefit Verification' as [FormName], '17-' + convert(varchar, isnull(pa.PatientID, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(pa.PatientID, 0), [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = null, SupervisorSignatureSignatureDate = null  from InsuranceBenefitVerification a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'Patient Information sheet' as [FormName], '16-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = null, SupervisorSignatureSignatureDate = null  from PatientInformationsheet a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'Adverse Childhood Experiences' as [FormName], '15-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedDate), [UpdatedOn] = convert(date, a.ModifiedDate), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from AdverseChildhood a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'MN - Consent to Central Registry' as [FormName], '14-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from GeneralConsentAuthforReleaseInfo a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'CO - Consent Central Registry Colorado' as [FormName], '13-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from ConsentCentralRegistryColorado a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'KS Patient Rights and Responsibilities' as [FormName], '12-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from KSPatientRightsResponsibilities a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
union select distinct SiteCode = 'B27', 'BHG Notice Of Privacy Practices' as [FormName], '10-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = null, SupervisorSignatureSignatureDate = null  from tblBHGNoticeOfPrivacyPractices a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 

 where a.CreatedOn >= '1/1/2024' or isnull(a.ModifiedOn, a.CreatedOn) >= '1/1/2024'union select distinct SiteCode = 'B27', 'Suicide Severity Rating Scale' as [FormName], '1-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = case when convert(date, a.SupervisorSignatureDate) is null then '1900-01-01' else convert(date, a.SupervisorSignatureDate) end  from SuicideSeverityRatingScale a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 

 where a.CreatedOn >= '1/1/2024' or isnull(a.ModifiedOn, a.CreatedOn) >= '1/1/2024'union select distinct SiteCode = 'B27', 'Suicide Severity Rating Scale 2.0' as [FormName], '11-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = case when convert(date, a.SupervisorSignatureDate) is null then '1900-01-01' else convert(date, a.SupervisorSignatureDate) end  from SAFETProtocolwithCSSRS a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 

 where a.CreatedOn >= '1/1/2024' or isnull(a.ModifiedOn, a.CreatedOn) >= '1/1/2024'union select distinct SiteCode = 'B27', 'Health Questionnaire' as [FormName], '2-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.Createddate), [UpdatedOn] = convert(date, a.Modifieddate), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = case when convert(date, a.DoctorSignatureDate) is null then '1900-01-01' else convert(date, a.DoctorSignatureDate) end, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = case when convert(date, a.NurseSignatureDate) is null then '1900-01-01' else convert(date, a.NurseSignatureDate) end, RequestorSignatureDate = null, [StaffSignatureDate] = null, SupervisorSignatureSignatureDate = null  from HealthQuestionnaire a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 

 where a.Createddate >= '1/1/2024' or isnull(a.Modifieddate, a.Createddate) >= '1/1/2024'union select distinct SiteCode = 'B27', 'Infectious Disease And Behavioral Screen' as [FormName], '3-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = null, ProviderSignatureSignatureDate = case when convert(date, a.MedicalStaffSignatureDate) is null then '1900-01-01' else convert(date, a.MedicalStaffSignatureDate) end, RequestorSignatureDate = null, [StaffSignatureDate] = null, SupervisorSignatureSignatureDate = null  from InfectiousDiseaseAndBehavioralScreen a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 

 where a.CreatedOn >= '1/1/2024' or isnull(a.ModifiedOn, a.CreatedOn) >= '1/1/2024'union select distinct SiteCode = 'B27', 'Consent to Treatment with an Approved Narcotic' as [FormName], '4-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = case when convert(date, a.DoctorSignatureDate) is null then '1900-01-01' else convert(date, a.DoctorSignatureDate) end, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.PatientSignatureDate) is null then '1900-01-01' else convert(date, a.PatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.StaffSignatureDate) is null then '1900-01-01' else convert(date, a.StaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from ConsentToTreatmentWithAnApprovedNarcotic a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 

 where a.CreatedOn >= '1/1/2024' or isnull(a.ModifiedOn, a.CreatedOn) >= '1/1/2024'union select distinct SiteCode = 'B27', 'Financial Hardship Application' as [FormName], '5-' + convert(varchar, isnull(a.CltID, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.CltID, 0), [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.FHAPatientSignatureDate) is null then '1900-01-01' else convert(date, a.FHAPatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = null, SupervisorSignatureSignatureDate = null  from FinancialHardshipApplication a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 

 where a.CreatedOn >= '1/1/2024' or isnull(a.ModifiedOn, a.CreatedOn) >= '1/1/2024'union select distinct SiteCode = 'B27', 'Comprehensive Assessment Form' as [FormName], '6-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, a.CAPatientSignatureDate) is null then '1900-01-01' else convert(date, a.CAPatientSignatureDate) end, ProviderSignatureSignatureDate = null, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, a.CAStaffSignatureDate) is null then '1900-01-01' else convert(date, a.CAStaffSignatureDate) end, SupervisorSignatureSignatureDate = null  from ComprehensiveAssessmentForm a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 

 where a.CreatedOn >= '1/1/2024' or isnull(a.ModifiedOn, a.CreatedOn) >= '1/1/2024'union select distinct SiteCode = 'B27', 'Admission Assessment' as [FormName], '7-' + convert(varchar, isnull(a.ClientId, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID], ClientId = isnull(a.ClientId, 0) , [CreatedOn] = convert(date, a.CreatedOn), [UpdatedOn] = convert(date, a.ModifiedOn), IsDeleted = case when isnull(a.IsDeleted,0) = 0 and pa.IsDeleted <> 1 and isnull(pa.DataFormId,0) >= 0 and isnull(d.IsDeleted,0) = 0 then 0 else 1 end, CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date,aas.AdmissionAssessmentPatientSignatureDate) is null then '1900-01-01' else convert(date,aas.AdmissionAssessmentPatientSignatureDate) end , ProviderSignatureSignatureDate = case when convert(date, aas.AdmissionAssessmentProviderSignatureDate) is null then '1900-01-01' else convert(date, aas.AdmissionAssessmentProviderSignatureDate) end, RequestorSignatureDate = null, [StaffSignatureDate] = case when convert(date, aas.AdmissionAssessmentStaffSignatureDate) is null then '1900-01-01' else convert(date, aas.AdmissionAssessmentStaffSignatureDate) end, SupervisorSignatureSignatureDate = case when convert(date, aas.AdmissionAssessmentSupervisorSignatureDate) is null then '1900-01-01' else convert(date, aas.AdmissionAssessmentSupervisorSignatureDate) end  from AdmissionAssessment a inner join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 left join dbo.SF_DataForms d on (pa.DataFormId = d.Id) 
 inner join[dbo].[AdmissionAssessmentSummary] aas on(a.Id = aas.AdmissionAssessmentId and a.PreAdmissionId = aas.PreAdmissionId) 

 where a.CreatedOn >= '1/1/2024' or isnull(a.ModifiedOn, a.CreatedOn) >= '1/1/2024' union select distinct SiteCode, FormName, FormID, ClientId, CreatedOn, UpdatedOn, IsDeleted , CompletedBySignatureSignatureDate, CounselorSignatureSignatureDate, DoctorSignatureSignatureDate, MedicalProviderSignatureSignatureDate , PatientSignatureDate, ProviderSignatureSignatureDate, RequestorSignatureDate, StaffSignatureDate, SupervisorSignatureSignatureDate from (Select SiteCode = 'B27', 'Treatment Plan' as [FormName] , '8-1-' + convert(varchar, ABS(tprCLTID)) + '-' + convert(varchar, tpRID) + '-' + convert(varchar, tprTPID) as [FormID], null PreAdmissionId, tprCLTID ClientId, 1 as QuestionID, 1 as QuestionOrderID, 'Treatment Plan Type' as QuestionText, null as [OptionID], TprTYPE as AnswerValue, tprCreatedby Createdby, convert(date, tprDT) as [CreatedOn], null as [UpdatedBy], null as [UpdatedOn], Isdeleted = Case when tprCLTID < 0 then 1 else 0 end, CompletedBySignatureSignatureDate = null, CounselorSignatureSignatureDate = null, DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null, PatientSignatureDate = case when convert(date, tprCLIRNTSIGDate) is null then '1900-01-01' else convert(date, tprCLIRNTSIGDate) end, ProviderSignatureSignatureDate = case when convert(date, tprDRSIGDate) is null then '1900-01-01' else convert(date, tprDRSIGDate) end, RequestorSignatureDate = null, StaffSignatureDate = case when(convert(date, tprCOUNSSIGDate) is null and convert(date, tprSUPERSIGDate) is null) then '1900-01-01' else convert(date, tprCOUNSSIGDate) end , SupervisorSignatureSignatureDate = convert(date, tprSUPERSIGDate) from [dbo].tblTP17REVIEW) tp
 Where (CreatedOn >= '1/1/2024' or isnull(UpdatedOn, CreatedOn) >= '1/1/2024') 
 union Select SiteCode = 'B27', 'Level Justification' as [FormName], [FormID] = '9-1-' + convert(varchar, ABS(cltID)) + '-' + convert(varchar, ReqNum) + '-1', ClientId = cltID /*, Createdby = Staff*/, [CreatedOn] = convert(date, DateAdded) /*, [UpdatedBy] = StatusUser*/, [UpdatedOn] = convert(date, statusDate) , Isdeleted = Case when cltID < 0 then 1 else 0 end , CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null , MedicalProviderSignatureSignatureDate = null , PatientSignatureDate = null , ProviderSignatureSignatureDate = case when (ISNull(convert(date, DrSigDt), convert(date, SigNurseDt)) is null and Status = 'Approved') then '1900-01-01' else ISNull(convert(date, DrSigDt), convert(date, SigNurseDt)) end, RequestorSignatureDate = null, StaffSignatureDate = null, SupervisorSignatureSignatureDate = case when convert(date, sigCoordinatorDt) is null and Status = 'Approved' then '1900-01-01' else convert(date, sigCoordinatorDt) end from [dbo].[tblORDERREQ] where status = 'Approved' and (Notes not like 'Test %' and Notes <> 'TEST' and DrNote <>'HEllo test' and DrNote <> 'TEST') 
and (DateAdded >= '1/1/2024' or isnull(statusDate, DateAdded) >= '1/1/2024') 

Select 'B26' SiteCode, [tpcID] tpcID, [tpccltID] tpccltID, [tpcStrStatus] tpcStrStatus, [tpcStrPayer] tpcStrPayer, [tpcDtmAdded] tpcDtmAdded
, [tpcStrAdded] tpcStrAdded, [f10oth] f10oth, [tpcClaimBatchID] tpcClaimBatchID, [f11insnumber] f11insnumber, [f11insplan] f11insplan
, [f11inssex] f11inssex, [f12sig] f12sig, [f12sigdate] f12sigdate, [f13inssig] f13inssig, [f14date] f14date, [f15firstdate] f15firstdate
, [f16dateunableend] f16dateunableend, [f10auto] f10auto, [tpcStrPrimary] tpcStrPrimary, [f10employ] f10employ, [f10local] f10local
, [f11insanother] f11insanother, [f11insdob] f11insdob, [f11insemploy] f11insemploy, [f16dateunablestart] f16dateunablestart
, [f17refername] f17refername, [f17refernpi] f17refernpi, [f18datehospend] f18datehospend, [f18datehospstart] f18datehospstart
, [f19local] f19local, [f1id] f1id, [f20outsidelab] f20outsidelab, [f21diag1] f21diag1, [f21diag2] f21diag2, [f21diag3] f21diag3
, [f21diag4] f21diag4, [f22medresub] f22medresub, [f23priorauth] f23priorauth, [f25taxid] f25taxid, [f26account] f26account
, [f27assign] f27assign, [f28totalcharge] f28totalcharge, [f29amtpaid] f29amtpaid, [f2name] f2name, [f30balancedue] f30balancedue
, [f31date] f31date, [f31phys] f31phys, [f32a] f32a, [f32b] f32b, [f32line1] f32line1, [f32line2] f32line2, [f32line3] f32line3
, [f32line4] f32line4, [f33a] f33a, [f33b] f33b, [f33line1] f33line1, [f33line2] f33line2, [f33line3] f33line3, [f33line4] f33line4
, [f33phone] f33phone, [f3dob] f3dob, [f4insname] f4insname, [f5add] f5add, [f5city] f5city, [f5phone] f5phone, [f5state] f5state, [f5zip] f5zip
, [f6insrel] f6insrel, [f7insadd] f7insadd, [f7inscity] f7inscity, [f7insphone] f7insphone, [f7insstate] f7insstate, [f7inszip] f7inszip
, [f8stat] f8stat, [f9othinsdob] f9othinsdob, [f9othinsemp] f9othinsemp, [f9othinsname] f9othinsname, [f9othinsnumber] f9othinsnumber
, [f9othinsplan] f9othinsplan, [f9othinssex] f9othinssex, [tpcCreatedDate] tpcCreatedDate, [tpcEncounter] tpcEncounter
, [tpcREBILLREASON] tpcREBILLREASON, [tpcStrWeek] tpcStrWeek, [tpcWKSTART] tpcWKSTART, [tpcPayerCIN] tpcPayerCIN, [tpcSrvType] tpcSrvType
, [f3sex] f3sex, [tpcClaimType] tpcClaimType, [SiteID] SiteID, [tpcDBnotes] tpcDBnotes, [tpcReferring] tpcReferring
, CHECKSUM([tpcID], [tpccltID], [tpcStrStatus], [tpcStrPayer], [tpcDtmAdded], [tpcStrAdded], [f10oth], [tpcClaimBatchID], [f11insnumber]
, [f11insplan], [f11inssex], [f12sig], [f12sigdate], [f13inssig], [f14date], [f15firstdate], [f16dateunableend], [f10auto], [tpcStrPrimary]
, [f10employ], [f10local], [f11insanother], [f11insdob], [f11insemploy], [f16dateunablestart], [f17refername], [f17refernpi], [f18datehospend]
, [f18datehospstart], [f19local], [f1id], [f20outsidelab], [f21diag1], [f21diag2], [f21diag3], [f21diag4], [f22medresub], [f23priorauth]
, [f25taxid], [f26account], [f27assign], [f28totalcharge], [f29amtpaid], [f2name], [f30balancedue], [f31date], [f31phys], [f32a], [f32b]
, [f32line1], [f32line2], [f32line3], [f32line4], [f33a], [f33b], [f33line1], [f33line2], [f33line3], [f33line4], [f33phone], [f3dob]
, [f4insname], [f5add], [f5city], [f5phone], [f5state], [f5zip], [f6insrel], [f7insadd], [f7inscity], [f7insphone], [f7insstate], [f7inszip]
, [f8stat], [f9othinsdob], [f9othinsemp], [f9othinsname], [f9othinsnumber], [f9othinsplan], [f9othinssex], [tpcCreatedDate], [tpcEncounter]
, [tpcREBILLREASON], [tpcStrWeek], [tpcWKSTART], [tpcPayerCIN], [tpcSrvType], [f3sex], [tpcClaimType], [SiteID], [tpcDBnotes], [tpcReferring])
RowChkSum  
from dbo.tbl3pClaim
