
/*
select SiteCode, FormName, FormID, PreadmissionId, ClientId, QuestionID 
, QuestionOrderID = Row_Number() over(Partition by v.FormName, v.FormId, v.ClientId, v.QuestionId order by v.QuestionId)
, QuestionText, OptionID, AnswerValue, Createdby, CreatedOn, UpdatedBy, UpdatedOn, IsDeleted from (
Select SiteCode = '" + st.SiteCode.ToString() + "', 'Adverse Childhood Experiences' as [FormName] 
, '15-' + convert(varchar, 0) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID] 
, PreAdmissionId, ClientId = 0, 0 as QuestionID, 1 as QuestionOrderID, null as QuestionText, null as [OptionID], null as AnswerValue 
, Createdby, convert(date, CreatedOn) as [CreatedOn], ModifiedBy as [UpdatedBy], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted 
  from [dbo].MentalHealthInformedConsent) v


select * from [dbo].MentalHealthInformedConsent
*/
select distinct SiteCode, FormName, convert(varchar(100),FormId) FormId, ClientId, CreatedOn, UpdatedOn, Isdeleted 
, CompletedBySignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'CompletedBySignatureSignatureDate' order by [DateTime] desc) 
, CounselorSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and 
 (DateField = 'CounselorSignatureSignatureDate' or DateField = 'CounselorSignatureDate') order by [DateTime] desc) 
, DoctorSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'DoctorSignatureSignatureDate' order by [DateTime] desc) 
, MedicalProviderSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'MedicalProviderSignatureSignatureDate' order by [DateTime] desc) 
, PatientSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'PatientSignatureDate' order by [DateTime] desc) 
, ProviderSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'ProviderSignatureSignatureDate' order by [DateTime] desc) 
, RequestorSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'RequestorSignatureDate' order by [DateTime] desc) 
, StaffSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'StaffSignatureDate' order by [DateTime] desc) 
, SupervisorSignatureSignatureDate = (select top 1 case when Sign is null then '1/1/1900' else [DateTime] end from AnswerSignature where FormId = x.FormId and DateField = 'SupervisorSignatureSignatureDate' order by [DateTime] desc) 
 from (select SiteCode = 'D08', ft.FormName, f.id as FormId, f.ClientId, f.CreatedOn, f.UpdatedOn, IsDeleted  from dbo.Form f left join FormTemplate ft 
 on (f.FormTemplateId = ft.Id) where (f.CreatedOn >= '6/17/2023' or isnull(f.UpdatedOn, f.CreatedOn) >= '6/17/2023') union select SiteCode = 'D08', ft.FormName, f.id as FormId, f.ClientId, f.CreatedOn, f.UpdatedOn, Isdeleted from dbo.Form f left join FormTemplate ft on(f.FormTemplateId = ft.Id) 
 where (f.CreatedOn >= '6/17/2023' or isnull(f.UpdatedOn, f.CreatedOn) >= '6/17/2023') or Isdeleted = 1) x 
 union select distinct SiteCode = 'D08', 'Suicide Severity Rating Scale' as [FormName]     , '1-' + convert(varchar, ClientId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]      , ClientId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted      , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null      , MedicalProviderSignatureSignatureDate = convert(date, MedicalProviderSignatureDate)      , PatientSignatureDate = null     , ProviderSignatureSignatureDate = null     , RequestorSignatureDate = null     , [StaffSignatureDate] = case when convert(date, StaffSignatureDate) is null then '1900-01-01' else convert(date, StaffSignatureDate) end      , SupervisorSignatureSignatureDate = case when convert(date, SupervisorSignatureDate) is null then '1900-01-01' else convert(date, SupervisorSignatureDate) end   from [dbo].[SuicideSeverityRatingScale]  
 union select distinct SiteCode = 'D08', 'Suicide Severity Rating Scale 2.0' as [FormName]     , '11-' + convert(varchar, ClientId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]      , ClientId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted      , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null      , MedicalProviderSignatureSignatureDate = null      , PatientSignatureDate = null     , ProviderSignatureSignatureDate = null     , RequestorSignatureDate = null     , [StaffSignatureDate] = case when convert(date, StaffSignatureDate) is null then '1900-01-01' else convert(date, StaffSignatureDate) end      , SupervisorSignatureSignatureDate = case when convert(date, SupervisorSignatureDate) is null then '1900-01-01' else convert(date, SupervisorSignatureDate) end   from [dbo].[SAFETProtocolwithCSSRS]  
 union select distinct SiteCode = 'D08', 'Health Questionnaire' as [FormName]      , '2-' + convert(varchar, ClientId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]       , ClientId, convert(date, Createddate), convert(date, Modifieddate), Isdeleted       , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null       , DoctorSignatureSignatureDate = case when convert(date, DoctorSignatureDate) is null then '1900-01-01' else convert(date, DoctorSignatureDate) end       , MedicalProviderSignatureSignatureDate = null       , PatientSignatureDate = null       , ProviderSignatureSignatureDate = case when convert(date, NurseSignatureDate) is null then '1900-01-01' else convert(date, NurseSignatureDate) end       , RequestorSignatureDate = null       , StaffSignatureDate = null       , SupervisorSignatureSignatureDate = null   from [dbo].[HealthQuestionnaire]  
 union select distinct SiteCode = 'D08', 'Infectious Disease And Behavioral Screen' as [FormName]      , '3-' + convert(varchar, ClientId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]       , ClientId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted       , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null       , MedicalProviderSignatureSignatureDate = null       , PatientSignatureDate = null       , ProviderSignatureSignatureDate = case when convert(date, MedicalStaffSignatureDate) is null then '1900-01-01' else convert(date, MedicalStaffSignatureDate) end       , RequestorSignatureDate = null      , StaffSignatureDate = null       , SupervisorSignatureSignatureDate = null  from [dbo].[InfectiousDiseaseAndBehavioralScreen]  
 union select distinct SiteCode = 'D08', 'Consent to Treatment with an Approved Narcotic' as [FormName]      , '4-' + convert(varchar, ClientId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]       , ClientId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted       , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = case when convert(date,DoctorSignatureDate) is null then '1900-01-01' else convert(date,DoctorSignatureDate) end       , MedicalProviderSignatureSignatureDate = null       , PatientSignatureDate = case when convert(date,PatientSignatureDate) is null then '1900-01-01' else convert(date,PatientSignatureDate) end        , ProviderSignatureSignatureDate = null       , RequestorSignatureDate = null      , StaffSignatureDate = case when convert(date,StaffSignatureDate) is null then '1900-01-01' else convert(date,StaffSignatureDate) end       , SupervisorSignatureSignatureDate = null  from [dbo].[ConsentToTreatmentWithAnApprovedNarcotic]  
 union select distinct SiteCode = 'D08', 'Financial Hardship Application' as [FormName]      , '5-' + convert(varchar, CltId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]       , CltId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted       , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null       , MedicalProviderSignatureSignatureDate = null       , PatientSignatureDate = case when convert(date,FHAPatientSignatureDate) is null then '1900-01-01' else convert(date,FHAPatientSignatureDate) end       , ProviderSignatureSignatureDate = null       , RequestorSignatureDate = null      , StaffSignatureDate = null       , SupervisorSignatureSignatureDate = null  from [dbo].[FinancialHardshipApplication]  
 union select distinct SiteCode = 'D08', 'Comprehensive Assessment Form' as [FormName]      , '6-' + convert(varchar, ClientId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]       , ClientId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted       , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null       , MedicalProviderSignatureSignatureDate = null       , PatientSignatureDate = case when convert(date,CAPatientSignatureDate) is null then '1900-01-01' else convert(date,CAPatientSignatureDate) end       , ProviderSignatureSignatureDate = case when convert(date,CAProviderSignatureDate) is null then '1900-01-01' else convert(date,CAProviderSignatureDate) end       , RequestorSignatureDate = null      , StaffSignatureDate = case when convert(date,CAStaffSignatureDate) is null then '1900-01-01' else convert(date,CAStaffSignatureDate) end       , SupervisorSignatureSignatureDate = case when convert(date,CASupervisorSignatureDate) is null then '1900-01-01' else convert(date,CASupervisorSignatureDate) end  from [dbo].[ComprehensiveAssessmentForm]  
 union select distinct SiteCode = 'D08', 'Admission Assessment' as [FormName]      , '7-' + convert(varchar, aa.ClientId) + '-' + convert(varchar, aa.PreAdmissionId) + '-' + convert(varchar, aa.id) as [FormID]       , aa.ClientId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted       , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null       , MedicalProviderSignatureSignatureDate = null       , PatientSignatureDate = case when convert(date,AdmissionAssessmentPatientSignatureDate) is null then '1900-01-01' else convert(date,AdmissionAssessmentPatientSignatureDate) end       , ProviderSignatureSignatureDate = case when convert(date,AdmissionAssessmentProviderSignatureDate) is null then '1900-01-01' else convert(date,AdmissionAssessmentProviderSignatureDate) end       , RequestorSignatureDate = null      , StaffSignatureDate = case when convert(date,AdmissionAssessmentStaffSignatureDate) is null then '1900-01-01' else convert(date,AdmissionAssessmentStaffSignatureDate) end       , SupervisorSignatureSignatureDate = case when convert(date,AdmissionAssessmentSupervisorSignatureDate) is null then '1900-01-01' else convert(date,AdmissionAssessmentSupervisorSignatureDate) end  from [dbo].[AdmissionAssessment] aa inner join [dbo].[AdmissionAssessmentSummary] aas on aa.Id = aas.AdmissionAssessmentId and aa.PreAdmissionId = aas.PreAdmissionId  
 union select distinct SiteCode, FormName, FormID, ClientId, CreatedOn, UpdatedOn, IsDeleted , CompletedBySignatureSignatureDate, CounselorSignatureSignatureDate, DoctorSignatureSignatureDate, MedicalProviderSignatureSignatureDate , PatientSignatureDate, ProviderSignatureSignatureDate, RequestorSignatureDate, StaffSignatureDate, SupervisorSignatureSignatureDate from(  Select SiteCode = 'D08', 'Treatment Plan' as [FormName] , '8-1-' + convert(varchar, ABS(tprCLTID)) + '-' + convert(varchar, tpRID) + '-' + convert(varchar, tprTPID) as [FormID] , null PreAdmissionId, tprCLTID ClientId, 1 as QuestionID, 1 as QuestionOrderID, 'Treatment Plan Type' as QuestionText, null as [OptionID], TprTYPE as AnswerValue , tprCreatedby Createdby, convert(date, tprDT) as [CreatedOn], null as [UpdatedBy], null as [UpdatedOn], Isdeleted = Case when tprCLTID< 0 then 1 else 0 end , CompletedBySignatureSignatureDate = null, CounselorSignatureSignatureDate = null, DoctorSignatureSignatureDate = null, MedicalProviderSignatureSignatureDate = null , PatientSignatureDate = case when convert(date, tprCLIRNTSIGDate) is null then '1900-01-01' else convert(date, tprCLIRNTSIGDate) end , ProviderSignatureSignatureDate = case when convert(date, tprDRSIGDate) is null then '1900-01-01' else convert(date, tprDRSIGDate) end , RequestorSignatureDate = null , StaffSignatureDate = case when(convert(date, tprCOUNSSIGDate) is null and convert(date, tprSUPERSIGDate) is null) then '1900-01-01' else convert(date, tprCOUNSSIGDate) end , SupervisorSignatureSignatureDate = convert(date, tprSUPERSIGDate) from [dbo].tblTP17REVIEW ) tp 
 union Select SiteCode = 'D08', 'Level Justification' as [FormName] , [FormID] = '9-1-' + convert(varchar, ABS(cltID)) + '-' + convert(varchar, ReqNum) + '-1' /*+ convert(varchar, tprTPID)*/ , ClientId = cltID /*, Createdby = Staff*/, [CreatedOn] = convert(date, DateAdded) /*, [UpdatedBy] = StatusUser*/, [UpdatedOn] = convert(date, statusDate) , Isdeleted = Case when cltID < 0 then 1 else 0 end , CompletedBySignatureSignatureDate = null , CounselorSignatureSignatureDate = null , DoctorSignatureSignatureDate = null , MedicalProviderSignatureSignatureDate = null , PatientSignatureDate = null , ProviderSignatureSignatureDate = case when (ISNull(convert(date, DrSigDt), convert(date, SigNurseDt)) is null and Status = 'Approved') then '1900-01-01' else ISNull(convert(date, DrSigDt), convert(date, SigNurseDt)) end , RequestorSignatureDate = null , StaffSignatureDate = null , SupervisorSignatureSignatureDate = case when convert(date, sigCoordinatorDt) is null and Status = 'Approved' then '1900-01-01' else convert(date, sigCoordinatorDt) end  from [dbo].[tblORDERREQ] where status = 'Approved' and (Notes not like 'Test %' and Notes <> 'TEST' and DrNote <>'HEllo test' and DrNote <> 'TEST')  
 union select distinct SiteCode = 'D08', 'BHG Notice Of Privacy Practices' as [FormName]      , '10-' + convert(varchar, aa.ClientId) + '-' + convert(varchar, aa.PreAdmissionId) + '-' + convert(varchar, aa.id) as [FormID]       , aa.ClientId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted       , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null       , MedicalProviderSignatureSignatureDate = null       , PatientSignatureDate = case when convert(date,PatientSignatureDate) is null then '1900-01-01' else convert(date,PatientSignatureDate) end       , ProviderSignatureSignatureDate = null       , RequestorSignatureDate = null      , StaffSignatureDate = null       , SupervisorSignatureSignatureDate = null  from [dbo].[tblBHGNoticeOfPrivacyPractices] aa  
 union select distinct SiteCode = 'D08', 'KS Patient Rights and Responsibilities' as [FormName]     , '12-' + convert(varchar, ClientId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]      , ClientId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted      , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null      , MedicalProviderSignatureSignatureDate = null      , PatientSignatureDate = case when convert(date,PatientSignatureDate) is null then '1900-01-01' else convert(date,PatientSignatureDate) end      , ProviderSignatureSignatureDate = null     , RequestorSignatureDate = null     , [StaffSignatureDate] = case when convert(date, StaffSignatureDate) is null then '1900-01-01' else convert(date, StaffSignatureDate) end      , SupervisorSignatureSignatureDate = null   from [dbo].[KSPatientRightsResponsibilities]  
 union select distinct SiteCode = 'D08', 'CO - Consent Central Registry Colorado' as [FormName]     , '13-' + convert(varchar, ClientId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]      , ClientId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted      , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null      , MedicalProviderSignatureSignatureDate = null      , PatientSignatureDate = case when convert(date,PatientSignatureDate) is null then '1900-01-01' else convert(date,PatientSignatureDate) end      , ProviderSignatureSignatureDate = null     , RequestorSignatureDate = null     , [StaffSignatureDate] = case when convert(date, StaffSignatureDate) is null then '1900-01-01' else convert(date, StaffSignatureDate) end      , SupervisorSignatureSignatureDate = null   from [dbo].[ConsentCentralRegistryColorado]  
 union select distinct SiteCode = 'D08', 'MN - Consent to Central Registry' as [FormName]     , '14-' + convert(varchar, ClientId) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]      , ClientId, convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted      , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null      , MedicalProviderSignatureSignatureDate = null      , PatientSignatureDate = case when convert(date,PatientSignatureDate) is null then '1900-01-01' else convert(date,PatientSignatureDate) end      , ProviderSignatureSignatureDate = null     , RequestorSignatureDate = null     , [StaffSignatureDate] = case when convert(date, StaffSignatureDate) is null then '1900-01-01' else convert(date, StaffSignatureDate) end      , SupervisorSignatureSignatureDate = null   from [dbo].[GeneralConsentAuthforReleaseInfo]  
 union select distinct SiteCode = 'D08', 'Adverse Childhood Experiences' as [FormName]     , '15-' + convert(varchar, isnull(pa.PatientID, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID]      , ClientId = isnull(pa.PatientID, 0), convert(date, a.CreatedDate) as [CreatedOn], convert(date, a.ModifiedDate) as [UpdatedOn], a.Isdeleted      , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null      , MedicalProviderSignatureSignatureDate = null      , PatientSignatureDate = null      , ProviderSignatureSignatureDate = null     , RequestorSignatureDate = null     , [StaffSignatureDate] = null      , SupervisorSignatureSignatureDate = null   from [dbo].[AdverseChildhood] a left join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 union select distinct SiteCode = 'D08', 'Patient Information sheet' as [FormName]     , '16-' + convert(varchar, isnull(Clientid, 0)) + '-' + convert(varchar, PreAdmissionId) + '-' + convert(varchar, id) as [FormID]      , ClientId = isnull(ClientID, 0), convert(date, CreatedOn) as [CreatedOn], convert(date, ModifiedOn) as [UpdatedOn], Isdeleted      , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null      , MedicalProviderSignatureSignatureDate = null      , PatientSignatureDate = null      , ProviderSignatureSignatureDate = null     , RequestorSignatureDate = null     , [StaffSignatureDate] = null      , SupervisorSignatureSignatureDate = null   from [dbo].[PatientInformationsheet]  
 union select distinct SiteCode = 'D08', 'Insurance Benefit Verification' as [FormName]     , '17-' + convert(varchar, isnull(pa.PatientID, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID]      , ClientId = isnull(pa.PatientID, 0), convert(date, a.CreatedOn) as [CreatedOn], convert(date, a.ModifiedOn) as [UpdatedOn], a.Isdeleted      , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null      , MedicalProviderSignatureSignatureDate = null      , PatientSignatureDate = null      , ProviderSignatureSignatureDate = null     , RequestorSignatureDate = null     , [StaffSignatureDate] = null      , SupervisorSignatureSignatureDate = null   from [dbo].[InsuranceBenefitVerification] a left join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 
 union select distinct SiteCode = 'D08', 'MN - Mental Health Informed Consent' as [FormName]     , '18-' + convert(varchar, isnull(pa.PatientID, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID]      , ClientId = isnull(pa.PatientID, 0), convert(date, a.CreatedOn) as [CreatedOn], convert(date, a.ModifiedOn) as [UpdatedOn], a.Isdeleted      , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null      , MedicalProviderSignatureSignatureDate = null      , PatientSignatureDate = case when convert(date, PatientSignatureDate) is null then '1900-01-01' else convert(date, PatientSignatureDate) end       , ProviderSignatureSignatureDate = null     
 , RequestorSignatureDate = null     
 , [StaffSignatureDate] = case when convert(date, StaffSignatureDate) is null then '1900-01-01' else convert(date, StaffSignatureDate) end      
 , SupervisorSignatureSignatureDate = null   
 select a.* from [dbo].MentalHealthInformedConsent a left join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID


 select distinct SiteCode = 'D08', 'Adverse Childhood Experiences' as [FormName]     
      , '15-' + convert(varchar, isnull(pa.PatientID, 0)) + '-' + convert(varchar, a.PreAdmissionId) + '-' + convert(varchar, a.id) as [FormID]      
      , ClientId = isnull(pa.PatientID, 0), convert(date, a.CreatedDate) as [CreatedOn], convert(date, a.ModifiedDate) as [UpdatedOn], a.Isdeleted      
      , CompletedBySignatureSignatureDate = null      , CounselorSignatureSignatureDate = null      , DoctorSignatureSignatureDate = null      
      , MedicalProviderSignatureSignatureDate = null      , PatientSignatureDate = null      , ProviderSignatureSignatureDate = null     
      , RequestorSignatureDate = null     , [StaffSignatureDate] = null      
      , SupervisorSignatureSignatureDate = null   
 select a.* from [dbo].[AdverseChildhood] a left join [dbo].[SF_PatientPreAdmission] pa on a.PreAdmissionId = pa.ID 