// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class Tbl3pClaimNote
    {
        public string SiteCode { get; set; }
        public int Tpcn { get; set; }
        public int? TpcnTpcid { get; set; }
        public DateTime? TpcnDtmAdded { get; set; }
        public string TpcnStrAdded { get; set; }
        public string TpcnStrNote { get; set; }
        public string TpcnStrType { get; set; }
        public DateTime? TpcnDtTickler { get; set; }
        public string TpcnDtTicklerRemoved { get; set; }
        public string TpcnStrTicklerRemovedNote { get; set; }
        public string TpcnStrTicklerRemovedUser { get; set; }
        public string TpcnStrTicklerType { get; set; }
        public long? GlobalBatchId { get; set; }
        public int? RowChkSum { get; set; }
        public DateTime? LastModAt { get; set; }
        public bool? RowState { get; set; }
    }
}