// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class Tbl3pArnote
    {
        public string SiteCode { get; set; }
        public int? RowChkSum { get; set; }
        public DateTime? LastModAt { get; set; }
        public bool? RowState { get; set; }
        public int ArnId { get; set; }
        public int? ArnLiid { get; set; }
        public string ArnNote { get; set; }
        public string ArnUser { get; set; }
        public DateTime? ArnDate { get; set; }
        public DateTime? ArnDtRemoved { get; set; }
        public string ArnStrRemovedReason { get; set; }
        public string ArnStrRemovedUser { get; set; }
        public int? Bid { get; set; }
        public string ArnDbnotes { get; set; }
        public long? GlobalBatchId { get; set; }
    }
}