// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblAppointments
    {
        public string SiteCode { get; set; }
        public int UniqueId { get; set; }
        public DateTime LastModAt { get; set; }
        public int RowChkSum { get; set; }
        public int? Type { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool? AllDay { get; set; }
        public string Subject { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public int? Label { get; set; }
        public int? ResourceId { get; set; }
        public string ResourceIds { get; set; }
        public string ReminderInfo { get; set; }
        public string RecurrenceInfo { get; set; }
        public int? PercentComplete { get; set; }
        public int? GroupName { get; set; }
        public string CustomField1 { get; set; }
        public bool? Attendees { get; set; }
        public string Service { get; set; }
        public string ServiceModifier { get; set; }
        public string TxtNote { get; set; }
        public string Area { get; set; }
        public bool? IntakeAppointmentMissed { get; set; }
        public string SalesForceId { get; set; }
        public int? IsSalesForceSync { get; set; }
        public int? IsThirdPartySync { get; set; }
        public string AppointmentType { get; set; }
        public bool? IsDropIn { get; set; }
        public bool? IsSchedule { get; set; }
        public int? NoofParticipants { get; set; }
        public int? GroupTimeAllowed { get; set; }
        public int? GracePeriod { get; set; }
    }
}