// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblAdmissionAssessmentDimensionOneDisorder
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int? AdmissionAssessmentId { get; set; }
        public int? OpioidDisorderPresent { get; set; }
        public int? AlcoholDisorderPresent { get; set; }
        public int? SedativeDisorderPresent { get; set; }
        public int? StimulantDisorderPresent { get; set; }
        public int? CannabisDisorderPresent { get; set; }
        public int? HallucinogenDisorderPresent { get; set; }
        public int? InhalantDisorderPresent { get; set; }
        public int? PhencyclidineDisorderPresent { get; set; }
        public string Comments { get; set; }
        public int? MedicallyAssistedWithdrawal { get; set; }
        public int? MedicallyAssistedWithdrawalHowManyTimes { get; set; }
        public int? MedicallyAssistedWithdrawalRecentTimes { get; set; }
        public int? InpatientRehabilitation { get; set; }
        public int? InpatientRehabilitationHowManyTimes { get; set; }
        public int? InpatientRehabilitationSuccessfullyComplete { get; set; }
        public int? InpatientRehabilitationRecentTimes { get; set; }
        public int? IntensiveOutpatientTreatments { get; set; }
        public int? IntensiveOutpatientHowManyTimes { get; set; }
        public int? IntensiveOutpatientSuccessfullyComplete { get; set; }
        public int? IntensiveOutpatientRecentTimes { get; set; }
        public int? OutpatientTreatment { get; set; }
        public int? OutpatientTreatmentHowManyTimes { get; set; }
        public int? OutpatientTreatmentSuccessfullyComplete { get; set; }
        public int? OutpatientTreatmentRecentTimes { get; set; }
        public int? PreviousMat { get; set; }
        public bool? PreviousMatmethadone { get; set; }
        public bool? PreviousMatbuprenorphine { get; set; }
        public bool? PreviousMatnaltrexone { get; set; }
        public string PreviousMatwhatWasYourDose { get; set; }
        public int? PreviousMatwasItHelpful { get; set; }
        public int? HowLongDidYouTakeIt { get; set; }
        public int? DdlhowLongDidYouTakeIt { get; set; }
        public int? LongestPeriodOfSobriety { get; set; }
        public int? DdllongestPeriodOfSobrietyFromAllSubstances { get; set; }
        public string SubstanceUseHistoryComments { get; set; }
        public int? DdldimensionOneScore { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? HowDoYouProcureTheDrug { get; set; }
        public bool? BuyOnTheStreet { get; set; }
        public bool? FreeFromFamily { get; set; }
        public bool? PrescriptionFromHealthcareProvider { get; set; }
        public bool? SellingUseOwnSupply { get; set; }
        public bool? Theft { get; set; }
        public int? DdlmedicallyAssistedWithdrawal { get; set; }
        public int? DdlinpatientRehabilitation { get; set; }
        public int? DdlintensiveOutpatient { get; set; }
        public int? DdloutpatientTreatment { get; set; }
        public bool? ChkMedicallyAssistedWithdrawal { get; set; }
        public bool? ChkInpatientRehabilitation { get; set; }
        public bool? ChkIntensiveOutpatientTreatments { get; set; }
        public bool? ChkOutpatientTreatment { get; set; }
        public bool? ChkPreviousMat { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}