// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblAdmissionAssessment
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? DataFormId { get; set; }
        public int? ClientId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsDeleted { get; set; }
        public string Version { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}