// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblAdmissionAssessmentDimensionTwo
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int? AdmissionAssessmentId { get; set; }
        public bool? HighBloodPressure { get; set; }
        public bool? Diabetes { get; set; }
        public bool? HeartDisease { get; set; }
        public bool? EpilepsySeizures { get; set; }
        public bool? Asthma { get; set; }
        public bool? HepatitisA { get; set; }
        public bool? HepatitisB { get; set; }
        public bool? HepatitisC { get; set; }
        public bool? Hiv { get; set; }
        public bool? LiverDisease { get; set; }
        public bool? Cancer { get; set; }
        public bool? Tuberculosis { get; set; }
        public bool? RenalKidneyDisease { get; set; }
        public bool? ChronicPain { get; set; }
        public bool? Blindness { get; set; }
        public bool? PoorVision { get; set; }
        public bool? Deafness { get; set; }
        public bool? HearingLoss { get; set; }
        public string DiagnosedComment2 { get; set; }
        public int? DoYouUseTobacco { get; set; }
        public int? DoYouHaveAnyConcerns { get; set; }
        public string Comments2 { get; set; }
        public int? DdldimensionTwoScore { get; set; }
        public int? PreAdmissionId { get; set; }
        public string Allergies { get; set; }
        public int? PrimaryCarePractitioner { get; set; }
        public string Dimension2Problems { get; set; }
        public bool? Copdemphysema { get; set; }
        public bool? HighCholesterol { get; set; }
        public bool? Gerd { get; set; }
        public bool? Other { get; set; }
        public string OtherTxt { get; set; }
        public bool? HepatitisD { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}