// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_Bills", Schema = "pats")]
    public partial class TblBills
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        public int? RowChkSum { get; set; }
        [Key]
        [Column("billID")]
        public int BillId { get; set; }
        [Column("billCLTID")]
        public int? BillCltid { get; set; }
        [Column("billGuestID")]
        public int? BillGuestId { get; set; }
        [Column("billDate", TypeName = "datetime")]
        public DateTime? BillDate { get; set; }
        [Column("billBILL", TypeName = "money")]
        public decimal? BillBill { get; set; }
        [Column("billPAY", TypeName = "money")]
        public decimal? BillPay { get; set; }
        [Column("billPAYTYPE")]
        [StringLength(50)]
        public string BillPaytype { get; set; }
        [Column(TypeName = "money")]
        public decimal? BillAdjust { get; set; }
        [Column("billReason")]
        [StringLength(2500)]
        public string BillReason { get; set; }
        [Column("billReceiptNum")]
        public int? BillReceiptNum { get; set; }
        [Column("strUser")]
        [StringLength(50)]
        public string StrUser { get; set; }
        [Column("blnDeposit")]
        public bool BlnDeposit { get; set; }
        [Column("dtDeposit", TypeName = "datetime")]
        public DateTime? DtDeposit { get; set; }
        [Column("billADJUSTID")]
        public int? BillAdjustid { get; set; }
        [Column("FIFOallocated")]
        public bool? Fifoallocated { get; set; }
        [Column("FIFObalance", TypeName = "money")]
        public decimal? Fifobalance { get; set; }
        [StringLength(50)]
        public string Costcenter { get; set; }
        [Column("BillAptID")]
        public int? BillAptId { get; set; }
        [Column("billORGdt", TypeName = "date")]
        public DateTime? BillOrgdt { get; set; }
        [Column("BillServID")]
        public int? BillServId { get; set; }
        [Column("BillSiteID")]
        public int? BillSiteId { get; set; }
        public DateTime? LastModAt { get; set; }
        public bool RowState { get; set; }
    }
}