// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblBottle
    {
        public string SiteCode { get; set; }
        public int BottleId { get; set; }
        public int RowChkSum { get; set; }
        public DateTime LastModAt { get; set; }
        public bool? RowState { get; set; }
        public string Deanum { get; set; }
        public string LotNumber { get; set; }
        public DateTime? DtReceived { get; set; }
        public bool? Liquid { get; set; }
        public string BottleType { get; set; }
        public int? InitialAmount { get; set; }
        public DateTime? DtClosed { get; set; }
        public bool? BlnClosed { get; set; }
        public string StrUser { get; set; }
        public bool? White { get; set; }
        public decimal? SpecGrav { get; set; }
        public decimal? Weight { get; set; }
        public string Color { get; set; }
        public string InvGroup { get; set; }
        public int? BrId { get; set; }
        public int? SiteId { get; set; }
        public string Manufacturer { get; set; }
        public DateTime? ExpDate { get; set; }
    }
}