// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_Claims", Schema = "pats")]
    public partial class TblClaims
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        [Key]
        [Column("tpcID")]
        public int TpcId { get; set; }
        public int RowChkSum { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [Column("tpccltID")]
        public int? TpccltId { get; set; }
        [Column("tpcStrStatus")]
        [StringLength(100)]
        public string TpcStrStatus { get; set; }
        [Column("tpcStrPayer")]
        [StringLength(100)]
        public string TpcStrPayer { get; set; }
        [Column("tpcDtmAdded", TypeName = "datetime")]
        public DateTime? TpcDtmAdded { get; set; }
        [Column("tpcStrAdded")]
        [StringLength(100)]
        public string TpcStrAdded { get; set; }
        [Column("f10oth")]
        [StringLength(50)]
        public string F10oth { get; set; }
        [Column("tpcClaimBatchID")]
        public int? TpcClaimBatchId { get; set; }
        [Column("f11insnumber")]
        [StringLength(50)]
        public string F11insnumber { get; set; }
        [Column("f11insplan")]
        [StringLength(50)]
        public string F11insplan { get; set; }
        [Column("f11inssex")]
        [StringLength(50)]
        public string F11inssex { get; set; }
        [Column("f12sig")]
        [StringLength(50)]
        public string F12sig { get; set; }
        [Column("f12sigdate")]
        [StringLength(50)]
        public string F12sigdate { get; set; }
        [Column("f13inssig")]
        [StringLength(50)]
        public string F13inssig { get; set; }
        [Column("f14date")]
        [StringLength(50)]
        public string F14date { get; set; }
        [Column("f15firstdate")]
        [StringLength(50)]
        public string F15firstdate { get; set; }
        [Column("f16dateunableend")]
        [StringLength(50)]
        public string F16dateunableend { get; set; }
        [Column("f10auto")]
        [StringLength(50)]
        public string F10auto { get; set; }
        [Column("tpcStrPrimary")]
        [StringLength(100)]
        public string TpcStrPrimary { get; set; }
        [Column("f10employ")]
        [StringLength(50)]
        public string F10employ { get; set; }
        [Column("f10local")]
        [StringLength(50)]
        public string F10local { get; set; }
        [Column("f11insanother")]
        [StringLength(50)]
        public string F11insanother { get; set; }
        [Column("f11insdob")]
        [StringLength(50)]
        public string F11insdob { get; set; }
        [Column("f11insemploy")]
        [StringLength(50)]
        public string F11insemploy { get; set; }
        [Column("f16dateunablestart")]
        [StringLength(50)]
        public string F16dateunablestart { get; set; }
        [Column("f17refername")]
        [StringLength(50)]
        public string F17refername { get; set; }
        [Column("f17refernpi")]
        [StringLength(50)]
        public string F17refernpi { get; set; }
        [Column("f18datehospend")]
        [StringLength(50)]
        public string F18datehospend { get; set; }
        [Column("f18datehospstart")]
        [StringLength(50)]
        public string F18datehospstart { get; set; }
        [Column("f19local")]
        [StringLength(50)]
        public string F19local { get; set; }
        [Column("f1id")]
        [StringLength(50)]
        public string F1id { get; set; }
        [Column("f20outsidelab")]
        [StringLength(50)]
        public string F20outsidelab { get; set; }
        [Column("f21diag1")]
        [StringLength(50)]
        public string F21diag1 { get; set; }
        [Column("f21diag2")]
        [StringLength(50)]
        public string F21diag2 { get; set; }
        [Column("f21diag3")]
        [StringLength(50)]
        public string F21diag3 { get; set; }
        [Column("f21diag4")]
        [StringLength(50)]
        public string F21diag4 { get; set; }
        [Column("f22medresub")]
        [StringLength(50)]
        public string F22medresub { get; set; }
        [Column("f23priorauth")]
        [StringLength(50)]
        public string F23priorauth { get; set; }
        [Column("f25taxid")]
        [StringLength(50)]
        public string F25taxid { get; set; }
        [Column("f26account")]
        [StringLength(50)]
        public string F26account { get; set; }
        [Column("f27assign")]
        [StringLength(50)]
        public string F27assign { get; set; }
        [Column("f28totalcharge")]
        [StringLength(50)]
        public string F28totalcharge { get; set; }
        [Column("f29amtpaid")]
        [StringLength(50)]
        public string F29amtpaid { get; set; }
        [Column("f2name")]
        [StringLength(50)]
        public string F2name { get; set; }
        [Column("f30balancedue")]
        [StringLength(50)]
        public string F30balancedue { get; set; }
        [Column("f31date")]
        [StringLength(50)]
        public string F31date { get; set; }
        [Column("f31phys")]
        [StringLength(50)]
        public string F31phys { get; set; }
        [Column("f32a")]
        [StringLength(50)]
        public string F32a { get; set; }
        [Column("f32b")]
        [StringLength(50)]
        public string F32b { get; set; }
        [Column("f32line1")]
        [StringLength(50)]
        public string F32line1 { get; set; }
        [Column("f32line2")]
        [StringLength(50)]
        public string F32line2 { get; set; }
        [Column("f32line3")]
        [StringLength(50)]
        public string F32line3 { get; set; }
        [Column("f32line4")]
        [StringLength(50)]
        public string F32line4 { get; set; }
        [Column("f33a")]
        [StringLength(50)]
        public string F33a { get; set; }
        [Column("f33b")]
        [StringLength(50)]
        public string F33b { get; set; }
        [Column("f33line1")]
        [StringLength(50)]
        public string F33line1 { get; set; }
        [Column("f33line2")]
        [StringLength(50)]
        public string F33line2 { get; set; }
        [Column("f33line3")]
        [StringLength(50)]
        public string F33line3 { get; set; }
        [Column("f33line4")]
        [StringLength(50)]
        public string F33line4 { get; set; }
        [Column("f33phone")]
        [StringLength(50)]
        public string F33phone { get; set; }
        [Column("f3dob")]
        [StringLength(50)]
        public string F3dob { get; set; }
        [Column("f4insname")]
        [StringLength(50)]
        public string F4insname { get; set; }
        [Column("f5add")]
        [StringLength(50)]
        public string F5add { get; set; }
        [Column("f5city")]
        [StringLength(50)]
        public string F5city { get; set; }
        [Column("f5phone")]
        [StringLength(50)]
        public string F5phone { get; set; }
        [Column("f5state")]
        [StringLength(50)]
        public string F5state { get; set; }
        [Column("f5zip")]
        [StringLength(50)]
        public string F5zip { get; set; }
        [Column("f6insrel")]
        [StringLength(50)]
        public string F6insrel { get; set; }
        [Column("f7insadd")]
        [StringLength(50)]
        public string F7insadd { get; set; }
        [Column("f7inscity")]
        [StringLength(50)]
        public string F7inscity { get; set; }
        [Column("f7insphone")]
        [StringLength(50)]
        public string F7insphone { get; set; }
        [Column("f7insstate")]
        [StringLength(50)]
        public string F7insstate { get; set; }
        [Column("f7inszip")]
        [StringLength(50)]
        public string F7inszip { get; set; }
        [Column("f8stat")]
        [StringLength(50)]
        public string F8stat { get; set; }
        [Column("f9othinsdob")]
        [StringLength(50)]
        public string F9othinsdob { get; set; }
        [Column("f9othinsemp")]
        [StringLength(50)]
        public string F9othinsemp { get; set; }
        [Column("f9othinsname")]
        [StringLength(50)]
        public string F9othinsname { get; set; }
        [Column("f9othinsnumber")]
        [StringLength(50)]
        public string F9othinsnumber { get; set; }
        [Column("f9othinsplan")]
        [StringLength(50)]
        public string F9othinsplan { get; set; }
        [Column("f9othinssex")]
        [StringLength(50)]
        public string F9othinssex { get; set; }
        [Column("tpcCreatedDate", TypeName = "datetime")]
        public DateTime? TpcCreatedDate { get; set; }
        [Column("tpcEncounter")]
        [StringLength(10)]
        public string TpcEncounter { get; set; }
        [Column("tpcREBILLREASON")]
        [StringLength(500)]
        public string TpcRebillreason { get; set; }
        [Column("tpcStrWeek")]
        [StringLength(25)]
        public string TpcStrWeek { get; set; }
        [Column("tpcWKSTART", TypeName = "date")]
        public DateTime? TpcWkstart { get; set; }
        [Column("tpcPayerCIN")]
        [StringLength(100)]
        public string TpcPayerCin { get; set; }
        [Column("tpcSrvType")]
        [StringLength(50)]
        public string TpcSrvType { get; set; }
        [Column("f3sex")]
        [StringLength(10)]
        public string F3sex { get; set; }
        [Column("tpcClaimType")]
        public int? TpcClaimType { get; set; }
        [Column("SiteID")]
        public int? SiteId { get; set; }
        [Column("tpcDBnotes")]
        [StringLength(1000)]
        public string TpcDbnotes { get; set; }
        [Column("tpcReferring")]
        [StringLength(10)]
        public string TpcReferring { get; set; }
        public bool? RowState { get; set; }
    }
}