// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_Clinic", Schema = "ctrl")]
    public partial class TblClinic
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        [Key]
        [Column("PKEY")]
        public int Pkey { get; set; }
        [StringLength(50)]
        public string DoseWarn { get; set; }
        [StringLength(50)]
        public string DoseStop { get; set; }
        [StringLength(150)]
        public string Photos { get; set; }
        public bool? Bottles { get; set; }
        public int? Overdue { get; set; }
        public int? BillHold { get; set; }
        public int? Test { get; set; }
        [Column("TBTest")]
        public bool? Tbtest { get; set; }
        public bool? Force { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdated { get; set; }
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        [StringLength(50)]
        public string Provider { get; set; }
        [StringLength(50)]
        public string Site { get; set; }
        [Column("CLINICCODE")]
        [StringLength(50)]
        public string Cliniccode { get; set; }
        public bool? DischargeGuest { get; set; }
        public int? NumInventory { get; set; }
        [Column("SCHEDUA")]
        public bool? Schedua { get; set; }
        [Column("UAMONTHLY")]
        public bool? Uamonthly { get; set; }
        [Column("ClinicNAME")]
        [StringLength(100)]
        public string ClinicName { get; set; }
        [Column("TPAUTOMATION")]
        public int? Tpautomation { get; set; }
        public bool? RequireDarts { get; set; }
        public int? PhysicalTestDays { get; set; }
        [Column("ASPhysicalTest")]
        public bool? AsphysicalTest { get; set; }
        public bool? ServiceOverlapPopup { get; set; }
        public bool? OrangeandWhite { get; set; }
        [StringLength(50)]
        public string ToxProvider { get; set; }
        public int? NumberofReceipts { get; set; }
        public bool? PasswordEnforce { get; set; }
        public int? PasswordLength { get; set; }
        [Column("helpfile")]
        [StringLength(100)]
        public string Helpfile { get; set; }
        [StringLength(100)]
        public string ScanPath { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateSigStart { get; set; }
        public bool? ElecSigs { get; set; }
        public bool? CreditPriorWeek { get; set; }
        public bool? DefaultTabOrange { get; set; }
        [Column(TypeName = "decimal(10, 4)")]
        public decimal? BottleWeight { get; set; }
        [Column("spGRAVITY", TypeName = "decimal(10, 4)")]
        public decimal? SpGravity { get; set; }
        public bool? DoseCharge { get; set; }
        public int? TimeOffset { get; set; }
        public bool? CoSign { get; set; }
        [StringLength(50)]
        public string DefaultProgram { get; set; }
        public bool? ClientSecurity { get; set; }
        public bool? AutoCheckin { get; set; }
        public bool? CheckinCheck { get; set; }
        public bool? OrderService { get; set; }
        public bool? Residential { get; set; }
        [StringLength(50)]
        public string BillDirection { get; set; }
        public bool? SmallReceipts { get; set; }
        public bool? DuplicateCheckinCheck { get; set; }
        public bool? NoPrintCheckinLabel { get; set; }
        [StringLength(50)]
        public string AdDomain { get; set; }
        [Column("AutoSetLABELPrinter")]
        [StringLength(100)]
        public string AutoSetLabelprinter { get; set; }
        [StringLength(100)]
        public string AutoSetReceiptPrinter { get; set; }
        [StringLength(15)]
        public string ClinicLetter { get; set; }
        [StringLength(2)]
        public string ClinicState { get; set; }
        public bool? Liquid { get; set; }
        [StringLength(50)]
        public string OtherInvType { get; set; }
        public bool? PrintDoseAmt { get; set; }
        public bool? Tabs { get; set; }
        public bool? DailyServices { get; set; }
        [Column("clientsearchRIN")]
        public bool? ClientsearchRin { get; set; }
        public bool? ClientServiceBilling { get; set; }
        public bool? DischargeClearsHolds { get; set; }
        public bool? DrugFreeOnly { get; set; }
        [Column("halfweekcredit")]
        public bool? Halfweekcredit { get; set; }
        public bool? AllowRinZero { get; set; }
        public bool? AllowAnyRin { get; set; }
        public bool? DefaultShowHoldAtNursing { get; set; }
        public bool? HideElecSigDates { get; set; }
        public bool? QueSearch { get; set; }
        public bool? EducFieldIsEmpStatus { get; set; }
        [Column("AutoImportUA")]
        public bool? AutoImportUa { get; set; }
        public bool? FastDose { get; set; }
        [Column("RecIDPrint")]
        public bool? RecIdprint { get; set; }
        public bool? NurseSig { get; set; }
        [Column("ORDER2CONFIRM")]
        public int? Order2confirm { get; set; }
        [Column("ORDERCONFIRM")]
        public int? Orderconfirm { get; set; }
        [Column("ToxACCT")]
        [StringLength(50)]
        public string ToxAcct { get; set; }
        [Column("spGravityClear", TypeName = "decimal(10, 4)")]
        public decimal? SpGravityClear { get; set; }
        [Column("toxtixnum")]
        public int? Toxtixnum { get; set; }
        [Column("toxTixspecial")]
        [StringLength(500)]
        public string ToxTixspecial { get; set; }
        public bool? AutoOrderExpirationHolds { get; set; }
        [Column("reqallintake")]
        public bool? Reqallintake { get; set; }
        public int? NumberOfBulkLabels { get; set; }
        [Column("UAonVISIT")]
        public bool? UaonVisit { get; set; }
        [Column("Diversion_Padding")]
        public int? DiversionPadding { get; set; }
        [Column("WORDPATH")]
        [StringLength(250)]
        public string Wordpath { get; set; }
        public bool? ScanDeleteOriginal { get; set; }
        [Column("UDSpanelRequired")]
        public bool? UdspanelRequired { get; set; }
        public bool? AutoDischargeCredit { get; set; }
        public bool? BeakerColors { get; set; }
        public int? NumberPriorTransactionsOnReceipt { get; set; }
        public bool? AlwaysAllowUseSavedSignature { get; set; }
        public bool? NewBottleLabels { get; set; }
        [StringLength(200)]
        public string DocTemplatePath { get; set; }
        [StringLength(250)]
        public string ReportDir { get; set; }
        [Column("reportServer")]
        [StringLength(250)]
        public string ReportServer { get; set; }
        [Column("DonotallowCASCADE")]
        public bool? DonotallowCascade { get; set; }
        [Column("isBHG")]
        public bool? IsBhg { get; set; }
        public bool? MultipleQueues { get; set; }
        [StringLength(50)]
        public string LabAcct { get; set; }
        public bool? AlwaysAskBagLabel { get; set; }
        public bool? PrepackBagLabelDefault { get; set; }
        public bool? DefaultShowHoldFront { get; set; }
        [Column("ShowFutureUAholds")]
        public bool? ShowFutureUaholds { get; set; }
        public bool? OpenOnSunday { get; set; }
        public bool? ChargeBeforeDose { get; set; }
        public bool? LandscapeLabel { get; set; }
        [Column("sigIMGPATH")]
        [StringLength(250)]
        public string SigImgpath { get; set; }
        [Column("sigIMGURI")]
        [StringLength(250)]
        public string SigImguri { get; set; }
        public bool? SignBeforeDose { get; set; }
        [Column("SortClientSearchbyID")]
        public bool? SortClientSearchbyId { get; set; }
        [Column("UApath")]
        [StringLength(100)]
        public string Uapath { get; set; }
        [StringLength(100)]
        public string AdjustmentEmail { get; set; }
        [Column("blAdjustatDischarge")]
        public bool? BlAdjustatDischarge { get; set; }
        [Column("Fifo_Bottle")]
        public bool? FifoBottle { get; set; }
        public bool? UseCostCenter { get; set; }
        public bool? ForceCheckin { get; set; }
        public bool? VerifyMedAdjustment { get; set; }
        public bool? PinSigs { get; set; }
        [Column("COMBINE3PAYFEES")]
        public bool? Combine3payfees { get; set; }
        public bool? PinBeforeSig { get; set; }
        [Column("siglcd")]
        public bool? Siglcd { get; set; }
        [StringLength(150)]
        public string DictionaryPath { get; set; }
        [Column("grammerpath")]
        [StringLength(150)]
        public string Grammerpath { get; set; }
        [StringLength(50)]
        public string DiversionType { get; set; }
        [Column("ismedmark")]
        public bool? Ismedmark { get; set; }
        [Column("ServiceDimsLinkToTP")]
        public bool? ServiceDimsLinkToTp { get; set; }
        [Column("advancedtesting")]
        public bool? Advancedtesting { get; set; }
        public bool? AllowActOldOrder { get; set; }
        [Column("FirstInitialonTOXlabel")]
        public bool? FirstInitialonToxlabel { get; set; }
        public bool? Over100check { get; set; }
        public bool? NoQuePop { get; set; }
        [Column("offsetdoseconfirm")]
        public bool? Offsetdoseconfirm { get; set; }
        public bool? OrderRequestsNeedBothSigs { get; set; }
        public bool? SmallTox { get; set; }
        [Column("toxservice")]
        public bool? Toxservice { get; set; }
        public bool? Zebra { get; set; }
        public bool? FingerPrintSig { get; set; }
        [Column("VOregistrationpath")]
        [StringLength(150)]
        public string Voregistrationpath { get; set; }
        [Column("blockaptcalhold")]
        public bool? Blockaptcalhold { get; set; }
        public int? CalendarStartTime { get; set; }
        [Column("EligPW")]
        [StringLength(50)]
        public string EligPw { get; set; }
        [Column("EligUN")]
        [StringLength(50)]
        public string EligUn { get; set; }
        public bool? FiveDayCalendarWeek { get; set; }
        [Column("multitenant")]
        public bool? Multitenant { get; set; }
        [Column("pumpwindow")]
        public bool? Pumpwindow { get; set; }
        public bool? RequireEmergencyContact { get; set; }
        public bool? QueueTwice { get; set; }
        [Column("CheckUAIsPrescription")]
        public bool? CheckUaisPrescription { get; set; }
        [Column("enableBusPass")]
        public bool? EnableBusPass { get; set; }
        [StringLength(200)]
        public string ClaimDir { get; set; }
        [Column("isIHC")]
        public bool? IsIhc { get; set; }
        public bool? Phase { get; set; }
        [Column("setEvalsOtherFocus")]
        public int? SetEvalsOtherFocus { get; set; }
        public int? EnableHoldayPickupCalifornia { get; set; }
        [Column("ZeroSSNs")]
        public bool? ZeroSsns { get; set; }
        public bool? EnableTouchSig { get; set; }
        public bool? CreditDosesDischarge { get; set; }
        public bool? AllowBulkDrSigs { get; set; }
        public bool? EnableAlertsMedChanges { get; set; }
        public bool? EnableOrderAlerts { get; set; }
        public bool? EnableTestingAlerts { get; set; }
        public bool? EnableAtRiskAlerts { get; set; }
        public bool? EnableAdministeringClientMeds { get; set; }
        public bool? DisableServiceUnits { get; set; }
        [Column("isMultiProgram")]
        public bool? IsMultiProgram { get; set; }
        [Column("versionNbr", TypeName = "decimal(9, 5)")]
        public decimal? VersionNbr { get; set; }
        public bool? LabelPrintMedTypeInsteadOfMedClass { get; set; }
        public bool? EnableEnrollDischargeDateInSearchGrid { get; set; }
        public bool? EnableServiceRevisions { get; set; }
        [Column("enableBAC")]
        public bool? EnableBac { get; set; }
        public int? SammsFormsDefaultIndexNumber { get; set; }
        [Column("enableDriveMapping")]
        public bool? EnableDriveMapping { get; set; }
        [Column("destructbottle")]
        public bool? Destructbottle { get; set; }
        [Column("dontprintorders")]
        public bool? Dontprintorders { get; set; }
        public bool? DisablePrintServiceMessageAfterSavePrompt { get; set; }
        public bool? DisableOtherAsReferralSource { get; set; }
        public bool? EnableInventory4and5 { get; set; }
        public bool? SigPadTest { get; set; }
        public bool? EnableRssAlerts { get; set; }
        [Column("iispath")]
        [StringLength(300)]
        public string Iispath { get; set; }
        public bool? PrintAlternativeZebraAndDymoLabelVersion1 { get; set; }
        [Column("isRNP")]
        public bool? IsRnp { get; set; }
        public bool? EnableAutoPopulateCity { get; set; }
        [Column("IntakePacketURL")]
        [StringLength(500)]
        public string IntakePacketUrl { get; set; }
        public bool? NoCheckinatPay { get; set; }
        public bool? EnableAutoHoldOnAbnormalLab { get; set; }
        public int? MultiQueueRefreshIntervalTimeSet { get; set; }
        public bool? EnableSuffixMiddleInitialInFirstNameOfSearch { get; set; }
        [Column("enableUserLoginAtBACqueueModeElseInitials")]
        public bool? EnableUserLoginAtBacqueueModeElseInitials { get; set; }
        [Column("SiteID")]
        public int? SiteId { get; set; }
        public bool? PrintSitesAddressDependingOnSites { get; set; }
        [Column("DoNotPrintDOE")]
        public bool? DoNotPrintDoe { get; set; }
        [Column("enableAutoSpSAMMSBilling")]
        public bool? EnableAutoSpSammsbilling { get; set; }
        [Column("enableCounselorSelectionInMultiProgramSectionOnly")]
        public bool? EnableCounselorSelectionInMultiProgramSectionOnly { get; set; }
        [Column("URLassessment")]
        [StringLength(350)]
        public string Urlassessment { get; set; }
        [Column("DisableTPproblemAndInOwnWords")]
        public bool? DisableTpproblemAndInOwnWords { get; set; }
        [Column("enableCustomizableRequirementsForClientInfo")]
        public bool? EnableCustomizableRequirementsForClientInfo { get; set; }
        [Column("enableIntakeDischargeIncomeInputs")]
        public bool? EnableIntakeDischargeIncomeInputs { get; set; }
        [Column("enableAutoBillingDuringEachToxPrint")]
        public bool? EnableAutoBillingDuringEachToxPrint { get; set; }
        [Column("isSH")]
        public bool? IsSh { get; set; }
        [Column("enableBACstopDose")]
        public bool? EnableBacstopDose { get; set; }
        [Column("enableBACnurseHoldEvenBlowZero")]
        public bool? EnableBacnurseHoldEvenBlowZero { get; set; }
        public bool? EnableSignaturesDuringPillCount { get; set; }
        public bool? EnableSignatureWhenAdministeringMeds { get; set; }
        [Column("CHSAMSID")]
        [StringLength(50)]
        public string Chsamsid { get; set; }
        [Column("FTS")]
        public int? Fts { get; set; }
        public bool? Over20 { get; set; }
        [Column("forcefindtype")]
        public bool? Forcefindtype { get; set; }
        [Column("HnPUrl")]
        [StringLength(100)]
        public string HnPurl { get; set; }
        [Column("EnablePrintMedTypeColorOnIDCard")]
        public bool? EnablePrintMedTypeColorOnIdcard { get; set; }
        public bool? EnablePortraitLabelDoubleSide { get; set; }
        [Column("enableCommentsOnMultiCheckin")]
        public bool? EnableCommentsOnMultiCheckin { get; set; }
        [Column("PullPicsFromDB")]
        public bool? PullPicsFromDb { get; set; }
        public bool? EnableCompetentCheckBoxAtDosing { get; set; }
        public bool? EnableActivateOrderWhenNotInSuboxoneProg { get; set; }
        public bool? EnablePrintToxLandscape { get; set; }
        [Column("EnableFlagNurseForBAC")]
        public bool? EnableFlagNurseForBac { get; set; }
        public bool? BottleReturnNote { get; set; }
        [Column("BHGMarginTH")]
        public int? BhgmarginTh { get; set; }
        [Column("BHGMarginTox")]
        public int? BhgmarginTox { get; set; }
        public int? NoCheckinService { get; set; }
        [Column("NoSAMMSFormHeader")]
        public bool? NoSammsformHeader { get; set; }
        public bool? PrintUnitDoseLabel { get; set; }
        public bool? AuthBasedOnProgram { get; set; }
        public bool? LandscapeZebra { get; set; }
        public bool? ShowBalanceAtDispense { get; set; }
        public int? SingleQueueRefreshIntervalTimeSet { get; set; }
        public bool? MultiDosingClinic { get; set; }
        public bool? BlasterWide { get; set; }
        public bool? PumpCalibrate { get; set; }
        public bool? CheckVisitingPatient { get; set; }
        public bool? RequireClientSignatureOrderRequest { get; set; }
        public bool? DischargedAllowAddPayer { get; set; }
        public bool? DymoDetailed { get; set; }
    }
}