// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_ClaimLineItemActivity", Schema = "pats")]
    public partial class TblClaimLineItemActivity
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        [Key]
        [Column("liaID")]
        public int LiaId { get; set; }
        public int RowChkSum { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [Column("liaTPCLIID")]
        public int? LiaTpcliid { get; set; }
        [Column("liaDtm", TypeName = "datetime")]
        public DateTime? LiaDtm { get; set; }
        [Column("liaStrUser")]
        [StringLength(100)]
        public string LiaStrUser { get; set; }
        [Column("laiPAIDINS", TypeName = "money")]
        public decimal? LaiPaidins { get; set; }
        [Column("laiContADJ", TypeName = "money")]
        public decimal? LaiContAdj { get; set; }
        [Column("laiGENADJ", TypeName = "money")]
        public decimal? LaiGenadj { get; set; }
        [Column("laiCOPay", TypeName = "money")]
        public decimal? LaiCopay { get; set; }
        [Column("laiDEDUC", TypeName = "money")]
        public decimal? LaiDeduc { get; set; }
        [Column("laiCLIENT", TypeName = "money")]
        public decimal? LaiClient { get; set; }
        [Column("liaBitNoteOnly")]
        public bool? LiaBitNoteOnly { get; set; }
        [Column("liaStrDesc")]
        [StringLength(1000)]
        public string LiaStrDesc { get; set; }
        [Column("tprbID")]
        public int TprbId { get; set; }
        [Column("liaPending")]
        public bool? LiaPending { get; set; }
        [Column("liaamt", TypeName = "money")]
        public decimal? Liaamt { get; set; }
        [Column("liastrtext")]
        [StringLength(50)]
        public string Liastrtext { get; set; }
        [Column("liaADJREASON")]
        [StringLength(100)]
        public string LiaAdjreason { get; set; }
        [Column("laiCOINS", TypeName = "money")]
        public decimal? LaiCoins { get; set; }
        [Column("liaAction1")]
        [StringLength(500)]
        public string LiaAction1 { get; set; }
        [Column("liaAction2")]
        [StringLength(500)]
        public string LiaAction2 { get; set; }
        [Column("liaADJcontract")]
        [StringLength(100)]
        public string LiaAdjcontract { get; set; }
        [Column("liaADJgeneral")]
        [StringLength(100)]
        public string LiaAdjgeneral { get; set; }
        [Column("liaANSI1")]
        [StringLength(50)]
        public string LiaAnsi1 { get; set; }
        [Column("liaANSI2")]
        [StringLength(50)]
        public string LiaAnsi2 { get; set; }
        [Column("liaANSImod1")]
        [StringLength(50)]
        public string LiaAnsimod1 { get; set; }
        [Column("liaANSImod2")]
        [StringLength(50)]
        public string LiaAnsimod2 { get; set; }
        [Column("BillID")]
        public int? BillId { get; set; }
        [Column("liaDBnotes")]
        [StringLength(1000)]
        public string LiaDbnotes { get; set; }
        public bool? RowState { get; set; }
    }
}