// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblCowxref
    {
        public string ColumnName { get; set; }
        public int PermissibleValue { get; set; }
        public string DescripiveText { get; set; }
    }
}