// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblCowsV6
    {
        public string SiteCode { get; set; }
        public int Cowid { get; set; }
        public int Preadmissionid { get; set; }
        public int CltId { get; set; }
        public bool RowState { get; set; }
        public int RowChkSum { get; set; }
        public DateTime LastModAt { get; set; }
        public DateTime? Dttime { get; set; }
        public string ReasonforthisAssessment { get; set; }
        public int? RestingPulseRate { get; set; }
        public string RestingPulseRatedesc { get; set; }
        public int? Giupset { get; set; }
        public string Giupsetdesc { get; set; }
        public int? Sweating { get; set; }
        public string Sweatingdesc { get; set; }
        public int? Tremor { get; set; }
        public string Tremordesc { get; set; }
        public int? Restlessness { get; set; }
        public string Restlessnessdesc { get; set; }
        public int? Yawning { get; set; }
        public string Yawningdec { get; set; }
        public int? PupilSize { get; set; }
        public string PupilSizedesc { get; set; }
        public int? AnxietyOrIrritability { get; set; }
        public string AnxietyOrIrritabilitydesc { get; set; }
        public int? BoneOrJointAches { get; set; }
        public string BoneOrJointAchesdesc { get; set; }
        public int? GoosefleshSkin { get; set; }
        public string GoosefleshSkindesc { get; set; }
        public int? RunnyNoseOrTearing { get; set; }
        public string RunnyNoseOrTearingdesc { get; set; }
        public string CompletedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public bool? IsActive { get; set; }
        public string PatientSignature { get; set; }
        public DateTime? ClientSignatureDate { get; set; }
        public bool? IsDeleted { get; set; }
        public string StaffNameSignature { get; set; }
        public string Version { get; set; }
        public DateTime? StaffSignatureDate { get; set; }
    }
}