// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_ClientDemo1", Schema = "pats")]
    public partial class TblClientDemo1
    {
        [Key]
        public long PrimKey { get; set; }
        [StringLength(25)]
        public string SiteCode { get; set; }
        [Column("ClientID")]
        public int ClientId { get; set; }
        public int? RowChkSum { get; set; }
        [Column("ClientM4ID")]
        [StringLength(50)]
        public string ClientM4id { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string MiddleName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string Suffix { get; set; }
        [Column("DOB", TypeName = "date")]
        public DateTime? Dob { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }
        [Column("SSN")]
        [StringLength(15)]
        public string Ssn { get; set; }
        [Column("email")]
        [StringLength(100)]
        public string Email { get; set; }
        public int? Size { get; set; }
        [StringLength(100)]
        public string Address1 { get; set; }
        [StringLength(100)]
        public string Address2 { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [StringLength(3)]
        public string State { get; set; }
        [Column("zip")]
        [StringLength(20)]
        public string Zip { get; set; }
        [StringLength(25)]
        public string Phone { get; set; }
        [Column("preg")]
        public bool? Preg { get; set; }
        [Column("PregEDC", TypeName = "date")]
        public DateTime? PregEdc { get; set; }
        [StringLength(50)]
        public string Marital { get; set; }
        [StringLength(50)]
        public string EmpStatus { get; set; }
        [StringLength(50)]
        public string Employer { get; set; }
        [StringLength(100)]
        public string WorkPhone { get; set; }
        [StringLength(50)]
        public string Income { get; set; }
        [StringLength(50)]
        public string Education { get; set; }
        [StringLength(50)]
        public string Hair { get; set; }
        [StringLength(50)]
        public string Eye { get; set; }
        [StringLength(50)]
        public string Height { get; set; }
        [StringLength(50)]
        public string Weight { get; set; }
        [StringLength(50)]
        public string Race { get; set; }
        [StringLength(50)]
        public string Language { get; set; }
        [StringLength(75)]
        public string County { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModAt { get; set; }
        public int? RowState { get; set; }
    }
}