// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblCustomAnswers
    {
        public string SiteCode { get; set; }
        public DateTime LastModAt { get; set; }
        public int RowCheckSum { get; set; }
        public int RowSate { get; set; }
        public int CaId { get; set; }
        public int CaQid { get; set; }
        public int CaCltid { get; set; }
        public string CaAns { get; set; }
    }
}