// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblDoseExcuse
    {
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        public bool RowState { get; set; }
        public int ExId { get; set; }
        public int? CltId { get; set; }
        public DateTime? DtEx { get; set; }
        public string StrExcused { get; set; }
        public DateTime? Dtstamp { get; set; }
        public string StrUser { get; set; }
        public DateTime LastModAt { get; set; }
    }
}