// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblDboFormAnswerSignatures
    {
        public string SiteCode { get; set; }
        public string FormName { get; set; }
        public string FormId { get; set; }
        public int ClientId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public DateTime? CompletedBySignatureSignatureDate { get; set; }
        public DateTime? CounselorSignatureSignatureDate { get; set; }
        public DateTime? DoctorSignatureSignatureDate { get; set; }
        public DateTime? MedicalProviderSignatureSignatureDate { get; set; }
        public DateTime? PatientSignatureDate { get; set; }
        public DateTime? ProviderSignatureSignatureDate { get; set; }
        public DateTime? RequestorSignatureDate { get; set; }
        public DateTime? StaffSignatureDate { get; set; }
        public DateTime? SupervisorSignatureSignatureDate { get; set; }
        public int? RowState { get; set; }
        public DateTime? LastModAt { get; set; }
        public int? RowChkSum { get; set; }
    }
}