// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblDose
    {
        public string SiteCode { get; set; }
        public bool RowState { get; set; }
        public int? RowChkSum { get; set; }
        public DateTime? LastModAt { get; set; }
        public long DoseId { get; set; }
        public int CltId { get; set; }
        public DateTime DtMedDate { get; set; }
        public int? GuestId { get; set; }
        public DateTime? DtDate { get; set; }
        public int? Dose { get; set; }
        public string StrUser { get; set; }
        public bool? BlVoid { get; set; }
        public string StrVoidReason { get; set; }
        public bool? BlException { get; set; }
        public string Bottletype { get; set; }
        public int? Ordernum { get; set; }
        public string ExceptionReason { get; set; }
        public bool? BlBulk { get; set; }
        public bool? BlPrepack { get; set; }
        public DateTime? Dtgiven { get; set; }
        public DateTime? Dtprep { get; set; }
        public bool? DtVoid { get; set; }
        public string Ppstaff { get; set; }
        public string Exceptiontype { get; set; }
        public DateTime? Manualauthdtm { get; set; }
        public string Manualauthuser { get; set; }
        public string Dosenote { get; set; }
        public string Dosesig { get; set; }
        public string InventoryGroup { get; set; }
        public int? SiteId { get; set; }
        public byte[] DoseSigImg { get; set; }
    }
}