// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblDboFormQuestionAnswers
    {
        public string SiteCode { get; set; }
        public string FormName { get; set; }
        public string FormId { get; set; }
        public int ClientId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public int? PreAdmissionId { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsChildForm { get; set; }
        public int QuestionId { get; set; }
        public int QuestionOrderId { get; set; }
        public string QuestionText { get; set; }
        public string OptionId { get; set; }
        public string AnswerValue { get; set; }
        public int? RowState { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}