// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblDboAnswerSignatures
    {
        public string SiteCode { get; set; }
        public string FormId { get; set; }
        public int SignatureId { get; set; }
        public bool? Sign { get; set; }
        public DateTime? SignedDateTime { get; set; }
        public string ImageField { get; set; }
        public string DataField { get; set; }
        public string DateField { get; set; }
        public string SignatureName { get; set; }
        public bool? IsChildForm { get; set; }
        public int? RowState { get; set; }
        public DateTime? LastModAt { get; set; }
        public int? RowChkSum { get; set; }
    }
}