// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BHG_DR_LIB.Models
{
    public partial class TblFormsCounts
    {
        public DateTime FscDate { get; set; }
        public string SiteCode { get; set; }
        public int fscsid { get; set; }
        public int fscCltID { get; set; }
        public int Cnt { get; set; }
    }
}