// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblGlobalDevices
    {
        public string SiteCode { get; set; }
        public int DId { get; set; }
        public string DDeviceid { get; set; }
        public int? DSid { get; set; }
        public int? DPumpnum { get; set; }
        public bool? DCheckin { get; set; }
        public string DPumptype { get; set; }
        public bool? DTestmode { get; set; }
        public string DLabel { get; set; }
        public string DReceipt { get; set; }
        public bool? DSigpad { get; set; }
        public bool? DDispense { get; set; }
        public bool? DFingerprint { get; set; }
        public bool? DTouchScreen { get; set; }
        public bool? DBacqueuePc { get; set; }
    }
}