// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblInvtype
    {
        public string SiteCode { get; set; }
        public int Invid { get; set; }
        public int RowChkSum { get; set; }
        public DateTime LastModAt { get; set; }
        public bool? RowState { get; set; }
        public string InvName { get; set; }
        public bool? InvLiquid { get; set; }
        public int? InvUnit { get; set; }
        public int? InvTotal { get; set; }
        public decimal? InvDivision { get; set; }
        public bool? DefaultMed { get; set; }
        public string DisplayName { get; set; }
        public string InvMedclass { get; set; }
        public bool? IsFilm { get; set; }
        public string Type { get; set; }
        public bool? HasBeaker { get; set; }
        public string InvActual { get; set; }
        public string InvLabelName { get; set; }
        public string InvNdc { get; set; }
        public string InvJcode { get; set; }
    }
}