// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_LocationCmds", Schema = "ctrl")]
    public partial class TblLocationCmds
    {
        [Key]
        public int CmdId { get; set; }
        [Required]
        [StringLength(25)]
        public string SiteCode { get; set; }
        public int CmdType { get; set; }
        public int CmdOrder { get; set; }
        [Column("ConID")]
        public int ConId { get; set; }
        public int StepKey { get; set; }
        public int CmdCtrl { get; set; }
        [Required]
        [StringLength(1000)]
        public string CmdStr { get; set; }
    }
}