// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblLabresult
    {
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        public DateTime LastModAt { get; set; }
        public int LabrId { get; set; }
        public int LablngCltId { get; set; }
        public int? LabrSchedId { get; set; }
        public DateTime? LabrDropDt { get; set; }
        public DateTime? LabrResultDt { get; set; }
        public string LabrCreatedBy { get; set; }
        public DateTime? LabrCreatedDt { get; set; }
        public string Labnote { get; set; }
        public byte[] UpsizeTs { get; set; }
        public decimal? RepOldLab { get; set; }
        public string LabrUpdatedBy { get; set; }
        public DateTime? LabrUpdatedDt { get; set; }
        public string LabBase64 { get; set; }
        public string LabrLotno { get; set; }
        public string OldClient { get; set; }
        public int? SiteId { get; set; }
        public string LabOrderId { get; set; }
        public string SupplementaryReport { get; set; }
        public string LabName { get; set; }
    }
}