// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblLiquidLog
    {
        public string SiteCode { get; set; }
        public int LiqId { get; set; }
        public int RowChkSum { get; set; }
        public DateTime LastModAt { get; set; }
        public bool? RowState { get; set; }
        public short? Pump { get; set; }
        public int? DoseId { get; set; }
        public int? BtlId { get; set; }
        public int? BkrId { get; set; }
        public decimal? Amt { get; set; }
        public DateTime? Dtm { get; set; }
        public string Desc { get; set; }
        public string Staff { get; set; }
        public bool BlLogOnly { get; set; }
        public bool? BlPrepack { get; set; }
        public string Memonew { get; set; }
        public string Memo { get; set; }
        public DateTime? DtRti { get; set; }
        public string AcknowledgeDate { get; set; }
        public string AcknowledgeUser { get; set; }
        public DateTime? RegionalDate { get; set; }
        public string RegionalUser { get; set; }
        public string ComplainceUser { get; set; }
        public DateTime? ComplianceDate { get; set; }
        public string Invgroup { get; set; }
        public int? SiteId { get; set; }
    }
}