// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblLocations
    {
        public string SiteCode { get; set; }
        public string ClinicName { get; set; }
        public string RegionCode { get; set; }
        public bool IsActive { get; set; }
        public string SiteClinic { get; set; }
        public string Location { get; set; }
        public string StateCode { get; set; }
        public string ZipCode { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public DateTime? ContractDate { get; set; }
        public DateTime? EnrollCutoff { get; set; }
        public DateTime? SammstrxDate { get; set; }
        public string AltRegion { get; set; }
        public string AcctCmpyId { get; set; }
        public int? SId { get; set; }
        public bool? IsNewSchema { get; set; }
        public string VpregionCode { get; set; }
    }
}