// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_MapSrc2Dsn", Schema = "dms")]
    public partial class TblMapSrc2Dsn
    {
        [Key]
        public long ActionKey { get; set; }
        [Key]
        public int ActionStepKey { get; set; }
        [Key]
        public int FieldKey { get; set; }
        [Required]
        [StringLength(50)]
        public string FieldName { get; set; }
        public bool Enabled { get; set; }
        public int? PrimaryKey { get; set; }
        [Required]
        [StringLength(25)]
        public string FieldType { get; set; }
        public int FieldLength { get; set; }
        public int FieldPrecision { get; set; }
        public int FieldScale { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [Required]
        [StringLength(50)]
        public string LastModBy { get; set; }
        [StringLength(50)]
        public string DsnFieldName { get; set; }
        public bool? Nullable { get; set; }
        [StringLength(255)]
        public string Default { get; set; }
        [StringLength(255)]
        public string FormatConvert { get; set; }
    }
}