// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblOrientationChecklistNew
    {
        public string SiteCode { get; set; }
        public int CheckListId { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? ClientId { get; set; }
        public int? DataFormId { get; set; }
        public bool? PatientComplaints { get; set; }
        public bool? AccesstoEmergency { get; set; }
        public bool? CodeofEthics { get; set; }
        public bool? ConfidentialityPolicy { get; set; }
        public bool? Methods { get; set; }
        public bool? ExplanationofFiancialObligations { get; set; }
        public bool? RulesforInvoluntaryDetox { get; set; }
        public bool? FireSafety { get; set; }
        public bool? ProgramRulesonPatientParking { get; set; }
        public bool? PolicyonRestraint { get; set; }
        public bool? PolicyonTobaccoProducts { get; set; }
        public bool? PolicyonIllicit { get; set; }
        public bool? PolicyonWeapons { get; set; }
        public bool? KnowledgeofNames { get; set; }
        public bool? ProgramRules { get; set; }
        public bool? Aidshivprevention { get; set; }
        public bool? HepatitisPrevention { get; set; }
        public bool? PurposeandProcess { get; set; }
        public bool? IndividualTreatmentPlan { get; set; }
        public bool? PolicyRegardingUrineDrug { get; set; }
        public bool? DischargeTransitionCriteria { get; set; }
        public bool? NaturalProgression { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool? IsDeleted { get; set; }
        public string Version { get; set; }
        public DateTime? StaffSignatureDate { get; set; }
        public string StaffSignatureBy { get; set; }
        public DateTime? PatientSignatureDate { get; set; }
        public string PatientSignatureBy { get; set; }
        public DateTime? LastModEtl { get; set; }
        public string PatientSignature { get; set; }
        public string StaffSignature { get; set; }
    }
}