// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblPbi3Payauth
    {
        public string SiteCode { get; set; }
        public int TpaId { get; set; }
        public DateTime TpEffdate { get; set; }
        public int? TpaCltid { get; set; }
        public string TpaPayer { get; set; }
        public string TpaDesc { get; set; }
        public DateTime? TpaEffDate { get; set; }
        public DateTime? TpaTermDate { get; set; }
        public string TpaStaff { get; set; }
        public DateTime? Tpadt { get; set; }
        public string TpaAuthCode { get; set; }
        public string TpAuthpath { get; set; }
        public string TpConfirmpath { get; set; }
        public string TpFail { get; set; }
        public string TpRequestForm { get; set; }
        public string TpResponseForm { get; set; }
        public string TpServ { get; set; }
        public DateTime? TpTermDate { get; set; }
        public int? TpUnits { get; set; }
        public string TpServapproved { get; set; }
        public string TpNote { get; set; }
        public string TpType { get; set; }
        public string TpaCompKey { get; set; }
        public string TpaBigKey { get; set; }
        public string ProgGroup { get; set; }
        public string PayerGroup { get; set; }
        public string PayerType { get; set; }
        public DateTime? LastModAt { get; set; }
        public int? RowChkSum { get; set; }
        public bool RowState { get; set; }
    }
}