// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblReAssessmentSubstanceUse
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int? PreAdmissionId { get; set; }
        public int ReAssessmentId { get; set; }
        public int? HaveYouHadAnOverdose { get; set; }
        public int? DoYouUseTobaccoOrVapeNicotine { get; set; }
        public string CommentsSubstanceUse { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}