// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BHG_DR_LIB.Models
{
    [Table("tbl_SERVICES", Schema = "pats")]
    public partial class TblServices
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        [Key]
        [Column("sID")]
        public int SId { get; set; }
        [Column("sSERVICE")]
        [StringLength(250)]
        public string SService { get; set; }
        [Column("sArea")]
        [StringLength(250)]
        public string SArea { get; set; }
        [Column("sCost", TypeName = "money")]
        public decimal? SCost { get; set; }
        [Column("sCPTCODE")]
        [StringLength(50)]
        public string SCptcode { get; set; }
        [Column("sREQSIG")]
        public bool? SReqsig { get; set; }
        [Column("sREQTIME")]
        public bool? SReqtime { get; set; }
        [Column("blAllowOverlap")]
        public bool? BlAllowOverlap { get; set; }
        [Column("oldArea")]
        [StringLength(100)]
        public string OldArea { get; set; }
        [Column("oldSrv")]
        [StringLength(100)]
        public string OldSrv { get; set; }
        [Column("sFilter")]
        public bool? SFilter { get; set; }
        [Column("sReportBillable")]
        public bool? SReportBillable { get; set; }
        [Column("sTimeOnly")]
        public bool? STimeOnly { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? LastModAt { get; set; }
        public bool? IsActive { get; set; }
    }
}