// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblTreatmentLevel
    {
        public string SiteCode { get; set; }
        public int? RowChkSum { get; set; }
        public bool? RowState { get; set; }
        public DateTime? LastModAt { get; set; }
        public int ID { get; set; }
        public string? TreatmentLevel { get; set; }
        public int? UserID { get; set; }
        public int? CltId { get; set; }
        public DateTime? RecordOn { get; set; }
    }
}
