// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_Tasks2", Schema = "tsk")]
    public partial class TblTasks
    {
        [Key]
        public int TaskId { get; set; }
        [Required]
        [StringLength(130)]
        public string TaskName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime RunAt { get; set; }
        public int ActionKey { get; set; }
        public int ActionStepKey { get; set; }
        public int Status { get; set; }
        [Required]
        [StringLength(25)]
        public string Duration { get; set; }
        public int OnCompletion { get; set; }
        public int OnError { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [Required]
        [StringLength(30)]
        public string LastModBy { get; set; }
        public int RowState { get; set; }
        public int? DependentTaskId { get; set; }
        public int? ParentTaskId { get; set; }
        [StringLength(25)]
        public string SiteCode { get; set; }
        public DateTime? WorkDate { get; set; }
        public int? RowCount { get; set; }
        public string ErrorMessage { get; set; }
        public int? RowsIns { get; set; }
        public int? RowsUpd { get; set; }
        public bool? Reload { get; set; }
        
    }
    public partial class RCodes
    {
        public int TaskId { get; set; }
        public bool IsResult { get; set; }
        public int RowsProcessed { get; set; }
        public int RowsIns { get; set; }
        public int RowsUpd { get; set; }
        public string ExceptMsg { get; set; }
        public string ExceptInnerMsg { get; set; }
    }

}