// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_UAResultDetail", Schema = "pats")]
    public partial class TblUaresultDetail
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [Key]
        [Column("uardID")]
        public int UardId { get; set; }
        [Key]
        [Column("uardRecID")]
        public int UardRecId { get; set; }
        [Column("uardResult")]
        [StringLength(100)]
        public string UardResult { get; set; }
        [Column("uardRX")]
        public bool UardRx { get; set; }
        [Column("uaDetail")]
        [StringLength(50)]
        public string UaDetail { get; set; }
        [Column("uardFullNote")]
        public string UardFullNote { get; set; }
        [Column("uardKey")]
        public string UardKey { get; set; }
        [Column("uardNote")]
        public string UardNote { get; set; }
    }
}