// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_UserSites", Schema = "ctrl")]
    public partial class TblUserSites
    {
        [Key]
        [Column("usID")]
        public int UsId { get; set; }
        [Column("usNAME")]
        [StringLength(50)]
        public string UsName { get; set; }
        [Column("usSite")]
        public int? UsSite { get; set; }
        [Column("usDEFAULT")]
        public bool? UsDefault { get; set; }
    }
}