// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class Tblvw3pBillSub
    {
        public string SiteCode { get; set; }
        public string Descript { get; set; }
        public DateTime? Billdatecriteria { get; set; }
        public string PayDefaultsubmit { get; set; }
        public string ScrubError { get; set; }
        public int DsId { get; set; }
        public int? DsClt { get; set; }
        public string DsTxtSrv { get; set; }
        public DateTime? DsDtStart { get; set; }
        public DateTime? DsDtEnd { get; set; }
        public string DsTxtType { get; set; }
        public double? DsdblUnits { get; set; }
        public double? BillUnits { get; set; }
        public string DstxtStaff { get; set; }
        public string Npi { get; set; }
        public DateTime? Dsbilled { get; set; }
        public string PyPayerid { get; set; }
        public string PySubsid { get; set; }
        public string PyGroup { get; set; }
        public string Cptcode { get; set; }
        public double? Charge { get; set; }
        public string TpaAuthCode { get; set; }
        public string Clientname { get; set; }
        public DateTime? CltDob { get; set; }
        public string CltGender { get; set; }
        public string CltAdd1 { get; set; }
        public string CltCity { get; set; }
        public string CltState { get; set; }
        public string Cltzip { get; set; }
        public string CltPhone { get; set; }
        public string CltMarry { get; set; }
        public string CltM4id { get; set; }
        public string Dsdiag { get; set; }
        public string Modifier { get; set; }
        public string DsPos { get; set; }
        public string Ndc { get; set; }
        public double? Mg { get; set; }
        public int? SiteId { get; set; }
        public string Dsarea { get; set; }
        public string Payclass { get; set; }
        public DateTime? LastModAt { get; set; }
        public bool? RowState { get; set; }
        public int? RowChkSum { get; set; }
        public string CptMod { get; set; }
    }
}