// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BHG_DR_LIB.Models
{
    public partial class VwOrders
    {
        public string SiteCode { get; set; }
        public int OrderNum { get; set; }
        public int CltId { get; set; }
        public int RowChkSum { get; set; }
        public DateTime LastModAt { get; set; }
        public string MedType { get; set; }
        public DateTime? DateAdded { get; set; }
        public DateTime? Orderdate { get; set; }
        public string Doctor { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public decimal? Dose { get; set; }
        public decimal? Dose2 { get; set; }
        public int? Changeby { get; set; }
        public short? Intervals { get; set; }
        public bool? Sunday { get; set; }
        public bool? Monday { get; set; }
        public bool? Tuesday { get; set; }
        public bool? Wednesday { get; set; }
        public bool? Thursday { get; set; }
        public bool? Friday { get; set; }
        public bool? Saturday { get; set; }
        public bool? Sunday2 { get; set; }
        public bool? Monday2 { get; set; }
        public bool? Tuesday2 { get; set; }
        public bool? Wednesday2 { get; set; }
        public bool? Thursday2 { get; set; }
        public bool? Friday2 { get; set; }
        public bool? Saturday2 { get; set; }
        public string Notes { get; set; }
        public bool? Active { get; set; }
        public string Type { get; set; }
        public string Stype { get; set; }
        public int? Weeknum { get; set; }
        public bool? SplitFirst { get; set; }
        public bool? Blind { get; set; }
        public string OUser { get; set; }
        public string CltM4id { get; set; }
        public int? Newdose { get; set; }
        public string Pckcode { get; set; }
        public string RxhistId { get; set; }
        public bool? Ex { get; set; }
        public DateTime? ActbyDate { get; set; }
        public string ActByUser { get; set; }
        public bool? White { get; set; }
        public decimal? RepOldOrder { get; set; }
        public string SigDr { get; set; }
        public DateTime? DtSig { get; set; }
        public bool? Aws { get; set; }
        public bool? BlSched { get; set; }
        public bool? BlVerbal { get; set; }
        public string Color { get; set; }
        public DateTime? DeActbyDate { get; set; }
        public string DeActbyUser { get; set; }
        public string OrderTypev5 { get; set; }
        public string Sigentered { get; set; }
        public string Signoted { get; set; }
        public DateTime? SigNoteddt { get; set; }
        public DateTime? Dtmid { get; set; }
        public string SigMid { get; set; }
        public string OverApprove { get; set; }
        public string OverapproveDt { get; set; }
        public DateTime? Sigentereddt { get; set; }
        public byte[] SigDrImg { get; set; }
        public byte[] SigMidImg { get; set; }
        public byte[] SigNotedImg { get; set; }
    }
}