// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblPreAdmissionV6
    {
        public string SiteCode { get; set; }
        public int PreAdmissionid { get; set; }
        public int Clientid { get; set; }
        public string cltM4ID { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string Createdby { get; set; }
        public DateTime? PreAdmissionDate { get; set; }
        public string RegistrationMode { get; set; }
        public string ReferralSourcedesc { get; set; }
        public string PrimaryReferralSourceNote { get; set; }
        public string Program { get; set; }
        public string InsuranceType { get; set; }
        public string IntakeProgram { get; set; }
        public DateTime? IntakeProgramDate { get; set; }
        public string IsCurrentlyInOpiateProgram { get; set; }
        public string IsPatientAtPainManagementClinic { get; set; }
        public string IsHavingLegalPrescription { get; set; }
        public string IsAnyLegalPrescriptionForPain { get; set; }
        public string IsAnyOngoingMedicalCondition { get; set; }
        public string IsSuicidalThoughtWithin72Hours { get; set; }
        public string IsHavingPlanForHowToCommitSuicide { get; set; }
        public string IsHomicidalThoughtWithin72Hours { get; set; }
        public string IsRecentlyReleasedFromPenal { get; set; }
        public string IsSpecialAccommodationRequired { get; set; }
        public string ReasonSeekingTreatment { get; set; }
        public string AccomodationNeeded { get; set; }
        public string ClientAddress { get; set; }
        public string Comments { get; set; }
        public string IsPatientAdmitted { get; set; }
        public string AreYouCurrentlyPregnant { get; set; }
        public string BringIdproof { get; set; }
        public string BringInsuranceCard { get; set; }
        public string ClinicInfo { get; set; }
        public string CurrntlyRecevingTreatmentForCondition { get; set; }
        public string IsAnyPrescriptionForPain { get; set; }
        public string IsInsurance { get; set; }
        public string IsOverTheCounterMedications { get; set; }
        public string ImmediateAssessment { get; set; }
        public string ImmediateAssessment911 { get; set; }
        public string MedicalConditionsProviderName1 { get; set; }
        public string MedicalConditionsProviderPhone1 { get; set; }
        public string MedicalConditionsProviderName2 { get; set; }
        public string MedicalConditionsProviderPhone2 { get; set; }
        public string PlanOfSuicide { get; set; }
        public string PlanOnSpendingTimeAtClinic { get; set; }
        public string Sammsprogram { get; set; }
        public string OfficeUseWhy { get; set; }
        public string OngoingMedicalConditionsWha { get; set; }
        public string PreAddAddress { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdateOn { get; set; }
        public DateTime? PatientSignatureDate { get; set; }
        public DateTime? DateofRelease { get; set; }
        public string Version { get; set; }
        public int RowChkSum { get; set; }
        public DateTime EtllastModAt { get; set; }
        public bool? RowState { get; set; }
    }
}