// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BHG_DR_LIB.Models2
{
    public partial class BHG_DRContext : DbContext
    {
        public BHG_DRContext()
        {
        }

        public BHG_DRContext(DbContextOptions<BHG_DRContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TblDose> TblDose { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=bhgazuresql01.database.windows.net;Initial Catalog=BHG_DR;User ID=brian.catellier@bhgrecovery.com;Password=Special38Ranger32!;Authentication=\"Active Directory Password\"");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TblDose>(entity =>
            {
                entity.HasKey(e => new { e.SiteCode, e.CltId, e.DtMedDate, e.DoseId })
                    .HasName("PK_Dose");

                entity.ToTable("tbl_DOSE", "pats");

                entity.Property(e => e.SiteCode)
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.CltId).HasColumnName("CltID");

                entity.Property(e => e.DtMedDate)
                    .HasColumnName("dtMedDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.DoseId).HasColumnName("DoseID");

                entity.Property(e => e.BlBulk).HasColumnName("blBULK");

                entity.Property(e => e.BlException).HasColumnName("blException");

                entity.Property(e => e.BlPrepack).HasColumnName("blPrepack");

                entity.Property(e => e.BlVoid).HasColumnName("blVoid");

                entity.Property(e => e.Bottletype)
                    .HasColumnName("bottletype")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Dosenote)
                    .HasColumnName("dosenote")
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.Dosesig)
                    .HasColumnName("dosesig")
                    .HasColumnType("ntext");

                entity.Property(e => e.DtDate)
                    .HasColumnName("dtDate")
                    .HasColumnType("datetime");

                entity.Property(e => e.DtVoid).HasColumnName("dtVoid");

                entity.Property(e => e.Dtgiven)
                    .HasColumnName("DTgiven")
                    .HasColumnType("datetime");

                entity.Property(e => e.Dtprep)
                    .HasColumnName("DTprep")
                    .HasColumnType("datetime");

                entity.Property(e => e.ExceptionReason)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.Exceptiontype)
                    .HasColumnName("exceptiontype")
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.GuestId).HasColumnName("GuestID");

                entity.Property(e => e.InventoryGroup)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Manualauthdtm)
                    .HasColumnName("manualauthdtm")
                    .HasColumnType("datetime");

                entity.Property(e => e.Manualauthuser)
                    .HasColumnName("manualauthuser")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Ordernum).HasColumnName("ordernum");

                entity.Property(e => e.Ppstaff)
                    .HasColumnName("PPStaff")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.SiteId).HasColumnName("SiteID");

                entity.Property(e => e.StrUser)
                    .HasColumnName("strUser")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.StrVoidReason)
                    .HasColumnName("strVoidReason")
                    .HasMaxLength(250)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}