// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class Tbl3psetup
    {
        public string SiteCode { get; set; }
        public int _pId { get; set; }
        public string Clinic { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Npi { get; set; }
        public string TaxId { get; set; }
        public string Medicaid { get; set; }
        public string City { get; set; }
        public string Drlname { get; set; }
        public string Drfname { get; set; }
        public string Drnpi { get; set; }
        public string ProviderAddress { get; set; }
        public string ProviderCity { get; set; }
        public string ProviderName { get; set; }
        public string ProviderPhone { get; set; }
        public string ProviderState { get; set; }
        public string ProviderZip { get; set; }
        public int? SiteId { get; set; }
        public string Clia { get; set; }
        public string StrDbnotes { get; set; }
        public string ProviderDesc { get; set; }
        public bool? BlHasPreloader { get; set; }
        public bool? IndividualNpi { get; set; }
        public string Taxonomy { get; set; }
        public string Sftpun { get; set; }
        public string Sftppw { get; set; }
        public int? RowChkSum { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}