// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class Tbl3pElig
    {
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        public bool RowState { get; set; }
        public DateTime LastModAt { get; set; }
        public int EId { get; set; }
        public int? EClt { get; set; }
        public string EPayer { get; set; }
        public DateTime? EDate { get; set; }
        public string EStaff { get; set; }
        public string EPost { get; set; }
        public string EResponse { get; set; }
        public string EStatus { get; set; }
        public string EFormat { get; set; }
        public string Filepath { get; set; }
        public string EElecstatus { get; set; }
        public string EstaffStatus { get; set; }
        public string EstaffNote { get; set; }
        public string EScan { get; set; }
        public int? EOrigid { get; set; }
        public DateTime? Pyeligcheck { get; set; }
    }
}