// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblAdmissionAssessmentDimensionSix
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int? AdmissionAssessmentId { get; set; }
        public int? StableHousingOfYourOwn { get; set; }
        public int? AreYouBehindOnYourRent { get; set; }
        public int? AreYouBehindOnYourUtility { get; set; }
        public int? DoYouHaveEnoughMoney { get; set; }
        public int? DoYouHaveJob { get; set; }
        public int? DoYouHaveSourceOfIncome { get; set; }
        public int? PeopleInHomeWhoDrinkAlcohol { get; set; }
        public int? DrugSellingCommonInYourNeighborhood { get; set; }
        public int? SafeFromPhysicalOrSexualAbuse { get; set; }
        public int? FamilyMembersWhoAreInRecovery { get; set; }
        public int? FamilyWhoYouCanCountOnToSupport { get; set; }
        public int? AnyPeerSupport { get; set; }
        public string Comments { get; set; }
        public int? DdldimensionSixScore { get; set; }
        public int? PreAdmissionId { get; set; }
        public string DimensionSixComments { get; set; }
        public string Dimension6Problems { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}