// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblAdmissionAssessmentDimensionFiveSubstanceUse
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int? AdmissionAssessmentId { get; set; }
        public int? HadAnOverdose { get; set; }
        public int? YourPhysicalHealthWorse { get; set; }
        public int? YourPhysicalMentalWorse { get; set; }
        public int? HaveYouCalled911 { get; set; }
        public int? SubstanceUseJeopardized { get; set; }
        public int? CausedProblemsAtYourJob { get; set; }
        public int? HavingAnyFinancialTroubles { get; set; }
        public int? DoesYourTemperTend { get; set; }
        public int? HaveYouEverBeenArrested { get; set; }
        public int? RiskOfBeingArrested { get; set; }
        public int? OpenOrPendingCourtCases { get; set; }
        public int? AreYouOnProbation { get; set; }
        public int? LegalCustodyOfYourChildren { get; set; }
        public int? AnyOpenCasesWitHlocalDepartment { get; set; }
        public int? ChildrenLiveInYourHome { get; set; }
        public string Comments { get; set; }
        public int? PreAdmissionId { get; set; }
        public string DimensionFiveComments { get; set; }
        public string Dimension5Problems { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}