// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BHG_DR_LIB.Models
{
    public partial class TblBriefAddictionMonitor
    {
        public int FId { get; set; }
        public string SiteCode { get; set; }
        public int FClinic { get; set; }
        public int FCltId { get; set; }
        public int RowState { get; set; }
        public DateTime? Date { get; set; }
        public string ClinicianText { get; set; }
        public string AdminList { get; set; }
        public string IntervalList { get; set; }
        public string UseCalc { get; set; }
        public string RiskCalc { get; set; }
        public string ProtectiveCalc { get; set; }
        public string Q1answerList { get; set; }
        public string Q2answerList { get; set; }
        public string Q3answerList { get; set; }
        public string Q4answerList { get; set; }
        public string Q5answerList { get; set; }
        public string Q6AnswerList { get; set; }
        public string Test { get; set; }
        public string Q1Answer { get; set; }
        public string Q2Answer { get; set; }
        public string Q3answer { get; set; }
        public string Q4answer { get; set; }
        public string Q5answer { get; set; }
        public string Q6answer { get; set; }
        public string Q7answerNumeric { get; set; }
        public string Q7aList { get; set; }
        public string Q7bList { get; set; }
        public string Q7cList { get; set; }
        public string Q7dList { get; set; }
        public string Q7eList { get; set; }
        public string Q7fList { get; set; }
        public string Q7gList { get; set; }
        public string Q8Answer { get; set; }
        public string Q9Answer { get; set; }
        public string Q10Answer { get; set; }
        public string Q11Answer { get; set; }
        public string Q12Answer { get; set; }
        public string Q13Answer { get; set; }
        public string Q14Answer { get; set; }
        public string Q15Answer { get; set; }
        public string Q15Answer1 { get; set; }
        public string Q15Answer2 { get; set; }
        public string Q16Answer { get; set; }
        public string Q17Answer { get; set; }
        public string Q14Answer2 { get; set; }
    }
}