// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_CheckIn", Schema = "pats")]
    public partial class TblCheckIn
    {
        [Key]
        [StringLength(50)]
        public string SiteCode { get; set; }
        [Key]
        [Column("ciID")]
        public int CiId { get; set; }
        public int RowChkSum { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [Required]
        [Column("ciCLTID")]
        [StringLength(50)]
        public string CiCltid { get; set; }
        [Key]
        [Column("ciDate", TypeName = "datetime")]
        public DateTime CiDate { get; set; }
        [Column("ciTIME", TypeName = "datetime")]
        public DateTime CiTime { get; set; }
        [Column("ciSERVEDdtm", TypeName = "datetime")]
        public DateTime? CiServeddtm { get; set; }
        [Column(TypeName = "decimal(10, 3)")]
        public decimal? MinutesWaited { get; set; }
        [Column("ciUSER")]
        [StringLength(50)]
        public string CiUser { get; set; }
        [Column("ciHOLD")]
        public bool? CiHold { get; set; }
        [Column("cicltm4id")]
        [StringLength(50)]
        public string Cicltm4id { get; set; }
        [Column("cicltName")]
        [StringLength(100)]
        public string CicltName { get; set; }
        [Column("ciCode")]
        [StringLength(50)]
        public string CiCode { get; set; }
        [Column("ciQueue")]
        [StringLength(50)]
        public string CiQueue { get; set; }
        [Column("ciServedStaff")]
        [StringLength(50)]
        public string CiServedStaff { get; set; }
        [Column("ciAmt")]
        public int? CiAmt { get; set; }
        [Column("ciDoses")]
        public int? CiDoses { get; set; }
        public DateTime? ciQUEUETIME { get; set; }
    }
}