using System;
using System.Collections.Generic;
using System.Text;

namespace BHG_DR_LIB.Models
{
    public partial class TblComprehensiveAssessmentForm
    {
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        public DateTime LastModAt { get; set; }
        public bool RowState { get; set; }
        public int Id { get; set; }
        public int DataFormId { get; set; }
        public int PreAdmissionId { get; set; }
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string ClientM4Id { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
        public int DDLActiveSubstanceUsers { get; set; }
        public int DDLCurrentJob { get; set; }
        public int DDLRelationshipStatus { get; set; }
        public int DDLWhatKindOfSchoolAttend { get; set; }
        public int DDLLiveWithYou { get; set; }
        public int DDLPreferredLanguage { get; set; }
        public int DDLEmploymentStatus { get; set; }
        public int DDLCheckMother { get; set; }
        public int DDLCheckFather { get; set; }
        public int DDLCheckSibling { get; set; }
        public int DDLCheckMaternalGrandmother { get; set; }
        public int DDLCheckMaternalGrandfather { get; set; }
        public int DDLCheckMaternalAunt { get; set; }
        public int DDLCheckMaternalUncle { get; set; }
        public int DDLCheckMaternalCousins { get; set; }
        public int DDLCheckPaternalGrandmother { get; set; }
        public int DDLCheckPaternalGrandfather { get; set; }
        public int DDLCheckPaternalAunt { get; set; }
        public int DDLCheckPaternalUncle { get; set; }
        public int DDLCheckPaternalCousins { get; set; }
        public int DDLHighestGradeCompleted { get; set; }
        public int DDLWhatBranch { get; set; }
        public int DDLTypeDischarge { get; set; }
        public int DDLGender { get; set; }
        public int DDLSexualOrientation { get; set; }
        public int DDLInfluenceDrugs { get; set; }
        public int DDLWhatBranchType { get; set; }
        public bool IsVeteransAdministration { get; set; }
        public bool IsPeerSupportMeetings { get; set; }
        public bool IsFriendsRecovery { get; set; }
        public bool IsCourtFines { get; set; }
        public bool IsOpenWarrants { get; set; }
        public bool IsOpenCourtCases { get; set; }
        public bool IsDrugTreatmentCourt { get; set; }
        public bool IsIncarcerated { get; set; }
        public bool IsArrested { get; set; }
        public bool IsSaferSexPractices { get; set; }
        public bool IsMakeYouUncomfortable { get; set; }
        public bool IsFeelingTraumatized { get; set; }
        public bool IsPertainingBeingLGBT { get; set; }
        public bool IsLGBT { get; set; }
        public bool IsCourtOrderedChildSupportPayments { get; set; }
        public bool IsArmedForces { get; set; }
        public bool IsTrainingActivities { get; set; }
        public bool IsEmploymentSituation { get; set; }
        public bool IsHighSchoolDiplomaGED { get; set; }
        public bool IsReadWriteEffectively { get; set; }
        public bool IsMainstreamClasses { get; set; }
        public bool IsHeldBackSchool { get; set; }
        public bool IsHaveAnyChildren { get; set; }
        public bool IsChildSupportPayments { get; set; }
        public bool IsCareOfFamilyMembers { get; set; }
        public bool IsAbuseNeglectGrowingUp { get; set; }
        public bool IsUnderstandEnglish { get; set; }
        public bool IsCountToSupportYou { get; set; }
        public bool IsCloseRelationship { get; set; }
        public bool IsDeployOverseas { get; set; }
        public bool CheckMother { get; set; }
        public bool CheckFather { get; set; }
        public bool CheckSibling { get; set; }
        public bool CheckMaternalGrandmother { get; set; }
        public bool CheckMaternalGrandfather { get; set; }
        public bool CheckMaternalAunt { get; set; }
        public bool CheckMaternalUncle { get; set; }
        public bool CheckMaternalCousins { get; set; }
        public bool CheckPaternalGrandmother { get; set; }
        public bool CheckPaternalGrandfather { get; set; }
        public bool CheckPaternalAunt { get; set; }
        public bool CheckPaternalUncle { get; set; }
        public bool CheckPaternalCousins { get; set; }
        public bool CheckVisuallyShowMe { get; set; }
        public bool CheckVerballyExplainItToMe { get; set; }
        public bool CheckPersonalExperience { get; set; }
        public bool CheckTactilelyHandsOn { get; set; }
        public bool CheckTalkItThrough { get; set; }
        public bool CheckNoOne { get; set; }
        public bool CheckImmediateFamily { get; set; }
        public bool CheckExtendedFamily { get; set; }
        public bool CheckCloseFriendsOnly { get; set; }
        public bool CheckFriends { get; set; }
        public bool CheckPeopleWork { get; set; }
        public bool CheckEveryone { get; set; }
        public bool CheckGamblingDisorder { get; set; }
        public bool CheckFoodOvereating { get; set; }
        public bool CheckEatingDisorders { get; set; }
        public bool CheckInternetAddiction { get; set; }
        public bool CheckSocialMediaAddiction { get; set; }
        public bool CheckLoveIntimacyDependence { get; set; }
        public bool CheckFamilyDisorder { get; set; }
        public bool CheckFriendsYourselfRecovery { get; set; }
        public bool CheckCoworkers { get; set; }
        public bool CheckMeetings { get; set; }
        public bool CheckOnline { get; set; }
        public bool IsDeleted { get; set; }
        public int HowLongHadCurrentJob { get; set; }
        public bool IsFullTimeStudent { get; set; }
        public bool IsPartTimeStudent { get; set; }
        public string Version { get; set; }
        public string ThoseWhoAreNotcisgender { get; set; }
        public bool CulturalPreferencesForYourTreatment { get; set; }
        public bool FamilyStruggledWithDrugAlcoholProblems { get; set; }
        public bool ExperiencedAnytraumaAbuseNeglect { get; set; }
        public bool PhysicalAbuseViolenceCaptivityOther { get; set; }
        public bool VerbalEmotionalFinancialAbuse { get; set; }
        public bool NeglectTraumaRelatedYourRace { get; set; }
        public bool SexualAbuseAssaultSexualExploitation { get; set; }
        public bool CurrentlyExperiencingAbuseNglectExploitation { get; set; }
        public int AnyDifficultyCopingWithTrauma { get; set; }
        public int HaveYouEverReceivedServices { get; set; }
        public bool ProbationorParole { get; set; }
        public bool SocialHistoryProblemsWithOther { get; set; }
        public bool FindSupportYourselfInRecoveryOther { get; set; }
        public bool RaceWhite { get; set; }
        public bool RaceBlack { get; set; }
        public bool RaceAmericanIndian { get; set; }
        public bool RaceAsian { get; set; }
        public bool RaceNativeHawaiian { get; set; }
        public bool RaceTwoorMore { get; set; }
        public bool RaceOther { get; set; }
        public string RaceOtherTxt { get; set; }
        public bool Hispanic { get; set; }
        public bool NonHispanic { get; set; }
        public int DDLTermsofGender { get; set; }
        public bool ObsevationofOthers { get; set; }
        public bool AffectedYourEmployment { get; set; }
        public bool PhysicalAbuse { get; set; }
        public bool SexualAbuse { get; set; }
        public bool VerbalAbuse { get; set; }
        public bool Neglect { get; set; }
        public bool Captivity { get; set; }
        public bool SexualExploitation { get; set; }
        public bool LaborExploitation { get; set; }
        public bool TraumaRelatedtoRace { get; set; }
        public bool TraumaOther { get; set; }
        public string SupportiveSexualOrientaion { get; set; }
        public string NotSupportiveSexualOrientaion { get; set; }
        public string SubstancesAffectedYourLife { get; set; }
        public bool AlwaysFollowsSaferSexPracices { get; set; }
        public bool HaveHighSchoolDiploma { get; set; }
    }
}
