// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_Connections", Schema = "ctrl")]
    public partial class TblConnections
    {
        [Key]
        [Column("ConID")]
        public int ConId { get; set; }
        public int ConType { get; set; }
        [Required]
        [StringLength(500)]
        public string ConStr { get; set; }
        [StringLength(50)]
        public string ConName { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(50)]
        public string LastModBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModAt { get; set; }
    }
}