// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblClinicalOpiateWithdrawalScale
    {
        public int FId { get; set; }
        public string SiteCode { get; set; }
        public int FCltId { get; set; }
        public bool RowState { get; set; }
        public int RowChkSum { get; set; }
        public DateTime LastModAt { get; set; }
        public string CompletedName { get; set; }
        public string CombinedScore { get; set; }
        public string AssessDate { get; set; }
        public string ReasonAssessList { get; set; }
        public string RestingPulseNum { get; set; }
        public string GiupsetNum { get; set; }
        public string SweatNum { get; set; }
        public string TremorNum { get; set; }
        public string RestlessNum { get; set; }
        public string YawnNum { get; set; }
        public string PupilNum { get; set; }
        public string AnxNum { get; set; }
        public string BoneNum { get; set; }
        public string GooseNum { get; set; }
        public string RunnyNum { get; set; }
        public string GenevaTest { get; set; }
        public string TimeAmpm { get; set; }
        public string AssesstimeText { get; set; }
    }
}