// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_CtrlSiteTableInit", Schema = "tsk")]
    public partial class TblCtrlSiteTableInit
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        [Key]
        [StringLength(100)]
        public string TableName { get; set; }
        [Required]
        [StringLength(50)]
        public string DateField { get; set; }
        public bool DateNulls { get; set; }
        [Column(TypeName = "date")]
        public DateTime? MinDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? InitRunDate { get; set; }
    }
}