// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_CtrlSiteTableInitLog", Schema = "tsk")]
    public partial class TblCtrlSiteTableInitLog
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        [Key]
        [StringLength(100)]
        public string TableName { get; set; }
        [Key]
        [Column(TypeName = "datetime")]
        public DateTime WorkDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RunDate { get; set; }
        public int? TranRows { get; set; }
    }
}