// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_Codes", Schema = "pats")]
    public partial class TblCodes
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [Key]
        [Column("cdeID")]
        public int CdeId { get; set; }
        [Column("cdeGroup")]
        [StringLength(50)]
        public string CdeGroup { get; set; }
        [Column("cdeDesc")]
        [StringLength(800)]
        public string CdeDesc { get; set; }
        [Column("cdeBillable")]
        public bool? CdeBillable { get; set; }
        [Column("cdeUA")]
        public bool? CdeUa { get; set; }
        [Column("cdeIntAmt")]
        public int? CdeIntAmt { get; set; }
        [Column("cdeLiquid")]
        public bool? CdeLiquid { get; set; }
        [Column("cdeSTAFFCODE")]
        public bool? CdeStaffcode { get; set; }
        [Column("cdeFUND")]
        [StringLength(50)]
        public string CdeFund { get; set; }
        [Column("cdeMODAlity")]
        [StringLength(50)]
        public string CdeModality { get; set; }
        [Column("cdeDRUGFREE")]
        public bool? CdeDrugfree { get; set; }
        [Column("cdePROVIDER")]
        [StringLength(4)]
        public string CdeProvider { get; set; }
        [Column("cdeSiteNum")]
        [StringLength(2)]
        public string CdeSiteNum { get; set; }
        [Column("rowguid")]
        public Guid? Rowguid { get; set; }
        [Column("cdeBillableResidential")]
        public bool? CdeBillableResidential { get; set; }
        [Column("cdeServiceSetting")]
        [StringLength(2)]
        public string CdeServiceSetting { get; set; }
        [Column("cdeDischargeType")]
        [StringLength(10)]
        public string CdeDischargeType { get; set; }
        [Column("cdeSigRequired")]
        public bool? CdeSigRequired { get; set; }
        [Column("cdeResidential")]
        public bool? CdeResidential { get; set; }
        [Column("cdeAllowOverlap")]
        public bool? CdeAllowOverlap { get; set; }
        [Column("duiAMT", TypeName = "decimal(18, 0)")]
        public decimal? DuiAmt { get; set; }
        [Column("duiHourRate", TypeName = "decimal(18, 2)")]
        public decimal? DuiHourRate { get; set; }
        [Column("blDEFAULT")]
        public bool? BlDefault { get; set; }
        public int? WeeklyFee { get; set; }
        public bool? MustHaveBilling { get; set; }
        public bool? Suboxoneprog { get; set; }
        [Column("cdeInsurance")]
        public bool? CdeInsurance { get; set; }
        [Column(TypeName = "money")]
        public decimal? DefRate { get; set; }
        [Column("SiteID")]
        public int? SiteId { get; set; }
        [Column("cdelblcolor")]
        [StringLength(25)]
        public string Cdelblcolor { get; set; }
        [Column("cde3pdonotbill")]
        public bool? Cde3pdonotbill { get; set; }
        [Column("cde3pPOSoverride")]
        [StringLength(10)]
        public string Cde3pPosoverride { get; set; }
        public bool? IsPrescreening { get; set; }
        [Column("OBAT")]
        public bool? Obat { get; set; }
        public bool? ReqAuth { get; set; }
        public bool? IntakeProg { get; set; }
    }
}