// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_ClaimLineItem", Schema = "pats")]
    public partial class TblClaimLineItem
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        [Key]
        [Column("tpcliID")]
        public int TpcliId { get; set; }
        public int RowChkSum { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [Column("tpcliTPCID")]
        public int? TpcliTpcid { get; set; }
        [Column("tpcliDtmService", TypeName = "datetime")]
        public DateTime? TpcliDtmService { get; set; }
        [Column("tpcliTxtService")]
        [StringLength(100)]
        public string TpcliTxtService { get; set; }
        [Column("tpcliIntUnits")]
        public int? TpcliIntUnits { get; set; }
        [Column("tpcliDtmAdded", TypeName = "datetime")]
        public DateTime? TpcliDtmAdded { get; set; }
        [Column("tpcliStrAdded")]
        [StringLength(100)]
        public string TpcliStrAdded { get; set; }
        [Column("tpcliAmtCharge", TypeName = "money")]
        public decimal? TpcliAmtCharge { get; set; }
        [Column("tpcliStrCPT")]
        [StringLength(100)]
        public string TpcliStrCpt { get; set; }
        [Column("tpcliStrModifier")]
        [StringLength(100)]
        public string TpcliStrModifier { get; set; }
        [Column("tpcliStrNDC")]
        [StringLength(100)]
        public string TpcliStrNdc { get; set; }
        [Column("tpcliStrPOS")]
        [StringLength(100)]
        public string TpcliStrPos { get; set; }
        [Column("tpcliIntDx1")]
        public int? TpcliIntDx1 { get; set; }
        [Column("tpcliIntDx2")]
        public int? TpcliIntDx2 { get; set; }
        [Column("tpcliIntDx3")]
        public int? TpcliIntDx3 { get; set; }
        [Column("tpcliIntDx4")]
        public int? TpcliIntDx4 { get; set; }
        [Column("tpcliDiagnosis")]
        [StringLength(50)]
        public string TpcliDiagnosis { get; set; }
        [Column("tpcliDSID")]
        public int? TpcliDsid { get; set; }
        [Column("tpcliPayerClaimID")]
        [StringLength(50)]
        public string TpcliPayerClaimId { get; set; }
        [Column("tpcliProviderId")]
        [StringLength(50)]
        public string TpcliProviderId { get; set; }
        [Column("tpcliUNITFEE", TypeName = "money")]
        public decimal? TpcliUnitfee { get; set; }
        [Column("tpcliVOID")]
        public bool? TpcliVoid { get; set; }
        [Column("tpclivoidDT", TypeName = "date")]
        public DateTime? TpclivoidDt { get; set; }
        [Column("tpclivoidUSER")]
        [StringLength(50)]
        public string TpclivoidUser { get; set; }
        [Column("tpcliDtmServiceTo", TypeName = "datetime")]
        public DateTime? TpcliDtmServiceTo { get; set; }
        [Column("tpcliIntMg")]
        public int? TpcliIntMg { get; set; }
        [Column("tpcliDBnotes")]
        [StringLength(1000)]
        public string TpcliDbnotes { get; set; }
        public bool? RowState { get; set; }
    }
}