// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_ClientDemo2", Schema = "pats")]
    public partial class TblClientDemo2
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        [Key]
        [Column("clientID")]
        public int ClientId { get; set; }
        public int? RowChkSum { get; set; }
        [StringLength(100)]
        public string Counselor { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [StringLength(50)]
        public string Prog { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateAdded { get; set; }
        [StringLength(50)]
        public string Amount { get; set; }
        [StringLength(50)]
        public string Freq { get; set; }
        [Column("DOW1")]
        [StringLength(50)]
        public string Dow1 { get; set; }
        [Column("DOW2")]
        [StringLength(50)]
        public string Dow2 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NextBill { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastBill { get; set; }
        [Column("NextTP", TypeName = "datetime")]
        public DateTime? NextTp { get; set; }
        [Column("PhysTB", TypeName = "datetime")]
        public DateTime? PhysTb { get; set; }
        public bool? Monthly { get; set; }
        [Column("BOTTLES")]
        public short? Bottles { get; set; }
        [Column("PICPATH")]
        [StringLength(150)]
        public string Picpath { get; set; }
        [Column("REMARKS", TypeName = "ntext")]
        public string Remarks { get; set; }
        [Column("RIN")]
        [StringLength(50)]
        public string Rin { get; set; }
        [Column("ETH")]
        [StringLength(50)]
        public string Eth { get; set; }
        public bool? Medicaid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EnrollDate { get; set; }
        [Column("BULK")]
        public bool? Bulk { get; set; }
        [Column("STAND")]
        public bool? Stand { get; set; }
        [Column("SPECIAL")]
        [StringLength(50)]
        public string Special { get; set; }
        [Column("dtLastUA")]
        [StringLength(25)]
        public string DtLastUa { get; set; }
        [Column("AMSID")]
        [StringLength(100)]
        public string Amsid { get; set; }
        [Column("NOCENSUS")]
        public bool? Nocensus { get; set; }
        [Column("CHANGEUSER")]
        [StringLength(100)]
        public string Changeuser { get; set; }
        [Column(TypeName = "numeric(18, 0)")]
        public decimal? RepOldClient { get; set; }
        [Column("UAWeekly", TypeName = "datetime")]
        public DateTime? Uaweekly { get; set; }
        public bool? OptIn { get; set; }
        [Column("credit")]
        public int? Credit { get; set; }
        [Column("CONTTXDT", TypeName = "date")]
        public DateTime? Conttxdt { get; set; }
        [Column("INS")]
        [StringLength(50)]
        public string Ins { get; set; }
        [Column("RISK")]
        [StringLength(50)]
        public string Risk { get; set; }
        [StringLength(150)]
        public string Clt3pBack { get; set; }
        [StringLength(150)]
        public string Clt3pfront { get; set; }
        [Column("BiWeeklyUA")]
        public bool? BiWeeklyUa { get; set; }
        public string NurseNotes { get; set; }
        [Column("PANEL")]
        [StringLength(100)]
        public string Panel { get; set; }
        [Column("PAYDAY")]
        [StringLength(50)]
        public string Payday { get; set; }
        public byte[] FingerPrint1 { get; set; }
        public byte[] FingerPrint2 { get; set; }
        [StringLength(175)]
        public string Clt911Name { get; set; }
        [Column("Clt911PH")]
        [StringLength(50)]
        public string Clt911Ph { get; set; }
        [StringLength(75)]
        public string Clt911Relation { get; set; }
        public bool? HolidayPickup { get; set; }
        [Column("ddapid")]
        public long? Ddapid { get; set; }
        public long? ProvClient { get; set; }
        [Column("ProvClientID")]
        public long? ProvClientId { get; set; }
        [Column(TypeName = "money")]
        public decimal? BackFee { get; set; }
        [Column("isSalesForceSync")]
        public int? IsSalesForceSync { get; set; }
        [StringLength(250)]
        public string SalesForceId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModAt { get; set; }
        public int? RowState { get; set; }
    }
}