// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BHG_DR_LIB.Models
{
    public partial class TblConsents_Phc
    {
        public int Cid { get; set; }
        public string CName { get; set; }
        public bool? ClientSig { get; set; }
        public bool? StaffSig { get; set; }
        public bool? SupervisorSig { get; set; }
        public bool? PhysicianSig { get; set; }
        public bool? NurseSig { get; set; }
        public bool? GuardianSig { get; set; }
        public bool? DenyGuardian { get; set; }
        public bool? CDeleted { get; set; }
        public int? Cdays { get; set; }
        public bool? Bac { get; set; }
        public bool? Ted { get; set; }
        public bool? AdminnurseSig { get; set; }
        public bool? Blrecurr { get; set; }
        public bool? IsMhform { get; set; }
    }
}