// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_DartsSrv_2015", Schema = "pats")]
    public partial class TblDartsSrv_2015
    {
        [Key]
        [Column("dsID")]
        public int DsId { get; set; }
        [Column("dsClt")]
        public int DsClt { get; set; }
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        [Column("dsDIM1")]
        public bool? DsDim1 { get; set; }
        [Column("dsDIM2")]
        public bool? DsDim2 { get; set; }
        [Column("dsDIM3")]
        public bool? DsDim3 { get; set; }
        [Column("dsDIM4")]
        public bool? DsDim4 { get; set; }
        [Column("dsDIM5")]
        public bool? DsDim5 { get; set; }
        [Column("dsDIM6")]
        public bool? DsDim6 { get; set; }
        [Column("dsTxtSrv")]
        [StringLength(100)]
        public string DsTxtSrv { get; set; }
        [Column("dsDtStart", TypeName = "datetime")]
        public DateTime? DsDtStart { get; set; }
        [Column("dsDtEnd", TypeName = "datetime")]
        public DateTime? DsDtEnd { get; set; }
        [Column("dsTxtType")]
        [StringLength(50)]
        public string DsTxtType { get; set; }
        [Column("dsdblUnits")]
        public double? DsdblUnits { get; set; }
        [Column("dsNoteID")]
        public int? DsNoteId { get; set; }
        [Column("dsDtAdded", TypeName = "datetime")]
        public DateTime? DsDtAdded { get; set; }
        [Column("dstxtStaff")]
        [StringLength(100)]
        public string DstxtStaff { get; set; }
        [Column("dstxtNote", TypeName = "ntext")]
        public string DstxtNote { get; set; }
        [Column("dsRTBNOTE", TypeName = "ntext")]
        public string DsRtbnote { get; set; }
        [Column("DSbilled", TypeName = "datetime")]
        public DateTime? Dsbilled { get; set; }
        [Column("dsGROUPNUM")]
        [StringLength(50)]
        public string DsGroupnum { get; set; }
        [Column("dsPROGRAM")]
        [StringLength(50)]
        public string DsProgram { get; set; }
        [Column("dsUpdate", TypeName = "datetime")]
        public DateTime? DsUpdate { get; set; }
        [Column("dsUPDATEStaff")]
        [StringLength(50)]
        public string DsUpdatestaff { get; set; }
        //[Column("upsize_ts")]
        //public byte[] UpsizeTs { get; set; }
        [Column("dsInvalidatedOn", TypeName = "datetime")]
        public DateTime? DsInvalidatedOn { get; set; }
        [Column("dsError")]
        [StringLength(4000)]
        public string DsError { get; set; }
        [Column("dsTxtHIV")]
        [StringLength(50)]
        public string DsTxtHiv { get; set; }
        [Column("dsDartsGroup")]
        public int? DsDartsGroup { get; set; }
        [Column("repOldSrv", TypeName = "numeric(18, 0)")]
        public decimal? RepOldSrv { get; set; }
        [Column("dsSignature", TypeName = "ntext")]
        public string DsSignature { get; set; }
        [Column("dsSigDate", TypeName = "datetime")]
        public DateTime? DsSigDate { get; set; }
        [Column("dssigdateCOSIGN", TypeName = "datetime")]
        public DateTime? DssigdateCosign { get; set; }
        [Column("dssignatureCOSIGN", TypeName = "ntext")]
        public string DssignatureCosign { get; set; }
        [Column("dsSigUser")]
        [StringLength(50)]
        public string DsSigUser { get; set; }
        [Column("dsSigUserCosign")]
        [StringLength(50)]
        public string DsSigUserCosign { get; set; }
        [Column("dsSIGCLT", TypeName = "ntext")]
        public string DsSigclt { get; set; }
        [Column("dsSIGCLTDATE", TypeName = "datetime")]
        public DateTime? DsSigcltdate { get; set; }
        [Column("dsSIGCLTUSER")]
        [StringLength(50)]
        public string DsSigcltuser { get; set; }
        [Column("dsAPTID")]
        public int? DsAptid { get; set; }
        [Column("dsuncharted")]
        public bool? Dsuncharted { get; set; }
        [Column("dsTxDim1")]
        public int? DsTxDim1 { get; set; }
        [Column("dsTxDim2")]
        public int? DsTxDim2 { get; set; }
        [Column("dsTxDim3")]
        public int? DsTxDim3 { get; set; }
        [Column("dsTxDim4")]
        public int? DsTxDim4 { get; set; }
        [Column("dsTxDim5")]
        public int? DsTxDim5 { get; set; }
        [Column("dsTxDim6")]
        public int? DsTxDim6 { get; set; }
        [Column("dsDIAG")]
        [StringLength(100)]
        public string DsDiag { get; set; }
        [Column("dsArea")]
        [StringLength(100)]
        public string DsArea { get; set; }
        [Column("dsGroupDefaultNote")]
        public bool? DsGroupDefaultNote { get; set; }
        [Column("dsGroupEnd", TypeName = "datetime")]
        public DateTime? DsGroupEnd { get; set; }
        [Column("dsGroupIdentity")]
        public int? DsGroupIdentity { get; set; }
        [Column("dsGroupStart", TypeName = "datetime")]
        public DateTime? DsGroupStart { get; set; }
        [Column("dsDIAG10")]
        [StringLength(100)]
        public string DsDiag10 { get; set; }
        [Column("SiteID")]
        public int? SiteId { get; set; }
        [Column("dsDBnotes")]
        [StringLength(250)]
        public string DsDbnotes { get; set; }
        [Column("dsSigCltImg")]
        public byte[] DsSigCltImg { get; set; }
        [Column("dsSignatureCoSignImg")]
        public byte[] DsSignatureCoSignImg { get; set; }
        [Column("dsSignatureIMG")]
        public byte[] DsSignatureImg { get; set; }
        [Column("MG")]
        public double? Mg { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModAt { get; set; }
    }
}