// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblEandMformPregnancy
    {
        public string SiteCode { get; set; }
        public int EandMformId { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? ClientId { get; set; }
        public int? DataFormId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool? Isdeleted { get; set; }
        public DateTime? FormDate { get; set; }
        public int? ServiceId { get; set; }
        public string Context { get; set; }
        public string Version { get; set; }
        public int? Ddltrimester { get; set; }
        public string DoseTxt { get; set; }
        public string MgTxt { get; set; }
        public string DoseStabilityTxt { get; set; }
        public string SignsTxt { get; set; }
        public bool? Bleeding { get; set; }
        public bool? Contraction { get; set; }
        public bool? NauseaVomiting { get; set; }
        public string PregnancyOtherTxt { get; set; }
        public string MedicationsTxt { get; set; }
        public string PrenatalVitaminsTxt { get; set; }
        public string AllergiesTxt { get; set; }
        public string ChangesInRoutineTxt { get; set; }
        public int? UdsradioBtn { get; set; }
        public int? SmokerRadioBtn { get; set; }
        public string IllicitDrugTxt { get; set; }
        public string NoOfPregnanciesTxt { get; set; }
        public string DeliveriesTxt { get; set; }
        public DateTime? DateOfLastOb { get; set; }
        public string NameofObtxt { get; set; }
        public string PregnancyCommentsTxt { get; set; }
        public string Wttxt { get; set; }
        public string GravidaTxt { get; set; }
        public string ParaTxt { get; set; }
        public string Provider { get; set; }
        public bool? PrenatalCare { get; set; }
        public bool? ReviewedandAcknowledged { get; set; }
        public bool? NapregnancyGrid { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}