// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_Enrollment", Schema = "pats")]
    public partial class TblEnrollment
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        [Column("cltID")]
        public int? CltId { get; set; }
        public bool? RowState { get; set; }
        [StringLength(100)]
        public string Program { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EnrollDate { get; set; }
        [StringLength(100)]
        public string EnrollReasonCode { get; set; }
        [StringLength(300)]
        public string EnrollReasonText { get; set; }
        [StringLength(100)]
        public string DischargeReasonCode { get; set; }
        [StringLength(300)]
        public string DischargeReasonText { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DischargeDate { get; set; }
        [Column("strStaff")]
        [StringLength(50)]
        public string StrStaff { get; set; }
        public bool? Transfer { get; set; }
        //[Column("upsize_ts")]
        //public byte[] UpsizeTs { get; set; }
        [Column("ParentEnrollID")]
        public int? ParentEnrollId { get; set; }
        [Column("NoDarts_Enroll")]
        public bool? NoDartsEnroll { get; set; }
        [Column("NoDarts_Discharge")]
        public bool? NoDartsDischarge { get; set; }
        [Column("repOldEnroll", TypeName = "numeric(18, 0)")]
        public decimal? RepOldEnroll { get; set; }
        [Column("DASAreason")]
        [StringLength(1)]
        public string Dasareason { get; set; }
        [Column("dtLastContact", TypeName = "datetime")]
        public DateTime? DtLastContact { get; set; }
        [Column("strArrests")]
        [StringLength(2)]
        public string StrArrests { get; set; }
        [Column("strBaby")]
        [StringLength(1)]
        public string StrBaby { get; set; }
        [Column("strBabyDF")]
        [StringLength(1)]
        public string StrBabyDf { get; set; }
        [Column("strEduc")]
        [StringLength(2)]
        public string StrEduc { get; set; }
        [Column("strEmpStat")]
        [StringLength(1)]
        public string StrEmpStat { get; set; }
        [Column("strLiving")]
        [StringLength(1)]
        public string StrLiving { get; set; }
        [Column("strNILF")]
        [StringLength(1)]
        public string StrNilf { get; set; }
        [Column("strPriFreq")]
        [StringLength(1)]
        public string StrPriFreq { get; set; }
        [Column("strPriProb")]
        [StringLength(2)]
        public string StrPriProb { get; set; }
        [Column("strSecFreq")]
        [StringLength(1)]
        public string StrSecFreq { get; set; }
        [Column("strSecProb")]
        [StringLength(2)]
        public string StrSecProb { get; set; }
        [Column("strSelfHelp")]
        [StringLength(1)]
        public string StrSelfHelp { get; set; }
        [Column("strSelfHelpDet")]
        [StringLength(2)]
        public string StrSelfHelpDet { get; set; }
        [Column("strSuppInt")]
        [StringLength(1)]
        public string StrSuppInt { get; set; }
        [Column("strTerFreq")]
        [StringLength(1)]
        public string StrTerFreq { get; set; }
        [Column("strTerProb")]
        [StringLength(2)]
        public string StrTerProb { get; set; }
        [Column("strSchoolJobTraining")]
        [StringLength(1)]
        public string StrSchoolJobTraining { get; set; }
        [StringLength(100)]
        public string Counselor { get; set; }
        [StringLength(100)]
        public string DischargeSubReasonCode { get; set; }
        [StringLength(100)]
        public string EnrollSubReasonCode { get; set; }
        public bool? OnDemand { get; set; }
        [Column("physician")]
        [StringLength(100)]
        public string Physician { get; set; }
        [Column("SiteID")]
        public int? SiteId { get; set; }
        
        [Column("MODULE")]
        [StringLength(100)]
        public string Module { get; set; }
        
        [Column("MODULENote")]
        [StringLength(30)]
        public string Modulenote { get; set; }
        [Column("dischargeIncome")]
        [StringLength(50)]
        public string DischargeIncome { get; set; }
        [Column("intakeIncome")]
        [StringLength(50)]
        public string IntakeIncome { get; set; }
        [Column("strDBnotes")]
        [StringLength(100)]
        public string StrDbnotes { get; set; }
        [Column("deleterecord")]
        [StringLength(10)]
        public string Deleterecord { get; set; }
        [Column("dtLastQuery", TypeName = "datetime")]
        public DateTime? DtLastQuery { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModAt { get; set; }
        public string Modality { get; set; }
        public string TreatmentLevel { get; set; }
    }
}