// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblEandMformMdm
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? ClientId { get; set; }
        public int? DataFormId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool? Isdeleted { get; set; }
        public DateTime? FormDate { get; set; }
        public int? ServiceId { get; set; }
        public string Context { get; set; }
        public string Version { get; set; }
        public DateTime? MedicalProviderSignatureDate { get; set; }
        public string MedicalProviderSignatureBy { get; set; }
    }
}