// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_FeeSched", Schema = "pats")]
    public partial class TblFeeSched
    {
        [Key]
        [Column("fsID")]
        public int FsId { get; set; }
        [Key]
        [Column("fsSite")]
        public string FsSite { get; set; }
        public int RowChkSum { get; set; }
        [Column("fsPAYID")]
        [StringLength(500)]
        public string FsPayid { get; set; }
        [Column("dsSERVICE")]
        [StringLength(100)]
        public string DsService { get; set; }
        [Column("CPTCODE")]
        [StringLength(50)]
        public string Cptcode { get; set; }
        [Column(TypeName = "money")]
        public decimal? Fee { get; set; }
        [Column(TypeName = "money")]
        public decimal? Contractual { get; set; }
        public bool? Datespan { get; set; }
        public bool? GroupTogether { get; set; }
        [StringLength(100)]
        public string Modifier { get; set; }
        [StringLength(50)]
        public string UnitMin { get; set; }
        public bool? ProviderBill { get; set; }
        public bool? CoAble { get; set; }
        [Column("defaultWeekFee")]
        public bool? DefaultWeekFee { get; set; }
        [StringLength(3)]
        public string RevCode { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Startdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Enddate { get; set; }
        [Column("POS")]
        [StringLength(50)]
        public string Pos { get; set; }
        public bool? AttendingBill { get; set; }
        [Column("pay2310A")]
        public bool? Pay2310A { get; set; }
        [Column("pay2310C")]
        public bool? Pay2310C { get; set; }
        public bool? ReferredByAttending { get; set; }
        public bool? BillAttendingOrder { get; set; }
        public bool? BillOrderDoctor { get; set; }
        [Column("fsMasterId")]
        public int? FsMasterId { get; set; }
        [StringLength(200)]
        public string Notes1 { get; set; }
        [StringLength(200)]
        public string Notes2 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModAt { get; set; }
        public bool? IsActive { get; set; }
    }
}