// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BHG_DR_LIB.Models
{
    public partial class TblFormsSammsclient
    {
        public string SiteCode { get; set; }
        public int Fscsid { get; set; }
        public DateTime? FscDate { get; set; }
        public int? FscCltid { get; set; }
        public int? Fscsite { get; set; }
        public string FscFormid { get; set; }
        public string Fscform { get; set; }
        public string ClientSig { get; set; }
        public string StaffSig { get; set; }
        public string SupervisorSig { get; set; }
        public string PhysicianSig { get; set; }
        public DateTime? ClientSigDate { get; set; }
        public DateTime? StaffSigDate { get; set; }
        public DateTime? SupervisorSigDate { get; set; }
        public DateTime? PhysicianSigDate { get; set; }
        public string Doctext { get; set; }
        public string NurseSig { get; set; }
        public string NurseSigBy { get; set; }
        public DateTime? NurseSigDate { get; set; }
        public string PhysicianSigBy { get; set; }
        public string StaffSigBy { get; set; }
        public string SupervisorSigBy { get; set; }
        public DateTime? DoctextEditDate { get; set; }
        public string DoctextEditBy { get; set; }
        public string GuardianSig { get; set; }
        public string GuardianSigBy { get; set; }
        public DateTime? GuardianSigDate { get; set; }
        public int? ScanLink { get; set; }
        public bool? ScanReplace { get; set; }
        public byte[] ClientSigImg { get; set; }
        public byte[] GuardianSigImg { get; set; }
        public byte[] NurseSigImg { get; set; }
        public byte[] PhysicianSigImg { get; set; }
        public byte[] StaffSigImg { get; set; }
        public byte[] SupervisorSigImg { get; set; }
        public bool? Bac { get; set; }
        public string AdminNurseSig { get; set; }
        public string AdminNurseSigBy { get; set; }
        public DateTime? AdminnurseSigDate { get; set; }
        public byte[] AdminnurseSigImg { get; set; }
        public DateTime? LastModAt { get; set; }
        public int? RowChkSum { get; set; }
        public int? RowState { get; set; }
    }
}