// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblFmp
    {
        public string SiteCode { get; set; }
        public int FmpId { get; set; }
        public int? FmpLngClt { get; set; }
        public DateTime? FmpDtStart { get; set; }
        public DateTime? FmpDtProjEnd { get; set; }
        public DateTime? FmpDtEnd { get; set; }
        public int? FmpIntRate { get; set; }
        public string FmpStrReason { get; set; }
        public string FmpStrDesc { get; set; }
        public DateTime? FmpDtAdded { get; set; }
        public string FmpStrUserAdded { get; set; }
        public DateTime? FmpDtEnded { get; set; }
        public string FmpStrUserEnded { get; set; }
        public string FmPendtext { get; set; }
        public string AtriskType { get; set; }
        public bool? RowState { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}