// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblForms2Process
    {
        public int FormProcessId { get; set; }
        public bool Enabled { get; set; }
        public bool RowState { get; set; }
        public bool DateFilterEnabled { get; set; }
        public string FormName { get; set; }
        public string TableName { get; set; }
        public string CompletedBy { get; set; }
        public string Counselor { get; set; }
        public string Doctor { get; set; }
        public string MedicalProvider { get; set; }
        public string Patient { get; set; }
        public string Provider { get; set; }
        public string Requestor { get; set; }
        public string Staff { get; set; }
        public string Supervisor { get; set; }
        public int? Prefix { get; set; }
        public string CreatedOn { get; set; }
        public string ModifiedOn { get; set; }
    }
}