// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_GlobalPayor", Schema = "pats")]
    public partial class TblGlobalPayor
    {
        [Key]
        public string SiteCode { get; set; }
        [Key]
        [Column("payID")]
        public int PayId { get; set; }
        public int? RowChkSum { get; set; }
        [Column("payNAME")]
        [StringLength(150)]
        public string PayName { get; set; }
        [StringLength(150)]
        public string PayAddress { get; set; }
        [Column("payCITY")]
        [StringLength(50)]
        public string PayCity { get; set; }
        [Column("payST")]
        [StringLength(50)]
        public string PaySt { get; set; }
        [StringLength(50)]
        public string Payzip { get; set; }
        [Column("payPH")]
        [StringLength(50)]
        public string PayPh { get; set; }
        [Column("payFX")]
        [StringLength(50)]
        public string PayFx { get; set; }
        [Column("payNOTE")]
        public string PayNote { get; set; }
        [Column("payDEFAULTSUBMIT")]
        [StringLength(50)]
        public string PayDefaultsubmit { get; set; }
        [Column("payAUTHFORMAT")]
        [StringLength(50)]
        public string PayAuthformat { get; set; }
        [Column("payCLMNUM")]
        public int? PayClmnum { get; set; }
        [Column("pay835")]
        public bool? Pay835 { get; set; }
        [Column("paySubmitType")]
        [StringLength(100)]
        public string PaySubmitType { get; set; }
        [Column("payBILLAMT", TypeName = "money")]
        public decimal? PayBillamt { get; set; }
        [Column("payDOSETYPE")]
        [StringLength(50)]
        public string PayDosetype { get; set; }
        [StringLength(50)]
        public string PayerNumber { get; set; }
        [Column("payaddressjoin")]
        [StringLength(150)]
        public string Payaddressjoin { get; set; }
        public int? PayCheckAuth { get; set; }
        [StringLength(50)]
        public string Payclass { get; set; }
        [Column("payINDfreq")]
        [StringLength(50)]
        public string PayIndfreq { get; set; }
        [Column("payindRATE", TypeName = "money")]
        public decimal? PayindRate { get; set; }
        [Column("payINDUNIT")]
        public int? PayIndunit { get; set; }
        [Column("PayLabelNAME")]
        [StringLength(100)]
        public string PayLabelName { get; set; }
        [Column("paynamejoin")]
        [StringLength(150)]
        public string Paynamejoin { get; set; }
        [Column("payOVERRIDE")]
        [StringLength(100)]
        public string PayOverride { get; set; }
        [Column("payPOS")]
        [StringLength(50)]
        public string PayPos { get; set; }
        [Column("payregion")]
        [StringLength(50)]
        public string Payregion { get; set; }
        [Column("PayREQAUTH")]
        public bool? PayReqauth { get; set; }
        [Column("paysig")]
        public bool? Paysig { get; set; }
        [Column("payGLclass")]
        [StringLength(50)]
        public string PayGlclass { get; set; }
        [Column("payLAB")]
        public bool? PayLab { get; set; }
        public bool? NoClaimLevelRendering { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Enddate { get; set; }
        [Column("revcode")]
        [StringLength(50)]
        public string Revcode { get; set; }
        [Column(TypeName = "date")]
        public DateTime? StartDate { get; set; }
        [Column("pay2310A")]
        public bool? Pay2310A { get; set; }
        [Column("pay2310B")]
        public bool? Pay2310B { get; set; }
        [Column("pay2310C")]
        public bool? Pay2310C { get; set; }
        public bool? SupressSecondary { get; set; }
        [Column("AltTaxID")]
        [StringLength(10)]
        public string AltTaxId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastModAt { get; set; }
        public int? RowState { get; set; }
    }
}