// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_LocationCons", Schema = "ctrl")]
    public partial class TblLocationCons
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        [Key]
        [Column(TypeName = "datetime")]
        public DateTime EffectiveDate { get; set; }
        [Column("ConnectionID")]
        public int ConnectionId { get; set; }
        [Required]
        [Column("dbName")]
        [StringLength(255)]
        public string DbName { get; set; }
        [Key]
        public long ActionKey { get; set; }
        [StringLength(5)]
        public string SchemaVersion { get; set; }
    }
}