// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblLabresultdetail
    {
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        public DateTime LastModAt { get; set; }
        public int LabrdId { get; set; }
        public int? LabrdRecId { get; set; }
        public string LabrdResult { get; set; }
        public string Labdetail { get; set; }
        public string LabrdFullNote { get; set; }
        public string LabrdKey { get; set; }
        public string LabrdNote { get; set; }
        public bool? LabrdRx { get; set; }
    }
}