// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BHG_DR_LIB.Models
{
    public partial class TblPayerClient
    {
        public long Pcid { get; set; }
        public int RowChkSum { get; set; }
        public string SiteCode { get; set; }
        public int PyId { get; set; }
        public string PyPayerid { get; set; }
        public string PyPayertype { get; set; }
        public string PySubsid { get; set; }
        public string PyGroup { get; set; }
        public string PyAuth { get; set; }
        public DateTime PyStart { get; set; }
        public DateTime? PyEnd { get; set; }
        public int PyCltid { get; set; }
        public bool? PyActive { get; set; }
        public string Pyadd { get; set; }
        public string Pycity { get; set; }
        public DateTime? PyDob { get; set; }
        public string Pyfirst { get; set; }
        public string Pylast { get; set; }
        public string PyPhone { get; set; }
        public bool? Pysame { get; set; }
        public string Pystate { get; set; }
        public string Pyzip { get; set; }
        public DateTime? PyAddDate { get; set; }
        public string PyAddUser { get; set; }
        public string PyBack { get; set; }
        public string Pybupe { get; set; }
        public decimal? Pycoins { get; set; }
        public decimal? Pycopay { get; set; }
        public string Pyded { get; set; }
        public decimal? Pydeduct { get; set; }
        public decimal? Pydeductleft { get; set; }
        public DateTime? PyEligCheck { get; set; }
        public string PyEligUser { get; set; }
        public string Pyfront { get; set; }
        public string Pymmt { get; set; }
        public string Pyout { get; set; }
        public DateTime? PyProjectedEnd { get; set; }
        public string TempSavePayer { get; set; }
        public string PyBasicNum { get; set; }
        public string PyCategory { get; set; }
        public string PyHmoprovider { get; set; }
        public string PyLocalOffice { get; set; }
        public string PyDbnotes { get; set; }
        public string TypeOfAgreementCode { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}