// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblPreAdmissionReferralSource
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? ClientId { get; set; }
        public int? DataFormId { get; set; }
        public string PrimaryReferralSource { get; set; }
        public string SecondaryReferralSource { get; set; }
        public string ReferralSourceNote { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdateOn { get; set; }
        public int? EnrollmentId { get; set; }
        public string Program { get; set; }
        public int? IsDeleted { get; set; }
        public string ReferralOrganization { get; set; }
        public string ReferralName { get; set; }
        public int? AccountNotInList { get; set; }
        public int? ContactNotInList { get; set; }
        public string WhyLeftTreatmentOfBhg { get; set; }
        public string WhyComingBackToBhg { get; set; }
        public string MostWantToDoDifferently { get; set; }
        public string Organization { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool? IsPatientReadmit { get; set; }
        public string ReferralOrganizationId { get; set; }
        public string ReferralNameId { get; set; }
    }
}