// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblReAssessmentTreatment
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int ReassessmentId { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? AreYouSatisfiedWith { get; set; }
        public int? IsEventuallyTaperingOff { get; set; }
        public int? DoYouPlanOnTaperingOff { get; set; }
        public string WhatNeedsDoYouHaveThatWeCanHelpYou { get; set; }
        public string WhatHaveYouLearnedAboutWhatYouPrefer { get; set; }
        public int? ClientId { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}