// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblReAssessmentFamily
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int ReassessmentId { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? DoYouHaveStableHousingOfYourOwn { get; set; }
        public int? AreYouSafeFromPhysicalOrSexualAbuseInYourHome { get; set; }
        public int? DoYouHaveLegalCustodyOfYourChildren { get; set; }
        public int? DoYouHaveAnyOpenCasesWithYourLocalDepartment { get; set; }
        public int? DoYouHaveEnoughMoney { get; set; }
        public string CommentsFamily { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}