// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblReAssessmentOccupational
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int ReassessmentId { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? WhatIsYourCurrentEmploymentStatus { get; set; }
        public int? AreYouCurrentlyAfulltimeStudent { get; set; }
        public int? AreYouCurrentlyAparttimeStudent { get; set; }
        public int? HaveYouFoundAparttimeOrFulltimeJob { get; set; }
        public string CommentsOccupational { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}