// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblReAssessmentPhysicalHealth
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int ReassessmentId { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? HaveYouInjectedDrugs { get; set; }
        public int? HaveYouHadAnyUnsafeSex { get; set; }
        public int? HaveYouBeenTestedForHivandHepatitisC { get; set; }
        public bool? ChkboxNa { get; set; }
        public bool? ChkboxHivnegative { get; set; }
        public bool? ChkboxHivpostive { get; set; }
        public bool? ChkboxHepatitisCnegative { get; set; }
        public bool? ChkboxHepatitisCpostive { get; set; }
        public int? IfYouWereHivpositive { get; set; }
        public int? IfYouWereHepatitisCpositive { get; set; }
        public int? DoYouHaveAprimaryCarePractitionerOrClinic { get; set; }
        public int? HowHasYourPhysicalHealthChanged { get; set; }
        public int? HaveYouCalled911OrBeeniItheEmergencyRoom { get; set; }
        public string CommentsPhysicalHealth { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}