// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblReAssessmentSocial
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int ReassessmentId { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? DoYouHaveAnyFriendsRorFamilyMembersWhoDontDrink { get; set; }
        public int? DoYouHaveFriendsAndFamilyWhoYouCanCountOnToSupportYou { get; set; }
        public int? DoYouKnowOfAnyPeerSupport { get; set; }
        public string CommentsSocial { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}