// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblReAssessmentLegal
    {
        public string SiteCode { get; set; }
        public int Id { get; set; }
        public int ReassessmentId { get; set; }
        public int? PreAdmissionId { get; set; }
        public int? HaveYouBeenArrested { get; set; }
        public int? DoYouHaveAnyOpenOrPendingCourtCases { get; set; }
        public int? AreYouOnProbationOrPayrole { get; set; }
        public int? AreYouInvolvedWithAdrugTreatmentCourt { get; set; }
        public int? DoYouHaveAnyOpenCriminalCases { get; set; }
        public int? DoYouHaveAnyOpenWarrants { get; set; }
        public int? DoYouOweMoneyForCourtFinesOrFees { get; set; }
        public string CommentsLegal { get; set; }
        public DateTime? LastModAt { get; set; }
    }
}