// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblRowTrax
    {
        public string SiteCode { get; set; }
        public DateTime Rcdate { get; set; }
        public string TblName { get; set; }
        public int? SammsCnt { get; set; }
        public int? AzureCnt { get; set; }
        public DateTime LastModAt { get; set; }
    }
}