// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_Schedule", Schema = "tsk")]
    public partial class TblSchedule
    {
        [Key]
        public int ScheduleId { get; set; }
        public bool Enabled { get; set; }
        public int RowState { get; set; }
        [Required]
        [StringLength(50)]
        public string LastModBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int TriggerKey { get; set; }
        public int ActionKey { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime NextRunTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastRunTime { get; set; }
        [StringLength(50)]
        public string LastOpResult { get; set; }
    }
}