using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Runtime.InteropServices;
using System.Text;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace BHG_DR_LIB.Models
{
    public partial class TblSFPatientPreAdmission
    {
        public string SiteCode { get; set; }
        public int ID { get; set; }
        public int PatientID { get; set; }
        public int? RegistrationModeID { get; set; }
        public bool? IsIntakeAppointmentScheduled { get; set; }
        public DateTime? IntakeAppointmentScheduledDateTime { get; set; }
        public int? ReferralSourceID { get; set; }
        public int? ProgramID { get; set; }
        public int? OpiatesUsageNoOfYears { get; set; }
        public int? OpiatesUsageNoOfMonths { get; set; }
        public int? DrugChoiceID { get; set; }
        public int? DrugAdministrationTypeID { get; set; }
        public string IllicitSubstanceOther { get; set; }
        public int? IllicitSubstanceOtherMgPerDay { get; set; }
        public bool? IsCurrentlyInOpiateProgram { get; set; }
        public string CurrentOpiateProgramLocation { get; set; }
        public int? CurrentOpiateProgramNoOfYears { get; set; }
        public int? CurrentOpiateProgramNoOfMonths { get; set; }
        public string CurrentOpiateProgramDose { get; set; }
        public bool? IsPatientAtPainManagementClinic { get; set; }
        public string PainManagementClinicLocation { get; set; }
        public DateTime? PainManagementClinicFromDate { get; set; }
        public DateTime? PainManagementClinicToDate { get; set; }
        public bool? IsHavingLegalPrescription { get; set; }
        public bool? IsAnyLegalPrescriptionForPain { get; set; }
        public bool? IsAnyOngoingMedicalCondition { get; set; }
        public bool? IsCurrentlyPregnant { get; set; }
        public bool? IsSuicidalThoughtWithin72Hours { get; set; }
        public int? SuicidalThoughtIntentScale { get; set; }
        public bool? IsHavingPlanForHowToCommitSuicide { get; set; }
        public bool? IsHomicidalThoughtWithin72Hours { get; set; }
        public bool? IsRecentlyReleasedFromPenal { get; set; }
        public DateTime? ReleasedFromPenalDate { get; set; }
        public bool? IsSpecialAccommodationRequired { get; set; }
        public bool? IsAbleToAttendTreatementCenterDaily { get; set; }
        public bool? IsAbleToPayIntakeAndWeeklyFee { get; set; }
        public bool? IsEligibleForFurtherAssessment { get; set; }
        public bool? IsReferralOffered { get; set; }
        public string ReferralOfferedList { get; set; }
        public bool? RejectedReferralOffered { get; set; }
        public string ReasonSeekingTreatment { get; set; }
        public bool? IsPatientAdmitted { get; set; }
        public bool? IsParticipitatingInOtherOpioidProgram { get; set; }
        public bool? IsPresentedWithoutIDProof { get; set; }
        public bool? IsPresentedAtCloseOfDay { get; set; }
        public bool? IsRequestedAdmissionDrUnavailable { get; set; }
        public int? RequestedAdmissionDay { get; set; }
        public bool? RequestedAdmissionAMOrPM { get; set; }
        public bool? IsUnableToPay { get; set; }
        public bool? IsUnableToProvideEvidenceofAddiction { get; set; }
        public bool? IsAddictionToUnstableNeeding { get; set; }
        public bool? IsImpairment { get; set; }
        public bool? IsMedicalProblemsNeedingStabilization { get; set; }
        public bool? IsPsychiatricProblemNeedingInpatientTreatment { get; set; }
        public bool? IsServiceDeclined { get; set; }
        public bool? IsOther { get; set; }
        public string OtherDescription { get; set; }
        public string Comments { get; set; }
        public bool? Active { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdateOn { get; set; }
        public DateTime? PreAdmissionDate { get; set; }
        public string LegalPrescription1 { get; set; }
        public string LegalPrescription2 { get; set; }
        public string LegalPrescription3 { get; set; }
        public string MedicalCondition1 { get; set; }
        public string MedicalCondition2 { get; set; }
        public string MedicalCondition3 { get; set; }
        public string DrugofchoiceAdministered { get; set; }
        public bool? requestedAdmissionDayFri { get; set; }
        public bool? requestedAdmissionDayMon { get; set; }
        public bool? requestedAdmissionDayThu { get; set; }
        public bool? requestedAdmissionDayTue { get; set; }
        public bool? requestedAdmissionDayWed { get; set; }
        public string AccomodationNeeded { get; set; }
        public string AcknowledgeClientSignature { get; set; }
        public DateTime? AcknowledgeClientSignatureDate { get; set; }
        public DateTime? AcknowledgeClientSignatureDateP { get; set; }
        public string AcknowledgeClientSignatureP { get; set; }
        public string AcknowledgeWitnessSignature { get; set; }
        public DateTime? AcknowledgeWitnessSignatureDate { get; set; }
        public DateTime? AcknowledgeWitnessSignatureDateP { get; set; }
        public string AcknowledgeWitnessSignatureP { get; set; }
        public bool? ActiveP { get; set; }
        public string AlcoholAmount { get; set; }
        public string AlcoholLastDrink { get; set; }
        public string ApplicantName { get; set; }
        public int? AreYouCurrentlyPregnant { get; set; }
        public bool? Biopsychosocialassessment { get; set; }
        public bool? BiopsychosocialassessmentP { get; set; }
        public string BiopsychosocialText { get; set; }
        public string BiopsychosocialTextP { get; set; }
        public bool? BringIDProof { get; set; }
        public bool? BringInsuranceCard { get; set; }
        public string ChronicMedicalCondition { get; set; }
        public string ClientDetails { get; set; }
        public string ClientNameP { get; set; }
        public bool? ClinicInfo { get; set; }
        public DateTime? Created { get; set; }
        public string CreatedByP { get; set; }
        public DateTime? CreatedP { get; set; }
        public string CurrentlyMedicatedTreatmentOther { get; set; }
        public DateTime? CurrentOpiateProgramFrom { get; set; }
        public DateTime? CurrentOpiateProgramTo { get; set; }
        public string CurrentOpiateWhatProgram { get; set; }
        public bool? CurrntlyRecevingTreatmentForCondition { get; set; }
        public string DailyTime { get; set; }
        public int? DataFormId { get; set; }
        public DateTime? Date { get; set; }
        public DateTime? DateP { get; set; }
        public bool? daysafterdischarge { get; set; }
        public bool? daysafterdischargeP { get; set; }
        public bool? DeniedDuetoCapacity { get; set; }
        public string describeother { get; set; }
        public string describeother1 { get; set; }
        public string describeother1P { get; set; }
        public string describeother2 { get; set; }
        public string describeother2P { get; set; }
        public string describeotherP { get; set; }
        public bool? Diagnosis { get; set; }
        public bool? DiagnosisP { get; set; }
        public string DiagnosisText { get; set; }
        public string DiagnosisTextP { get; set; }
        public string DischargeReasonsText { get; set; }
        public string DischargeReasonsTextP { get; set; }
        public bool? DischargeSummary { get; set; }
        public bool? DischargeSummaryP { get; set; }
        public string DischargeSummaryText { get; set; }
        public string DischargeSummaryTextP { get; set; }
        public string DoctorSignature { get; set; }
        public DateTime? DoctorSignatureDate { get; set; }
        public int? dropdownPresentlyInPainScale1to10 { get; set; }
        public string DrugApplicantTime { get; set; }
        public string DrugDaily { get; set; }
        public string DrugLastUsed { get; set; }
        public string DrugTaken { get; set; }
        public string DrugUsing { get; set; }
        public int? EnrollmentId { get; set; }
        public string GynDoctorProviderName { get; set; }
        public string GynDoctorProviderPhone { get; set; }
        public bool? HasGynDoctor { get; set; }
        public string ImmediateAssessment { get; set; }
        public string ImmediateAssessment911 { get; set; }
        public int? InformationToObtained { get; set; }
        public bool? InformationToObtainedFax { get; set; }
        public bool? InformationToObtainedFaxP { get; set; }
        public int? InformationToObtainedP { get; set; }
        public bool? InformationToObtainedVerbal { get; set; }
        public bool? InformationToObtainedVerbalP { get; set; }
        public bool? InformationToObtainedWritten { get; set; }
        public bool? InformationToObtainedWrittenP { get; set; }
        public string InitialSceeningParticipationText { get; set; }
        public string InitialSceeningParticipationTextP { get; set; }
        public string InitialScreeningSummaryText { get; set; }
        public string InitialScreeningSummaryTextP { get; set; }
        public string InsuranceDescription { get; set; }
        public string InsuranceType { get; set; }
        public string IntakeProgram { get; set; }
        public DateTime? IntakeProgramDate { get; set; }
        public bool? IsAllergies { get; set; }
        public bool? IsAmPm { get; set; }
        public bool? IsAnyPrescriptionForPain { get; set; }
        public bool? IsApplicantPregnant { get; set; }
        public bool? IsBehaviorallyunstabldangerous { get; set; }
        public bool? IsClinicAddress { get; set; }
        public bool? IsCSUAtFullCapacity { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsDetox { get; set; }
        public bool? IsDidnotMeetMedicalNecessity { get; set; }
        public bool? IsDrinkingAlcohol { get; set; }
        public bool? IsEVSCompleted { get; set; }
        public bool? IsInsurance { get; set; }
        public bool? IsInsuranceAvailable { get; set; }
        public bool? IsInsuranceCard { get; set; }
        public bool? IsMaintenance { get; set; }
        public bool? IsMedicalEmergency { get; set; }
        public bool? isOverTheCounterMedications { get; set; }
        public bool? IsPackets { get; set; }
        public bool? IsPastTreatmentHistory { get; set; }
        public bool? IsPhysicalHealthUnstable { get; set; }
        public bool? IsPictureId { get; set; }
        public bool? IsPlanSendTime { get; set; }
        public bool? IsPreviousMentalHealthTreatment { get; set; }
        public bool? IsTakingPrescriptionMedication { get; set; }
        public bool? IsTriagedtoMedicalDetoxFacility { get; set; }
        public string LastUsedTime { get; set; }
        public string MedicalConditionsProviderName1 { get; set; }
        public string MedicalConditionsProviderName2 { get; set; }
        public string MedicalConditionsProviderPhone1 { get; set; }
        public string MedicalConditionsProviderPhone2 { get; set; }
        public string MedicalEmergencyDescribe { get; set; }
        public bool? Medicalinformation { get; set; }
        public bool? MedicalinformationP { get; set; }
        public string MedicalText { get; set; }
        public string MedicalTextP { get; set; }
        public string MedicationConditions { get; set; }
        public string MedicationName1 { get; set; }
        public string MedicationName2 { get; set; }
        public string MedicationName3 { get; set; }
        public string MedicationName4 { get; set; }
        public string MedicationName5 { get; set; }
        public string MentalHealthTreatmentDescription { get; set; }
        public DateTime? Modified { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedByP { get; set; }
        public DateTime? ModifiedP { get; set; }
        public string NeedReferal { get; set; }
        public string ObservationComments { get; set; }
        public int? OfficeUseTime { get; set; }
        public string OfficeUseWhy { get; set; }
        public string OngoingMedicalConditionsWha { get; set; }
        public bool? other { get; set; }
        public bool? other2 { get; set; }
        public bool? other2P { get; set; }
        public bool? OtherCode { get; set; }
        public bool? otherP { get; set; }
        public string OtherText { get; set; }
        public string OtherTextP { get; set; }
        public string OverTheCounterMedicationsText1 { get; set; }
        public bool? Participationininitialsceeningprocess { get; set; }
        public bool? ParticipationininitialsceeningprocessP { get; set; }
        public string PatientSignature { get; set; }
        public DateTime? PatientSignatureDate { get; set; }
        public bool? PersonForIntakeProcess { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Phone4 { get; set; }
        public string Phone5 { get; set; }
        public bool? PlanOfSuicide { get; set; }
        public bool? PlanOnSpendingTimeAtClinic { get; set; }
        public string PreAdd_Address { get; set; }
        public string Prescriber1 { get; set; }
        public string Prescriber2 { get; set; }
        public string Prescriber3 { get; set; }
        public string Prescriber4 { get; set; }
        public string Prescriber5 { get; set; }
        public string ProgressRecoveryGoalsText { get; set; }
        public string ProgressRecoveryGoalsTextP { get; set; }
        public bool? Progresstowardsrecoverygoals { get; set; }
        public bool? ProgresstowardsrecoverygoalsP { get; set; }
        public bool? ProofOfOpiateDependence { get; set; }
        public int? PurposeOfObtainingRelease { get; set; }
        public int? PurposeOfObtainingReleaseP { get; set; }
        public string Reason { get; set; }
        public bool? Reasonsfordischarge { get; set; }
        public bool? ReasonsfordischargeP { get; set; }
        public bool? RecentHeadTrauma { get; set; }
        public bool? Recoveryplansorgoals { get; set; }
        public bool? RecoveryplansorgoalsP { get; set; }
        public string RecoveryPlansText { get; set; }
        public string RecoveryPlansTextP { get; set; }
        public bool? Referralrecommendations { get; set; }
        public bool? ReferralrecommendationsP { get; set; }
        public string ReferralRecommendationsText { get; set; }
        public string ReferralRecommendationsTextP { get; set; }
        public string ReferredBy { get; set; }
        public bool? Relapseepisodes { get; set; }
        public bool? RelapseepisodesP { get; set; }
        public string RelapseEpisodesText { get; set; }
        public string RelapseEpisodesTextP { get; set; }
        public string RevocationClientSignature { get; set; }
        public DateTime? RevocationClientSignatureDate { get; set; }
        public DateTime? RevocationClientSignatureDateP { get; set; }
        public string RevocationClientSignatureP { get; set; }
        public string RevocationWitnessSignature { get; set; }
        public DateTime? RevocationWitnessSignatureDate { get; set; }
        public DateTime? RevocationWitnessSignatureDateP { get; set; }
        public string RevocationWitnessSignatureP { get; set; }
        public string RNPStaffSign { get; set; }
        public DateTime? RNPStaffSignDate { get; set; }
        public int? SammsProgramID { get; set; }
        public bool? SeizureInPast7Days { get; set; }
        public string SetupAppointment { get; set; }
        public DateTime? SignatureDate { get; set; }
        public string SignatureOfConsenP { get; set; }
        public string SignatureOfConsent { get; set; }
        public string SignatureOfConsentP { get; set; }
        public string SignatureRnpStaff { get; set; }
        public string SubstanceAbuseWhat { get; set; }
        public string SubstanceAbuseWhen { get; set; }
        public string SubstanceAbuseWhere { get; set; }
        public bool? Summaryofinitialscreeningprocess { get; set; }
        public bool? SummaryofinitialscreeningprocessP { get; set; }
        public string SupervisorSignature { get; set; }
        public DateTime? SupervisorSignatureDate { get; set; }
        public string TakenTime { get; set; }
        public string TimeFinishingRNtriage { get; set; }
        public string TimeStartingRNtriage { get; set; }
        public bool? Treatmentrecommendations { get; set; }
        public bool? TreatmentrecommendationsP { get; set; }
        public string TreatmentText { get; set; }
        public string TreatmentTextP { get; set; }
        public int? TypeOfMedication { get; set; }
        public bool? Upondischargefromtreatment { get; set; }
        public bool? UpondischargefromtreatmentP { get; set; }
        public bool? Uponreceiptofinformationrequested { get; set; }
        public bool? UponreceiptofinformationrequestedP { get; set; }
        public bool? Uponreceiptofpaymentforservicesrendered { get; set; }
        public bool? UponreceiptofpaymentforservicesrenderedP { get; set; }
        public bool? Urinalysisresults { get; set; }
        public bool? UrinalysisresultsP { get; set; }
        public string UrinalysisText { get; set; }
        public string UrinalysisTextP { get; set; }
        public string WhatAccomodations { get; set; }
        public int? ParentPreAdmissionId { get; set; }
        public bool? IsRequireChildCare { get; set; }
        public bool? AnswerRangeThree { get; set; }
        public bool? AnswerRangeSix { get; set; }
        public bool? AnswerRangeNine { get; set; }
        public bool? AnswerRangeAbove { get; set; }
        public bool? IsReliableTransportation { get; set; }
        public int? RequireTransportationServices { get; set; }
        public int? IsTransfer { get; set; }
        public string WhereTransfer { get; set; }
        public int? dropdownNumberOfChildren { get; set; }
        public string Incarcenated { get; set; }
        public string ClientAddress { get; set; }
        public bool? IsEmployed { get; set; }
        public bool? IsAttemptedSuicide { get; set; }
        public bool? IsThoughtsOfKilling { get; set; }
        public bool? isMentalHealthTreatment { get; set; }
        public string MentalHealthTreatmentWhere { get; set; }
        public string MentalHealthTreatmentWhen { get; set; }
        public string MentalHealthTreatmentWhat { get; set; }
        public string ThoughtsOfHurtingTxt { get; set; }
        public string SuicideDetailsTxt { get; set; }
        public string ReliableTransportationTxt { get; set; }
        public string EmployedYesTxt { get; set; }
        public string EmployedNoTxt { get; set; }
        public bool? IsPlanForHowToHurtSomeElse { get; set; }
        public int? PacketTypeID { get; set; }
        public string UsingOpioids { get; set; }
        public bool? TimeOfIntake { get; set; }
        public DateTime? SubstanceUseFromDate { get; set; }
        public DateTime? SubstanceUseToDate { get; set; }
        public DateTime? MentalHealthFromDate { get; set; }
        public DateTime? MentalHealthToDate { get; set; }
        public int? ReasonForDenial { get; set; }
        public string DischargeReason { get; set; }
        public string ReferedTo { get; set; }
        public DateTime? DateOfStaffSignature { get; set; }
        public string nameOfWitness { get; set; }
        public int? staffAtHCRC { get; set; }
        public int? SUDinformationMA { get; set; }
        public int? protectedHealthInformationMA { get; set; }
        public string namedIndividualMA { get; set; }
        public string namedEntityMA { get; set; }
        public string namedThirdPartyMA { get; set; }
        public string namedEntityWithoutTreatmentMA { get; set; }
        public string namedIndividualPaticipantMA { get; set; }
        public string genralTreatingproviderrelationshipMA { get; set; }
        public string purposeOfDisclosureMA { get; set; }
        public string exclusionsMA { get; set; }
        public string representativesRelationshiptoPatientMA { get; set; }
        public string HCRCClinicLocationMA { get; set; }
        public string AddressMA { get; set; }
        public string PhoneMA { get; set; }
        public string FAXMA { get; set; }
        public string unlessrevokedMA { get; set; }
        public bool? istheresubstanceusehistory { get; set; }
        public bool? iscurrentlypatientpainmanagementmethadone { get; set; }
        public string txtpatientatpainmanagementclinicmethadone { get; set; }
        public bool? interestedtransferringetsyes { get; set; }
        public bool? ispreviouslybeenpatientmedicationassisted { get; set; }
        public string txtpreviouslybeenpatientmedicationassisted { get; set; }
        public DateTime? datepreviouslypatientmedicationassisted { get; set; }
        public bool? ispregnant { get; set; }
        public DateTime? currentlypregnant { get; set; }
        public int? isplantopaytreatment { get; set; }
        public string txtplantopaytreatmentprivateinsurance { get; set; }
        public string txtplantopaytreatmentother { get; set; }
        public bool? isdoyouhavepicture { get; set; }
        public DateTime? datetimelastopioid { get; set; }
        public bool? issymptomsofopioidwithdrawal { get; set; }
        public string txtsymptomsofopioidwithdrawaltrue { get; set; }
        public bool? ishadalcoholinlast12hours { get; set; }
        public string txthadanyalcohol { get; set; }
        public bool? isprioretspatientyes { get; set; }
        public DateTime? prioretspatient { get; set; }
        public DateTime? lastprescription { get; set; }
        public bool? ishaveyouhospitalizedinlast30daysyes { get; set; }
        public string txthospitalisedlast30days { get; set; }
        public string nameOfWitnessQ8 { get; set; }
        public string unlessrevokedQ8 { get; set; }
        public string FAXQ8 { get; set; }
        public string PhoneQ8 { get; set; }
        public string AddressQ8 { get; set; }
        public string HCRCClinicLocationQ8 { get; set; }
        public string representativesRelationshiptoPatientQ8 { get; set; }
        public string exclusionsQ8 { get; set; }
        public string purposeOfDisclosureQ8 { get; set; }
        public string genralTreatingproviderrelationshipQ8 { get; set; }
        public string namedIndividualPaticipantQ8 { get; set; }
        public string namedEntityWithoutTreatmentQ8 { get; set; }
        public string namedThirdPartyQ8 { get; set; }
        public string namedEntityQ8 { get; set; }
        public string namedIndividualQ8 { get; set; }
        public int? protectedHealthInformationQ8 { get; set; }
        public int? SUDinformationQ8 { get; set; }
        public int? staffAtHCRCQ8 { get; set; }
        public string AdditionalDoc { get; set; }
        public bool? ChkboxSUDInformationQ2_1 { get; set; }
        public bool? ChkboxSUDInformationQ2_2 { get; set; }
        public bool? ChkboxSUDInformationQ2_3 { get; set; }
        public bool? ChkboxSUDInformationQ2_4 { get; set; }
        public bool? ChkboxSUDInformationQ2_5 { get; set; }
        public bool? ChkboxSUDInformationQ2_6 { get; set; }
        public bool? ChkboxSUDInformationQ2_7 { get; set; }
        public bool? ChkboxSUDInformationQ2_8 { get; set; }
        public bool? ChkboxSUDInformationQ2_9 { get; set; }
        public bool? ChkboxSUDInformationQ2_10 { get; set; }
        public bool? ChkboxSUDInformationQ2_11 { get; set; }
        public bool? ChkboxProtectedHealthInformationQ2_1 { get; set; }
        public bool? ChkboxProtectedHealthInformationQ2_2 { get; set; }
        public bool? ChkboxProtectedHealthInformationQ2_3 { get; set; }
        public bool? ChkboxProtectedHealthInformationQ2_4 { get; set; }
        public bool? ChkboxSUDInformationQ8_1 { get; set; }
        public bool? ChkboxSUDInformationQ8_2 { get; set; }
        public bool? ChkboxSUDInformationQ8_3 { get; set; }
        public bool? ChkboxSUDInformationQ8_4 { get; set; }
        public bool? ChkboxSUDInformationQ8_5 { get; set; }
        public bool? ChkboxSUDInformationQ8_6 { get; set; }
        public bool? ChkboxSUDInformationQ8_7 { get; set; }
        public bool? ChkboxSUDInformationQ8_8 { get; set; }
        public bool? ChkboxSUDInformationQ8_9 { get; set; }
        public bool? ChkboxSUDInformationQ8_10 { get; set; }
        public bool? ChkboxSUDInformationQ8_11 { get; set; }
        public bool? ChkboxProtectedHealthInformationQ8_1 { get; set; }
        public bool? ChkboxProtectedHealthInformationQ8_2 { get; set; }
        public bool? ChkboxProtectedHealthInformationQ8_3 { get; set; }
        public bool? ChkboxProtectedHealthInformationQ8_4 { get; set; }
        public bool? radioNamedIndividualQ2 { get; set; }
        public bool? radioNamedthirdpartyPayerQ2 { get; set; }
        public bool? radioNamedEntityProvideRelationWithMeQ2 { get; set; }
        public bool? radioNamedEntityWithoutProvideRelationWithMeQ2 { get; set; }
        public bool? radioNamedIndividualParticipantQ2 { get; set; }
        public bool? radioGeneralDesignationQ2 { get; set; }
        public bool? radioNamedIndividualQ8 { get; set; }
        public bool? radioNamedthirdpartyPayerQ8 { get; set; }
        public bool? radioNamedEntityProvideRelationWithMeQ8 { get; set; }
        public bool? radioNamedEntityWithoutProvideRelationWithMeQ8 { get; set; }
        public bool? radioNamedIndividualParticipantQ8 { get; set; }
        public bool? radioGeneralDesignationQ8 { get; set; }
        public int? radioNamedIndividualQ2select { get; set; }
        public int? radioNamedIndividualParticipantQ2select { get; set; }
        public int? radioNamedIndividualQ8select { get; set; }
        public int? radioNamedIndividualParticipantQ8select { get; set; }
        public bool? chkBoxRevokeROIQ2 { get; set; }
        public string txtBoxRevokeROIQ2 { get; set; }
        public bool? chkBoxRevokeROIQ8 { get; set; }
        public string txtBoxRevokeROIQ8 { get; set; }
        public int? NamedEntitesIDQ2 { get; set; }
        public int? NamedEntitesIDQ8 { get; set; }
        public bool? ChkboxSUDInformationQ2_12 { get; set; }
        public bool? ChkboxSUDInformationQ2_13 { get; set; }
        public string SUDInformationOtherQ2 { get; set; }
        public bool? ChkboxSUDInformationQ8_12 { get; set; }
        public bool? ChkboxSUDInformationQ8_13 { get; set; }
        public string SUDInformationOtherQ8 { get; set; }
        public string StaffSignCredentials { get; set; }
        public DateTime? DateofRelease { get; set; }
        public string DoYouHaveInsuranceNo { get; set; }
        public string Version { get; set; }
        public string PrimaryReferralSourceNote { get; set; }
        public string SecondaryReferralSource { get; set; }
        public string PrimaryReferralSource { get; set; }
        public int? InitialScreening { get; set; }
        public int? DDLPrimarySubstance { get; set; }
        public bool? CurrentlyUsingOpoidDrug { get; set; }
        public bool? MedicatedAssistedTreatmentProgram { get; set; }
        public bool? PainManagementClinic { get; set; }
        public bool? ReceivedTreatmentForAddiction { get; set; }
        public bool? RequireAssistiveTechnologies { get; set; }
        public bool? HaveYouUsedOpoidDrug { get; set; }
        public bool? AnswerAllQuestion { get; set; }
        public string AnswerAllQuestionTxt { get; set; }
        public DateTime? AppointmentDate { get; set; }
        public string AppointmentTime { get; set; }
        public string ScreenedBy { get; set; }
        public DateTime? ScreenedByDate { get; set; }
        public int? FollowupScreening { get; set; }
        public bool? ReviewedResponsesFromCallCenter { get; set; }
        public string AnyChangestoInformation { get; set; }
        public bool? HadAnySuicidalThoughts { get; set; }
        public string HadAnySuicidalThoughtsTxt { get; set; }
        public bool? HadAnyHomicidalThoughts { get; set; }
        public string HadAnyHomicidalThoughtsTxt { get; set; }
        public bool? HaveBeenCarcerated { get; set; }
        public bool? HaveAnyUrgentNeeds { get; set; }
        public string AdditionalComments { get; set; }
        public string Comment { get; set; }
        public int? ReceiveingAnyTreatment { get; set; }
        public string ReasonforReferral { get; set; }
        public bool? NA { get; set; }
        public string PacketVersion { get; set; }
        
    }
}
