// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_Triggers", Schema = "tsk")]
    public partial class TblTriggers
    {
        [Key]
        public int TriggerKey { get; set; }
        [Required]
        [StringLength(50)]
        public string LastModBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        public int RowState { get; set; }
        [Required]
        [StringLength(50)]
        public string TriggerName { get; set; }
        public bool TriggerEnabled { get; set; }
        public int TaskType { get; set; }
        public int TrgSetting { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime TrgStartTime { get; set; }
        public bool? TrgRecur { get; set; }
        public int? TrgRecurPrd { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TrgExpire { get; set; }
        public int? TrgWklyDays { get; set; }
        [Column("TrgMMonths")]
        [StringLength(255)]
        public string TrgMmonths { get; set; }
        [Column("TrgMDays")]
        [StringLength(255)]
        public string TrgMdays { get; set; }
        public int? TrgDelay { get; set; }
        public int? TrgRepeat { get; set; }
        public int? TrgRepeatDuration { get; set; }
    }
}