// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class TblUasched
    {
        public string SiteCode { get; set; }
        public int UasId { get; set; }
        public int? UasLngCltId { get; set; }
        public DateTime? UasDt { get; set; }
        public DateTime? UasDtAdded { get; set; }
        public string UasStat { get; set; }
        public DateTime? UasStatDt { get; set; }
        public string UasStatUser { get; set; }
        public int? LngCpano { get; set; }
        public string UasNote { get; set; }
        public string OldNum { get; set; }
        public string OldClient { get; set; }
        public decimal? RepOldUas { get; set; }
        public string UasCollectedBy { get; set; }
        public DateTime? UasCollectedDate { get; set; }
        public DateTime? UasManifestDate { get; set; }
        public string UasPanel { get; set; }
        public string UasPanelOther { get; set; }
        public string UasType { get; set; }
        public bool? UasEtg { get; set; }
        public string Uapriority { get; set; }
        public DateTime? Uasticketprintdate { get; set; }
        public int RowChkSum { get; set; }
        public DateTime LastModAt { get; set; }
        public bool? RowState { get; set; }
    }
}