// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_User", Schema = "ctrl")]
    public partial class TblUser
    {
        [Key]
        [Column("uskey")]
        public int Uskey { get; set; }
        [Required]
        [Column("usrName")]
        [StringLength(50)]
        public string UsrName { get; set; }
        [Column("usrPassword")]
        [StringLength(50)]
        public string UsrPassword { get; set; }
        [Column("usrGroups", TypeName = "ntext")]
        public string UsrGroups { get; set; }
        [Column("usrDescription")]
        [StringLength(50)]
        public string UsrDescription { get; set; }
        [Column("usrFName")]
        [StringLength(50)]
        public string UsrFname { get; set; }
        [Column("usrLName")]
        [StringLength(50)]
        public string UsrLname { get; set; }
        [Column("usrSSN")]
        [StringLength(50)]
        public string UsrSsn { get; set; }
        [Column("usrcred")]
        [StringLength(250)]
        public string Usrcred { get; set; }
        [Column("usrACTIVE")]
        public bool? UsrActive { get; set; }
        [Column("usrPasswordChanged", TypeName = "datetime")]
        public DateTime? UsrPasswordChanged { get; set; }
        [Column("usrSignature", TypeName = "ntext")]
        public string UsrSignature { get; set; }
        [Column("usrTEMPLATE")]
        [StringLength(250)]
        public string UsrTemplate { get; set; }
        [Column("usrtemplatechanged")]
        public bool? Usrtemplatechanged { get; set; }
        [Column("usrCounselor")]
        public bool? UsrCounselor { get; set; }
        [Column("usrPIN")]
        [StringLength(10)]
        public string UsrPin { get; set; }
        [Column("usrCOSIG")]
        public bool? UsrCosig { get; set; }
        [Column("usrSignatureImage")]
        public byte[] UsrSignatureImage { get; set; }
        [Column("usrSUPER")]
        [StringLength(100)]
        public string UsrSuper { get; set; }
        [Column("isDASAcounselor")]
        public int? IsDasacounselor { get; set; }
        [Column("usrLocation")]
        [StringLength(100)]
        public string UsrLocation { get; set; }
        [Column("usrRole")]
        [StringLength(100)]
        public string UsrRole { get; set; }
        public string EmailId { get; set; }
        public string Userfullname { get; set; }
        [Column("usrCalendarUser")]
        public bool? UsrCalendarUser { get; set; }
        [Column("usrDEA")]
        [StringLength(25)]
        public string UsrDea { get; set; }
        [Column("usrDoctor")]
        public bool? UsrDoctor { get; set; }
        [Column("usrLicensed")]
        public bool? UsrLicensed { get; set; }
        [Column("usrnpi")]
        [StringLength(25)]
        public string Usrnpi { get; set; }
        [Column("usrphone")]
        [StringLength(25)]
        public string Usrphone { get; set; }
        [Column("usrxdea")]
        [StringLength(25)]
        public string Usrxdea { get; set; }
        [Column("usrExt")]
        public string UsrExt { get; set; }
        [Column("usrTaxonomy")]
        public string UsrTaxonomy { get; set; }
    }
}