// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_UAResults", Schema = "pats")]
    public partial class TblUaresults
    {
        [Key]
        [StringLength(25)]
        public string SiteCode { get; set; }
        public int RowChkSum { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [Column("uarResultDt", TypeName = "datetime")]
        public DateTime UarResultDt { get; set; }
        [Key]
        [Column("uarID")]
        public int UarId { get; set; }
        [Column("uarLngCltID")]
        public int? UarLngCltId { get; set; }
        [Column("uarSchedID")]
        public int? UarSchedId { get; set; }
        [Column("uarDropDt", TypeName = "datetime")]
        public DateTime? UarDropDt { get; set; }
        [Column("uarCreatedBy")]
        [StringLength(100)]
        public string UarCreatedBy { get; set; }
        [Column("uarCreatedDt", TypeName = "datetime")]
        public DateTime? UarCreatedDt { get; set; }
        [Column("cpID")]
        public int? CpId { get; set; }
        [Column("uaNOTE", TypeName = "ntext")]
        public string UaNote { get; set; }
        [Column("oldnum")]
        public int? Oldnum { get; set; }
        [Column("oldClient")]
        [StringLength(50)]
        public string OldClient { get; set; }
        //[Column("upsize_ts")]
        //public byte[] UpsizeTs { get; set; }
        [Column("repOldUAr", TypeName = "numeric(18, 0)")]
        public decimal? RepOldUar { get; set; }
        [Column("uarLabKey")]
        [StringLength(50)]
        public string UarLabKey { get; set; }
        [Column("uarUpdatedBy")]
        [StringLength(50)]
        public string UarUpdatedBy { get; set; }
        [Column("uarUpdatedDt", TypeName = "datetime")]
        public DateTime? UarUpdatedDt { get; set; }
        [Column("uaType")]
        [StringLength(100)]
        public string UaType { get; set; }
        [Column("SiteID")]
        public int? SiteId { get; set; }
        [Column("uaDBnotes")]
        [StringLength(100)]
        public string UaDbnotes { get; set; }
        [Column("uaNurseNote")]
        [StringLength(100)]
        public string UaNurseNote { get; set; }
        [Column("uaSig", TypeName = "ntext")]
        public string UaSig { get; set; }
        [Column("uaSigDt", TypeName = "datetime")]
        public DateTime? UaSigDt { get; set; }
        [Column("uaSigImg")]
        public byte[] UaSigImg { get; set; }
        [Column("uaSigUser")]
        [StringLength(50)]
        public string UaSigUser { get; set; }
        [Column("location_")]
        [StringLength(50)]
        public string Location { get; set; }
        [Column("scheduledDate", TypeName = "datetime")]
        public DateTime? ScheduledDate { get; set; }
        [Column("uaBase64")]
        public string UaBase64 { get; set; }
        [Column("UAProgram")]
        [StringLength(50)]
        public string Uaprogram { get; set; }
        public string LabName { get; set; }
        public string UAEval { get; set; }
    }
}