// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    [Table("tbl_XRef", Schema = "ctrl")]
    public partial class TblXref
    {
        [Key]
        [Column("xref")]
        public int Xref { get; set; }
        public int DisplayOrder { get; set; }
        [Required]
        [StringLength(25)]
        public string Code { get; set; }
        [Required]
        [StringLength(50)]
        public string LastModBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastModAt { get; set; }
        [StringLength(200)]
        public string Descrptn { get; set; }
        [Column("ParentXRef")]
        public int? ParentXref { get; set; }
    }
}