// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    public partial class VwMapSrc2Dsn
    {
        public long ActionKey { get; set; }
        public int ActionStepKey { get; set; }
        public int FieldKey { get; set; }
        [Required]
        [StringLength(50)]
        public string FieldName { get; set; }
        public bool PHC_Enabled { get; set; }
        public bool Enabled { get; set; }
        public int? PrimaryKey { get; set; }
        [Required]
        [StringLength(25)]
        public string FieldType { get; set; }
        public int FieldLength { get; set; }
        public int FieldPrecision { get; set; }
        public int FieldScale { get; set; }
        [StringLength(50)]
        public string DsnFieldName { get; set; }
        public bool? Nullable { get; set; }
        [StringLength(255)]
        public string Default { get; set; }
        [StringLength(255)]
        public string FormatConvert { get; set; }
        [StringLength(8000)]
        public string CompKey { get; set; }
    }
}