// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BHG_DR_LIB.Models
{
    public partial class VwReinitRunSchd
    {
        [StringLength(219)]
        public string CompKey { get; set; }
        [Required]
        [StringLength(25)]
        public string SiteCode { get; set; }
        public long ActionKey { get; set; }
        public int StepKey { get; set; }
        public bool Enabled { get; set; }
        [StringLength(25)]
        public string ConType { get; set; }
        [Column("ConnectionID")]
        public int? ConnectionId { get; set; }
        [StringLength(50)]
        public string ConName { get; set; }
        [StringLength(1045)]
        public string ConStr { get; set; }
        [Column("dbName")]
        [StringLength(255)]
        public string DbName { get; set; }
        [StringLength(25)]
        public string CtrlMethod { get; set; }
        [Column(TypeName = "date")]
        public DateTime? EnrollCutoff { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ContractDate { get; set; }
        [StringLength(255)]
        public string ClinicName { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsNewSchema { get; set; }
        [Required]
        [StringLength(50)]
        public string SrcSchema { get; set; }
        [Required]
        [StringLength(100)]
        public string FromTblVw { get; set; }
        [Required]
        [StringLength(50)]
        public string DsnSchema { get; set; }
        [Required]
        [StringLength(500)]
        public string DsnTbl { get; set; }
        [Required]
        [StringLength(1000)]
        public string WhereCondition { get; set; }
        [StringLength(500)]
        public string SortOrder { get; set; }
        public bool ReInitialize { get; set; }
        [Column(TypeName = "date")]
        public DateTime WorkDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? MinDate { get; set; }
    }
}