// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BHG_DR_LIB.Models
{
    public partial class YearlyAuditData
    {
        public string CompKey { get; set; }
        public string SiteCode { get; set; }
        public long ActionKey { get; set; }
        public int StepKey { get; set; }
        public bool Enabled { get; set; }
        public string ConType { get; set; }
        public int? ConnectionId { get; set; }
        public string ConName { get; set; }
        public string ConStr { get; set; }
        public string DbName { get; set; }
        public string CtrlMethod { get; set; }
        public DateTime? EnrollCutoff { get; set; }
        public DateTime? ContractDate { get; set; }
        public string ClinicName { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsNewSchema { get; set; }
        public string SrcSchema { get; set; }
        public string DsnSchema { get; set; }
        public string DsnTbl { get; set; }
        public string WhereCondition { get; set; }
        public string SortOrder { get; set; }
        public bool ReInitialize { get; set; }
        public string WrkYear { get; set; }
        public string FromTblVw { get; set; }
        public string DateField { get; set; }
    }
}